### ISSUE TITLE
Unable to generate the lib for iOS devices

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-sdk#1]
Hi,

MacBook Pro :: Mac OS 10.15 (19A603)
Xcode :: Version 11.1 (11A1027)

I am trying to compile linphone for my iOS app. It is successfully generating frameworks for simulator. But it is not generating for "arm64, armv7". Compilation always end with below message: Any idea how to fix it?

-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk
-- Using sdk version: 13.1
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- broken
CMake Error at /opt/local/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/jfalexvijay/Alex/linphone-sdk/build/ios-armv7/CMakeFiles/CMakeTmp
    
    Run Build Command:"/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_cb57e" "-configuration" "Debug"
    Build settings from command line:
        TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
    
    Prepare build
    note: Using legacy build system
    
    === BUILD TARGET cmTC_cb57e OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===
    
    Check dependencies
    Code Signing Error: Signing for "cmTC_cb57e" requires a development team. Select a development team in the Signing & Capabilities editor.
    
    ** BUILD FAILED **
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    
  CMake will not be able to correctly generate this project.

-- Configuring incomplete, errors occurred!
See also "/Users/jfalexvijay/Alex/linphone-sdk/build/ios-armv7/CMakeFiles/CMakeOutput.log".
See also "/Users/jfalexvijay/Alex/linphone-sdk/build/ios-armv7/CMakeFiles/CMakeError.log".
make: *** [/Users/jfalexvijay/Alex/linphone-sdk/build/ios-armv7-prefix/src/ios-armv7-stamp/Debug/ios-armv7-configure] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution CMake\ Rules build/linphone-sdk.build/Debug/ios-armv7.build/Script-BB0C0221AF6344999CE16EEA.sh
(1 failure)

**Comment by becklo** [comment]
I have the same problem. I tried to use XCode to do the compilation but there are not targets for the project so it is not possible to associate it with a signing team.

**Comment by KyronNextLevel** [comment]
Hi.
Actually there is two problems regarding Xcode11 and iOS 13.
A CMake error may happend and can be fixed with a not merged patch.
https://gitlab.kitware.com/cmake/cmake/issues/19699

The second problem is about signature. We can't push our dev keys on the repo to help you...
As a workaround, if you do not use the Swift wrapper, you can build the linphone-sdk with XCode 10, and eventually build your app with XCode 11.

**Comment by appiotic** [comment]
Hi, I'm facing the same issue
Regarding the "if you do not use the Swift wrapper", how can I disable this option?

I am trying to build it for iOS arm64 with non-GPL, but whatever I try (path is set to XCode 10) I get the same error.
