### ISSUE TITLE
Compiling G729 using docker no cmakelist

### ISSUE THREAD

**Issue by christianjj** [BelledonneCommunications/linphone-sdk#108]
![image3](https://user-images.githubusercontent.com/8798968/105004242-a10fc600-5a6e-11eb-9ec1-2808064e02c9.PNG)

Cmake Error: The source directory "/home/bc/linphone-sdk" does not appear to contain CMakeLists.txt.

**Comment by christianjj** [comment]
this is the link that I pull
docker pull gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android:r17c

**Comment by Viish** [comment]
Either use one of the docker-files inside linphone-sdk repository to create your own or clone linphone-sdk from scratch on your docker VM.
