### ISSUE TITLE
Not receiving a Sip Notify Response for a sucessful Sip Subscribe Request.

### ISSUE THREAD

**Issue by nick2601** [BelledonneCommunications/linphone-sdk#109]
Describe the bug:
There is a usecase in our application that when a sip subscribe is sent out to a server , a notify is received in the app as a response.

To Reproduce
 Construct a Sip Subscribe Packet using core.createsubscribe and you can get notify using the coreListener onNotifyReceived Callback

Expected behavior:
On checking the logs , I got a 200ok for the subscribe packet with the event as presence but the Notify is not received for the corresponding packet

Please complete the following information
 - Device: Nokia 6.1
 - OS:  Android 10
 - Version of the App-4.3.1
 - Version of the SDK -4.5+

**Comment by nick2601** [comment]
> Can you attach SDK logs?
> Also, if the SUBSCRIBE is correctly sent and acknowledged by the proxy, have you considered the issue might be that the proxy doesn't send the NOTIFY ?

After checking the wireshark logs from the server side we could see a Sip Notify going out from the proxy ,but the client is rejecting it 405 error code .

Link to the Debug Logs 
[https://www.linphone.org:444//tmp/600ea165829df_2e013077f9733f5400cf.gz]
Thanks in advance for the help

**Comment by Viish** [comment]
From our code the NOTIFY is dismissed because there is not "Event" header in the received NOTIFY.
I can't tell you why we deny such message, that's not my area of expertise.
Can you check your proxy to see if you can add this header?

**Comment by nick2601** [comment]
> From our code the NOTIFY is dismissed because there is not "Event" header in the received NOTIFY.
> I can't tell you why we deny such message, that's not my area of expertise.
> Can you check your proxy to see if you can add this header?

We have added the "Event" header in the outgoing Notify from the server , still we are not able to see a Notify Response received at the Linphone end.

Wireshark trace from the server 
```
2021/01/27 03:12:24.298077 172.31.37.34:7684 -> 172.27.224.22:38193
NOTIFY sip:mcx.test-111.iitb@172.27.224.22:38193;transport=udp SIP/2.0
Via: SIP/2.0/UDP 172.31.37.34:7684;rport;branch=z9hG4bKt5m7X2ZDtBSjp
Max-Forwards: 70
From: <sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.org>;tag=pFjr2v1vtUNcK
To: <sip:mcx.test-111.iitb@172.27.224.22:38193>;transport=udp
Call-ID: UCI~C6aPZ-
CSeq: 31304780 NOTIFY
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mcptt";require;explicit
User-Agent: MCLabs MCX Server
Event: presence
Subscription-State: active;expires=4294967295
Content-Type: application/pidf+xml
Content-Length: 264
P-Asserted-Service: urn:urn-7:3gpp-service.ims.icsi.mcptt
P-Asserted-Identity: <sip:mcptt-as-mcla-1.ims.mnc001.mcc001.3gppnetwork.or>
<?xml version="1.0" encoding="UTF-8"?><presence xmlns="urn:ietf:params:xml:ns:pidf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-
stance" xmlns:mcpttPI10="urn:3gpp:ns:mcpttPresInfo:1.0" entity="sip:mcptt.test-111.iitb@ims.mnc001.mcc001.3gppnetwork.org"></pre
nce>
```

**Comment by Viish** [comment]
Please attach new logs from the SDK.

**Comment by Viish** [comment]
Can I close the issue?

**Comment by nick2601** [comment]
Yes please and thanks for the help @Viish
