### ISSUE TITLE
Java Wrapper Build failure

### ISSUE THREAD

**Issue by TreeFrogApps** [BelledonneCommunications/linphone-sdk#11]
Hi Im building for Desktop, with the Java wrapper enabled and building fails (checked out tag 4.3.3): 

cmake options : 

`cmake -DENABLE_ALSA=YES -DENABLE_SOUND=YES -DLINPHONESDK_PLATFORM=Desktop -DENABLE_JAVA_WRAPPER=YES`

error: 

`[  1%] Building CXX object coreapi/CMakeFiles/linphone-coreapi.dir/__/wrappers/java/src/linphone_jni.cc.o
/home/keenm/Documents/Linphone/linphone-sdk/build/WORK/desktop/Build/linphone/wrappers/java/src/linphone_jni.cc:20:10: fatal error: jni.h: No such file or directory
 #include <jni.h>
          ^~~~~~~
compilation terminated.`

I have tried to manually adjust the `linphone/wrappers/java/CMakeLists.txt` adding :

`if (NOT ANDROID)
	find_package(JNI REQUIRED)
	if (JNI_FOUND)
			message (STATUS "JNI_INCLUDE_DIRS=${JNI_INCLUDE_DIRS}")
			message (STATUS "JNI_LIBRARIES=${JNI_LIBRARIES}")
	endif()
endif()`

Which prints out the correct locations for `jni.h`, however makes no difference and build still fails.

**Comment by Viish** [comment]
Hi,
Java wrapper is intended for Android platform only, it won't work with desktop Java as it depends of Android APIs.
