### ISSUE TITLE
No candidate:2 with STUN

### ISSUE THREAD

**Issue by alex-eri** [BelledonneCommunications/linphone-sdk#112]
**Describe the bug**

Stun and ice enabled, but linphone  on android sends one candidate:
```
a=candidate:1 1 UDP 2130706303 176.59.35.200 37528 typ host
a=candidate:1 2 UDP 2130706302 176.59.35.200 37529 typ host
```
On another SIM:
```
a=candidate:1 1 UDP 2130706303 10.62.189.144 9078 typ host
a=candidate:1 2 UDP 2130706302 10.62.189.144 9079 typ host
```
So sometimes call failed.

Linphone on linux sends 2 candidates:
```
a=candidate:1 1 UDP 2130706303 192.168.117.138 9078 typ host
a=candidate:1 2 UDP 2130706302 192.168.117.138 9079 typ host
a=candidate:2 1 UDP 1694498687 128.73.105.106 9078 typ srflx raddr 192.168.117.138 rport 9078
a=candidate:2 2 UDP 1694498686 128.73.105.106 9079 typ srflx raddr 192.168.117.138 rport 9079
```

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**

Server uses direct media and behind nat. Phone on cell lte network (MTS RUS).

**Expected behavior**

Want to see 213.87.133.56 in candidates with 10.62.189.144

**Please complete the following information**
 - Device: Huawei Nova 2
 - OS:  Android 8
 - Version of the App 4.3.1
 - Version of the SDK 4.4.2

**SDK logs**

https://yadi.sk/d/iN8a81hMY9XlOg

**Comment by Viish** [comment]
`2021-02-07 02:25:55:075 [org.linphone/liblinphone] WARNING ICE is used without STUN server`
Here's the answer to why you don't have STUN results.

**Comment by alex-eri** [comment]
@Viish stun server is set in settings and works on another network.
