### ISSUE TITLE
How to stop registration process for wrong ProxyConfig?

### ISSUE THREAD

**Issue by autooz** [BelledonneCommunications/linphone-sdk#117]
Hi!
How to stop new registration process if port or domain is entered incorrectly?
If possible, preferably without core.stop.
Is not coming  "RegistrationState.Failed"  on

>             @Override
>             public void onRegistrationStateChanged(Core lc, ProxyConfig cfg, RegistrationState cstate, String message) {
>                 Log.d(pseudo_tag, "onRegistrationStateChanged message=["+message+"] cstate=["+cstate.toInt()+"] message = ["+message+"] sipRegistrationCallback=["+sipRegistrationCallback+"] RegistrationState.Progress.toString() = ["+RegistrationState.Progress.toString()+"]");
> 
>                 if (sipRegistrationCallback != null && cstate == RegistrationState.None) {
>                     Log.d(pseudo_tag, "RRegistrationState.None");
>                     sipRegistrationCallback.registrationNone();
>                 } else if (cstate == RegistrationState.Progress) {
>                     Log.d(pseudo_tag, "RegistrationState.Progress");
>                     sipRegistrationCallback.registrationProgress();
>                 } else if (cstate == RegistrationState.Ok) {
>                     Log.d(pseudo_tag, "RegistrationState.Ok");
>                     sipRegistrationCallback.registrationOk();
>                 } else if (cstate == RegistrationState.Cleared) {
>                     Log.d(pseudo_tag, "RegistrationState.Cleared");
>                     sipRegistrationCallback.registrationCleared();
>                 } else if (cstate == RegistrationState.Failed) {
>                     Log.d(pseudo_tag, "RegistrationState.Failed");
>                     sipRegistrationCallback.registrationFailed();
>                 }
>             }
 Аt the same time, core does not stop trying to reconnect to the closed port.
> I/ATDA: Linphone core [0xb7f5cd58] notified [registration_state_changed]
> I/ATDA: nict_on_timer_E: sending retransmission
>     channel [0xa80c5008]: message sent to [UDP://172.14.2.100:5], size: [515] bytes
>     REGISTER sip:172.14.2.100:5 SIP/2.0
>     Via: SIP/2.0/UDP 10.0.2.15:37833;branch=z9hG4bK.wEaUFCazc;rport
>     From: <sip:1104@172.14.2.100>;tag=LeWJcRTZ6
>     To: sip:1104@172.14.2.100
>     CSeq: 20 REGISTER
>     Call-ID: CNKYwiVgrr
>     Max-Forwards: 70
>     Supported: replaces, outbound, gruu
>     Accept: application/sdp
>     Accept: text/plain
>     Accept: application/vnd.gsma.rcs-ft-http+xml
>     Contact: <sip:1104@10.0.2.15:37833;transport=udp>;+sip.instance="<urn:uuid:a5ef9ba8-dfc0-0014-bcbc-dfbc1f013fd9>"
>     Expires: 3600
>     User-Agent: ATDA/2.14
> I/ATDA: nict_on_timer_E: sending retransmission
>     channel [0xa80c5008]: message sent to [UDP://172.14.2.100:5], size: [515] bytes
>     REGISTER sip:172.14.2.100:5 SIP/2.0
>     Via: SIP/2.0/UDP 10.0.2.15:37833;branch=z9hG4bK.wEaUFCazc;rport
>     From: <sip:1104@172.14.2.100>;tag=LeWJcRTZ6
>     To: sip:1104@172.14.2.100
>     CSeq: 20 REGISTER
>     Call-ID: CNKYwiVgrr
>     Max-Forwards: 70
>     Supported: replaces, outbound, gruu
>     Accept: application/sdp
>     Accept: text/plain
>     Accept: application/vnd.gsma.rcs-ft-http+xml
>     Contact: <sip:1104@10.0.2.15:37833;transport=udp>;+sip.instance="<urn:uuid:a5ef9ba8-dfc0-0014-bcbc-dfbc1f013fd9>"
>     Expires: 3600
>     User-Agent: ATDA/2.14
> I/ATDA: nict_on_timer_E: sending retransmission
>     channel [0xa80c5008]: message sent to [UDP://172.14.2.100:5], size: [515] bytes
>     REGISTER sip:172.14.2.100:5 SIP/2.0
>     Via: SIP/2.0/UDP 10.0.2.15:37833;branch=z9hG4bK.wEaUFCazc;rport
>     From: <sip:1104@172.14.2.100>;tag=LeWJcRTZ6
>     To: sip:1104@172.14.2.100
>     CSeq: 20 REGISTER
>     Call-ID: CNKYwiVgrr
>     Max-Forwards: 70
>     Supported: replaces, outbound, gruu
>     Accept: application/sdp
>     Accept: text/plain
>     Accept: application/vnd.gsma.rcs-ft-http+xml
>     Contact: <sip:1104@10.0.2.15:37833;transport=udp>;+sip.instance="<urn:uuid:a5ef9ba8-dfc0-0014-bcbc-dfbc1f013fd9>"
>     Expires: 3600
>     User-Agent: ATDA/2.14
> I/ATDA: nict_on_timer_E: sending retransmission
>     channel [0xa80c5008]: message sent to [UDP://172.14.2.100:5], size: [515] bytes
>     REGISTER sip:172.14.2.100:5 SIP/2.0
>     Via: SIP/2.0/UDP 10.0.2.15:37833;branch=z9hG4bK.wEaUFCazc;rport
>     From: <sip:1104@172.14.2.100>;tag=LeWJcRTZ6
>     To: sip:1104@172.14.2.100
>     CSeq: 20 REGISTER
>     Call-ID: CNKYwiVgrr
>     Max-Forwards: 70
>     Supported: replaces, outbound, gruu
>     Accept: application/sdp
>     Accept: text/plain
>     Accept: application/vnd.gsma.rcs-ft-http+xml
>     Contact: <sip:1104@10.0.2.15:37833;transport=udp>;+sip.instance="<urn:uuid:a5ef9ba8-dfc0-0014-bcbc-dfbc1f013fd9>"
>     Expires: 3600
>     User-Agent: ATDA/2.14

But no problem with RegistrationState.Progress AND  RegistrationState.Ok.

**Comment by Viish** [comment]
Hi,
On the ProxyConfig object, use `linphone_proxy_config_enable_register(proxyConfig, FALSE);` method to disable the registration.
Cheers,
