### ISSUE TITLE
Issue scanning QR codes on Android

### ISSUE THREAD

**Issue by winsock** [BelledonneCommunications/linphone-sdk#122]
I do not know if this potentially applies to other platforms but between 4.5.0-beta.110+8c9a009 and 4.5.0-beta.111+39c7bce releases on Maven QR code parsing seems to be broken. I didn't notice anything in particular in recent commits that I would think would this regression but there was a commit yesterday that [updated mediastreamer2](https://gitlab.linphone.org/BC/public/mediastreamer2/-/compare/4957aaddfd668a17f2166532c26d70080e7e71a1...531a1f1f2e886925366db066deaad2d11d19570a) but to my eye nothing in there should cause this. 

# Test Case (123456789)
![image](https://user-images.githubusercontent.com/509341/111528698-76b94c80-872f-11eb-95d5-54a0568ce628.png)

# Results
|4.5.0-beta.110+8c9a009|4.5.0-beta.111+39c7bce|
|-|-|
|![image](https://user-images.githubusercontent.com/509341/111529602-5938b280-8730-11eb-94c7-da0a65059a68.png)|![image](https://user-images.githubusercontent.com/509341/111529802-943ae600-8730-11eb-86c0-115e83f6a451.png)|

**Comment by Viish** [comment]
Hi,
Thanks for the report, I can reproduce it, I will update the issue when fixed.
Cheers,

**Comment by Viish** [comment]
Issue has been fixed in fix/qr_code_corruption, it will be merged into release/4.5 branch soon.
Thanks again.

**Comment by winsock** [comment]
Thank you @Viish! I appreciate the fast fix, I will look out for the new SDK version.

**Comment by Viish** [comment]
It has been merged into release/4.5 branch, new AAR will be built tonight and will be available tomorrow.
