### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;

### ISSUE THREAD

**Issue by hammamziadeh12** [BelledonneCommunications/linphone-sdk#129]
Hey,

When linphone service is getting instantiated, I get error on this line :
mCore = Factory.instance()
                .createCore(basePath + "/.linphonerc", basePath + "/linphonerc", this);

I'm using Firebase and I guess, it seems to be interfering with Firebase?

E: [Android Platform Helper] Could not instanciate CoreManager object.
A: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
A: java_vm_ext.cc:577]   at void org.linphone.core.tools.firebase.FirebasePushHelper.init(android.content.Context) (FirebasePushHelper.java:49)
A: java_vm_ext.cc:577]   at void org.linphone.core.tools.PushNotificationUtils.init(android.content.Context) (PushNotificationUtils.java:52)
A: java_vm_ext.cc:577]   at void org.linphone.core.tools.service.CoreManager.<init>(java.lang.Object, org.linphone.core.Core) (CoreManager.java:99)
A: java_vm_ext.cc:577]   at org.linphone.core.Core org.linphone.core.FactoryImpl.createCore3(long, java.lang.String, java.lang.String, java.lang.Object) (Factory.java:-2)
A: java_vm_ext.cc:577]   at org.linphone.core.Core org.linphone.core.FactoryImpl.createCore(java.lang.String, java.lang.String, java.lang.Object) (Factory.java:759)
A: java_vm_ext.cc:577]   at void com.zgapplications.wayjava.LinphoneService.onCreate() (LinphoneService.java:132)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:4400)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread.access$1800(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:274)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2118)
A: java_vm_ext.cc:577]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:107)
A: java_vm_ext.cc:577]   at void android.os.Looper.loop() (Looper.java:237)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8167)
A: java_vm_ext.cc:577]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
A: java_vm_ext.cc:577]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:496)
A: java_vm_ext.cc:577]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1100)
A: java_vm_ext.cc:577] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/com.zgapplications.wayjava-36LccZPsiUIZZhBkGKUXHA==/base.apk"],nativeLibraryDirectories=[/data/app/com.zgapplications.wayjava-36LccZPsiUIZZhBkGKUXHA==/lib/arm64, /data/app/com.zgapplications.wayjava-36LccZPsiUIZZhBkGKUXHA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
A: java_vm_ext.cc:577]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:196)
A: java_vm_ext.cc:577]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
A: java_vm_ext.cc:577]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
A: java_vm_ext.cc:577]   at void org.linphone.core.tools.firebase.FirebasePushHelper.init(android.content.Context) (FirebasePushHelper.java:49)
A: java_vm_ext.cc:577]   at void org.linphone.core.tools.PushNotificationUtils.init(android.content.Context) (PushNotificationUtils.java:52)
A: java_vm_ext.cc:577]   at void org.linphone.core.tools.service.CoreManager.<init>(java.lang.Object, org.linphone.core.Core) (CoreManager.java:99)
A: java_vm_ext.cc:577]   at org.linphone.core.Core org.linphone.core.FactoryImpl.createCore3(long, java.lang.String, java.lang.String, java.lang.Object) (Factory.java:-2)
A: java_vm_ext.cc:577]   at org.linphone.core.Core org.linphone.core.FactoryImpl.createCore(java.lang.String, java.lang.String, java.lang.Object) (Factory.java:759)
A: java_vm_ext.cc:577]   at void com.zgapplications.threewayjava.LinphoneService.onCreate() (LinphoneService.java:132)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread.handleCreateService(android.app.ActivityThread$CreateServiceData) (ActivityThread.java:4400)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread.access$1800(android.app.ActivityThread, android.app.ActivityThread$CreateServiceData) (ActivityThread.java:274)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:2118)
A: java_vm_ext.cc:577]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:107)
A: java_vm_ext.cc:577]   at void android.os.Looper.loop() (Looper.java:237)
A: java_vm_ext.cc:577]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8167)
A: java_vm_ext.cc:577]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
A: java_vm_ext.cc:577]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:496)
A: java_vm_ext.cc:577]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1100)
A: java_vm_ext.cc:577] 

How do I fix this issue?

**Comment by hammamziadeh12** [comment]
I'm using Linphone 4.5 SDK btw

**Comment by Viish** [comment]
Which version of the 4.5 SDK ?

**Comment by hammamziadeh12** [comment]
I just did this:

debugImplementation "org.linphone:linphone-sdk-android-debug:4.5+"
    releaseImplementation "org.linphone:linphone-sdk-android:4.5+"

BUT:
I just tried 4.4 it works fine:

debugImplementation "org.linphone:linphone-sdk-android-debug:4.4+"
    releaseImplementation "org.linphone:linphone-sdk-android:4.4+"


Which version of 4.5 do i use? I really need to use it since it has the functionality I want

**Comment by Viish** [comment]
OK replace
```
debugImplementation "org.linphone:linphone-sdk-android-debug:4.5+"
releaseImplementation "org.linphone:linphone-sdk-android:4.5+"
```
by
```
debugImplementation "org.linphone:linphone-sdk-android-debug:4.5.0"
releaseImplementation "org.linphone:linphone-sdk-android:4.5.0"
```
and if issue persists attach full logs from SDK.

**Comment by Viish** [comment]
Oh and don't pass `this` in `mCore = Factory.instance().createCore(basePath + "/.linphonerc", basePath + "/linphonerc", this);` if you do it from a Service, we need application Context.

**Comment by hammamziadeh12** [comment]
Just tried 4.5.0,  Same issue. I even changed this, to getApplicationContext() and still same issue.

[logcat_SDK_4.5.0_JNI_ISSUE.pdf](https://github.com/BelledonneCommunications/linphone-sdk/files/6230118/logcat_SDK_4.5.0_JNI_ISSUE.pdf)

**Comment by Viish** [comment]
Do you are in the main thread?

**Comment by hammamziadeh12** [comment]
I copied the sample exactly so I'm not 100% sure.

on onStart() I have this:

if (LinphoneService.isReady()) {
            animate();
        } else {
            // If it's not, let's start it
            startService(
                    new Intent().setClass(this, LinphoneService.class));
            // And wait for it to be ready, so we can safely use it afterwards
            new ServiceWaitThread().start();
        }


And this is the ServiceWaitThread():
private class ServiceWaitThread extends Thread {
        public void run() {
            while (!LinphoneService.isReady()) {
                try {
                    sleep(30);
                } catch (InterruptedException e) {
                    throw new RuntimeException("waiting thread sleep() has been interrupted");
                }
            }
            // As we're in a thread, we can't do UI stuff in it, must post a runnable in UI thread
            mHandler.post(
                    new Runnable() {
                        @Override
                        public void run() {
                            animate();
                        }
                    });
        }
    }

**Comment by hammamziadeh12** [comment]
Any ideas?

**Comment by Viish** [comment]
Forget about sample project in linphone-android repository.
Instead try the following: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/HelloWorld

**Comment by Viish** [comment]
Also should be fixed by latest versions of SDK.
