### ISSUE TITLE
AudioManager not turning on speaker

### ISSUE THREAD

**Issue by hammamziadeh12** [BelledonneCommunications/linphone-sdk#130]
Hey,

I'm using android SDK 4.4 (Can't use 4.5 since I'm having issues with it).

I tried using AudioManager to turn on speaker, but it's not working. How can I fix this? Code for State change is below, everything in this runs normal except that speaker doesn't get turned on unfortunately.

mCoreListener = new CoreListenerStub() {
            @Override
            public void onCallStateChanged(Core core, Call call, Call.State state, String message) {
                if (state == Call.State.Connected) {
                    callStateTextView.setText("connected");
                    loadingDots.setVisibility(View.INVISIBLE);
                    timerTextView.setVisibility(View.VISIBLE);
                    stopwatch.start();

                    mAudioManager = ((AudioManager) getContext().getSystemService(Context.AUDIO_SERVICE));

                    mAudioManager.setSpeakerphoneOn(true);

                } else if(state == Call.State.End || state == Call.State.Released){
                    dismiss();
                }
            }
        };

**Comment by Viish** [comment]
It's very likely this happens because you are using the emulator...
Try on a real device with a speakerphone, should work.

**Comment by hammamziadeh12** [comment]
I have

**Comment by hammamziadeh12** [comment]
I used both a samsung and a google pixel. I don't really use emulators

**Comment by hammamziadeh12** [comment]
I figured it out actually. I had to place permission <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" /> in manifest

**Comment by Viish** [comment]
Ah indeed I didn't think of that...
