### ISSUE TITLE
How to call multiple users at the same time？

### ISSUE THREAD

**Issue by onetrio** [BelledonneCommunications/linphone-sdk#133]
Hi，
I use linphone sdk 4.5+ in my application. 
I want to call multiple users at the same time, but I only expect just one user to answer.
Is there any way to do that?
Thanks!

**Comment by Viish** [comment]
Hi,
To do that you will have to terminate all the other calls once the first one is answered.
Cheers,

**Comment by onetrio** [comment]
> Hi,
> To do that you will have to terminate all the other calls once the first one is answered.
> Cheers,

Thank you for your reply!
I try to call two users at the same time, but only the first call is valid. The second call report a error:
`linphone_core_invite_address_with_params(): sound are locked by another call and they cannot be freed. Call attempt is rejected.`
