### ISSUE TITLE
SSL handshake failed : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-sdk#136]
Hello @Viish ,

I am getting following error intermittently with Kamailio as proxy server over TLS. 
SSL handshake failed : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed

Please check logs.

[TLS_HANDSHAKE_ERROR.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/6270825/TLS_HANDSHAKE_ERROR.txt)

**Comment by Viish** [comment]
Hi,

Seems the certificate was signed by an authority that isn't in the rootca.pem embedded in our SDK.
Simply change the rootca.pem to add your certificate authority in it or use one of the Core method to set it programatically.

Cheers,
