### ISSUE TITLE
In-band Message

### ISSUE THREAD

**Issue by kyle9292** [BelledonneCommunications/linphone-sdk#140]
Is there a way to send a MESSAGE request in-band on the call similar to how the sendInfoMessage method works?

**Comment by Viish** [comment]
An in-band message doesn't exists as it is a SIP MESSAGE, however you can send characters over RTP using a RealTimeText chat room : http://linphone.org/snapshots/docs/liblinphone/5.0/java/org/linphone/core/Call.html#getChatRoom--
