### ISSUE TITLE
not negotiating ICE

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-sdk#142]
Using most recent kotlin_rewrite branch, it seems to my eye that even though the server is trying to negotiate with ICE, linphone-android is not.  Am I wrong?

[Log](http://brian.interlinx.bc.ca/linphone-not-using-ice.txt)

**Comment by brianjmurrell** [comment]
> > WARNING ICE is used without STUN server

> Check you do have a NatPolicy object confgured with a valid STUN server.

I did see that too, but I do have a STUN server configured.

I will update to master and see if this persists.

**Comment by brianjmurrell** [comment]
No change.  Still no ICE.

**Comment by brianjmurrell** [comment]
From linphonerc:

```
[net]
mtu=1300
download_bw=0
upload_bw=0
force_ice_disablement=0
nat_policy_ref=xuRzmxFUZTkoJmM
friendlist_subscription_enabled=0
#Because dynamic bitrate adaption can increase bitrate, we must allow "no limit"
use_legacy_push_notification_params=1
...
[nat_policy_66]
ref=xuRzmxFUZTkoJmM
stun_server=stun.l.google.com:19302
protocols=stun,ice
```

**Comment by Viish** [comment]
```
nat_policy_ref=xuRzmxFUZTkoJmM
...
[nat_policy_66]
```
Ids don't match. Check for the real xuRzmxFUZTkoJmM nat policy. 

Also you should have one in your proxy_config_0 section.

**Comment by brianjmurrell** [comment]
Those are the only occurrences of "xuRzmxFUZTkoJmM" in that file.  I don't have a proxy_config_0 section.  I do have a proxy_0 section that does have `nat_policy_ref=Prvk02ee5HOdpHa` and it looks like:

```
[nat_policy_67]
ref=Prvk02ee5HOdpHa
stun_server=stun.l.google.com:19302
protocols=ice
```

That file is created by linphone-android.  Is this perhaps a case of a file format change that has not had a proper migration done on it?

**Comment by Viish** [comment]
Maybe the issue here is that protocols contains only ice and not stun. I'll check.

**Comment by brianjmurrell** [comment]
Were you able to check?

**Comment by brianjmurrell** [comment]
SDK 5.0.0-alpha seems pretty unstable.

What is the most recent linphone-android master commit that doesn't need any SDK 5.0.0-alpha features and can use a more recent stable SDK (4.5.0 maybe)?

**Comment by brianjmurrell** [comment]
Could you please comment on the above?

**Comment by brianjmurrell** [comment]
For my own future reference, and for the benefit of anyone watching or that comes across this in their travels...

If we assume that any 5.0.0-alpha SDK release is (too) unstable (to use at the moment), and that releases 4.5.x are stable, 4.5.13 is the most recent as of this comment, and BelledonneCommunications/linphone-android@4f6b416b7 is the latest linphone commit that builds with 4.5.13.

Anything newer needs things that are not in 4.5.13.

**Comment by Viish** [comment]
> SDK 5.0.0-alpha seems pretty unstable.

That's an alpha, so yes it might be instable. As soon as it will be in beta it should be usable in a daily-use scenario.

**Comment by Viish** [comment]
> I.e. there was no point in the 5.0.0 landing stream where it was stable before some significant change was landed that made it unstable?

Not really. The real change starting 5.0 is ProxyConfig object being replaced by Account, which is the reason the kotlin version can't use an older SDK because it uses the new object.

> The only issue I find is that frequently just after a call starts (don't have a handle if it's both incoming and outgoing or just one yet) it gets "paused" and I have to unpause it. Is that known?

You're not the first one to complain about that. This happens because for some reason another app (or maybe the system?) asks for the audio focus right after it was granted to Linphone for a call. And when the audio focus is lost, call is paused as per Google guidelines. Check your adb logcat logs to see who is responsible for this audio focus loss. In the meantime you can workaround that by setting the following in your factory config file:
```
[audio]
android_pause_calls_when_audio_focus_lost=0
```

**Comment by brianjmurrell** [comment]
> Check your adb logcat logs to see who is responsible for this audio focus loss

Frustratingly, this typically happens in non-lab scenarios where there is no `adb` running, logging the logcat (i.e. to a file) and so inevitably it's too late to find any message by the time one gets to looking for it.

Thanks for the work-around.  The only unfortunate part is that "editing" that file on a non-rooted device can be a palaver.

**Comment by brianjmurrell** [comment]
I'm still not getting ICE negotiation happening using linphone-android and linphone-sdk 4f6b416b7 and 4.5.13 respectively.

I can see in the log:

```
2021-05-18 07:38:48:147 [org.linphone.debug/liblinphone] WARNING ICE is used without STUN server
```
yet I can see in the UI that I have a STUN server configured.

**Comment by brianjmurrell** [comment]
> Maybe the issue here is that protocols contains only ice and not stun. I'll check.

Per my previous msg, any news here?  What is supposed to add the `stun` to `protocols`?  I.e. is there something in UI that I can do to update that?

**Comment by brianjmurrell** [comment]
> Maybe the issue here is that protocols contains only ice and not stun. I'll check.

This does appear to be the case.  I added it and now linphone-android at least seems to be trying ICE with a candidate (`c=`) address.

The issue still though is why that proxy configuration was created without the required `stun` in `protocols`.

**Comment by KyronNextLevel** [comment]
Hello @brianjmurrell.
A lot of fixes have been done since the 5.0 release, especially for ICE.
Could you try and tell me if you have the same issue ?
You could also check the release/5.1 branch in beta state (which is soon to be released)

This could be a bug on our side.
Are you using a Linphone account with a custom stun server, or are you using an external sip account (non sip.linphone.org) ?

**Comment by brianjmurrell** [comment]
I don't build the SDK here, but rather use prebuilt releases as referenced by linphone-android.

It looks like it is using some kind of 5.1+ currently:

https://github.com/BelledonneCommunications/linphone-android/blob/35a110841c4fb17d503c85a815a17fc32af14145/app/build.gradle#L255

**Comment by KyronNextLevel** [comment]
"Are you using a Linphone account with a custom stun server, or are you using an external sip account (non sip.linphone.org) ?"

**Comment by brianjmurrell** [comment]
Non sip.linphone.org account with stun.linphone.org as the _STUN/TURN server_.

**Comment by KyronNextLevel** [comment]
This is not what the discussion shows... 
It shows stun_server=stun.l.google.com:19302

Did you modify your STUN server from then (and did it work) ?


As far as I remember, the only setting related to STUN in Linphone is the server address.
There is no option to enable STUN explicitly in the app.

Can you please try install a fresh 4.6.1 app (without previous config, or on another phone), log in with your external SIP account, set the STUN address and then send me the generated linphonerc ?

I'm not familiar with this part of the code but I think that a big hint in the missing "stun" in _protocols_ key of the nat policy associated with your proxy_0 section.

Regards

**Comment by brianjmurrell** [comment]
> This is not what the discussion shows... It shows stun_server=stun.l.google.com:19302
> 
> Did you modify your STUN server from then (and did it work) ?

That's quite possible.  This ticket is pretty old and a lot of time has gone by since it was filed.
 
> As far as I remember, the only setting related to STUN in Linphone is the server address. There is no option to enable STUN explicitly in the app.

There is an "Enable ICE" option in the app.
 
> Can you please try install a fresh 4.6.1 app (without previous config, or on another phone), log in with your external SIP account, set the STUN address and then send me the generated linphonerc ?

Maybe at some point, if this issue reproduces.  But looking at the network trace of a test call I just did, it would seem that ICE is working again/now.

We can probably just close this now.
