### ISSUE TITLE
Cannot start the local conference again after ending for the first time

### ISSUE THREAD

**Issue by powerqian** [BelledonneCommunications/linphone-sdk#143]
Hi,

I found an issue with the linphone-sdk that for the local conference, it is okay to start the local conference with multiple calls for the first time. However after ending the local conference, it cannot be started again, and prompting something like
```
liblinphone/Unable to add participant to conference 0x7fb826e37480 because it is in state TerminationPending
```
Seems like after the conference ended and changed the state to Terminated or TerminationPending, it never reset to the correct state, and for the all future attempts to start another local conference, it will fail by checking the state.

**Comment by AndreaGianarda** [comment]
Hi,

Can you please attach a logfile to this issue?

Thanks,

Andrea

**Comment by powerqian** [comment]
Hi Andrea,

Thank you for your response and your time to check the log. Please see the file of all the logs I get when trying to replicate the issue below

https://drive.google.com/file/d/1mm1cm4OJ2C0onSoTgZE-lixfLh9OKIqi/view?usp=sharing

Some background of the log:

Three devices involved to test the local conference.

A: iPhone simulator, whose log is fetched from. User 101010-A
B: iPhone 7. User 101011
C: iPhone Xs Max. User 101012.

Steps and timing:

15:22:25  - A call to C. A and C can hear each other.
15:22:49 - A call to B, putting call with C on hold. A and B can hear each other. C hearing music on hold.
15:23:01 - A pressed conference button, putting call with B and call with C into conference. After the conference created, A cannot hear anything. B and C can hear each other. **Here is the first problem.**
15:23:30 - A pressed hang up button to end conference. Successfully ended.
After that A called to B and C again, and when A try to create the conference again, the conference button is greyed out and cannot be pressed. **Here is the second problem.**
If I modify the code to remove the checking to disable the button, and after pressing it in the above condition, it will print out the log similar to the one in the original post. Note that the conference state is changed to `TerminationPending` at
```
2021-05-03 15:23:30.597364+0800 linphone[53520:2958291] [Message] Switching conference [0x7fe134e20040] from state Created to TerminationPending
```
however there's no log indicates the state is changed back to `Created` so that the conference can be used again for the second attempt. Not sure what to do to use the local conference again.

Thanks again for the help.

Li

**Comment by powerqian** [comment]
More information on this topic

1. The log is saved when running linphone-iphone project with commit c9e189e0ae319c1a2a3501a5aea946046ac937d2, which is actually using a pre build of linphone-sdk 5.0.0-alpha in pod. If I switch to 8a689af705487fba94f6dbd4df3f8c21fd03fc05, which is using linphone-sdk 4.5, and I change the linphone-sdk pod version to 4.5.11, the problem is actually gone.
2. In the meantime in my personal project I use a customized build of linphone-sdk with commit d0c8e6d9217b3e6f94f52044d8e42f595d081ef1 (4.5.11), with only the following feature enabled to provide a minimal build
```
 Enabled features:
  * Mbedtls, Crypto stack implementation based on mbeddtls.
  * DNS_SERVICE, Enable Apple DNS Service. Available on Mac and iOS. Incompatible with ENABLE_MDNS.
  * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
  * Non free codecs, Allow inclusion of non-free codecs in the build.
  * SRTP, SRTP media encryption support.
  * WebRTC AECM, WebRTC echo canceller for mobile support.
  * G729, G.729 audio encoding/decoding support.
  * iLBC, iLBC audio encoding/decoding support.
  * Speex, Speex audio encoding/decoding support.
  * Video, Ability to capture and display video.
  * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
```
Using this build also has this problem, and after terminating the conference, the conference state actually changed from `Created` to `TerminationPending`, then `TerminationPending` to `Termination`, then `Termination` to `TerminationPending` again, which is very weird. Also the callback `onConferenceTerminated` is actually not called. 

Hope these information can help to narrow down the problem.

**Comment by AndreaGianarda** [comment]
Hi, 

I understand that your build sets -DENABLE_ADVANCED_IM=OFF. Can you confirm?

I think the problem is that the conference termination is buggy if -DENABLE_ADVANCED_IM=OFF, hence can you please rerun your test by enabling advanced instastant messaging features and "conference_event_log_enabled" in section misc of your linphone.rc is set to TRUE.

The default value of "conference_event_log_enabled" is TRUE, thus if it is explicitely changed in your rc file, you don't have to take any action on this regard

Thanks,

Andrea

**Comment by powerqian** [comment]
Hi Andrea,

Indeed I set `-DENABLE_ADVANCED_IM=OFF`. Now I tried to enable it and actually I also must set `-DENABLE_DB_STORAGE=ON` to actually activate the ADVANCED_IM in the SDK.

However when I compile the SDK, I encountered the following errors:
```
/path/to/liblinphone/libxsd/xsd/cxx/tree/containers.hxx:864:9: error: definition of implicit copy assignment operator for 'sequence<LinphonePrivate::Xsd::ConferenceInfo::UriType, false>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
        sequence (const sequence& v, flags f = 0, container* c = 0)
        ^
/path/to/liblinphone/src/xml/conference-info.cpp:1215:22: note: in implicit copy assignment operator for 'xsd::cxx::tree::sequence<LinphonePrivate::Xsd::ConferenceInfo::UriType, false>' first required here
        this->entry_ = s;
                     ^
In file included from /path/to/liblinphone/src/xml/conference-info.cpp:46:
In file included from /path/to/liblinphone/src/xml/conference-info.h:71:
In file included from /path/to/liblinphone/libxsd/xsd/cxx/tree/types.hxx:25:
In file included from /path/to/liblinphone/libxsd/xsd/cxx/tree/list.hxx:15:
```
and 7 other locations reporting the same error. 

I searched online and found https://github.com/flutterhash/linphone-libxsd this repo is attempting to fix the compiling error, but using his fork also has other kind of compiling errors, which I already created the issue in that repo.

Unfortunately I'm not a C++ developer so I can't really fix those issues myself. Please try to help. I am using cmake version 3.19.2.

Thanks.
Li

**Comment by AndreaGianarda** [comment]
Hi Li,

Can you please provide the command line you're running to compile the SDK?

Thanks,

Andrea

**Comment by powerqian** [comment]
Hi Andrea,

I'm using `ccmake` with the following configuration

```
ENABLE_ADVANCED_IM               ON
 ENABLE_AMRNB                     OFF
 ENABLE_AMRWB                     OFF
 ENABLE_ASSETS                    OFF
 ENABLE_BV16                      OFF
 ENABLE_CAMERA2                   OFF
 ENABLE_CODEC2                    OFF
 ENABLE_CSHARP_WRAPPER            OFF
 ENABLE_CXX_WRAPPER               OFF
 ENABLE_DB_STORAGE                ON
 ENABLE_DEBUG_LOGS                OFF
 ENABLE_DNS_SERVICE               ON
 ENABLE_DOC                       OFF
 ENABLE_FFMPEG                    OFF
 ENABLE_G726                      OFF
 ENABLE_G729                      ON
 ENABLE_G729B_CNG                 OFF
 ENABLE_GPL_THIRD_PARTIES         OFF
 ENABLE_GSM                       OFF
 ENABLE_GTK_UI                    OFF
 ENABLE_HW_SANITIZER              OFF
 ENABLE_ILBC                      ON
 ENABLE_ISAC                      OFF
 ENABLE_JAVA_WRAPPER              OFF
 ENABLE_JAZZY_DOC                 OFF
 ENABLE_JPEG                      OFF
 ENABLE_LIME                      OFF
 ENABLE_LIME_X3DH                 ON
 ENABLE_MBEDTLS                   ON
 ENABLE_MDNS                      OFF
 ENABLE_MKV                       OFF
 ENABLE_NLS                       OFF
 ENABLE_NON_FREE_CODECS           ON
 ENABLE_OPENH264                  ON
 ENABLE_OPUS                      OFF
 ENABLE_PCAP                      OFF
 ENABLE_POLARSSL                  OFF
 ENABLE_QRCODE                    OFF
 ENABLE_RELATIVE_PREFIX           OFF
 ENABLE_RTP_MAP_ALWAYS_IN_SDP     OFF
 ENABLE_SANITIZER                 OFF
 ENABLE_SILK                      OFF
 ENABLE_SOCI_MYSQL                OFF
 ENABLE_SPEEX                     ON
 ENABLE_SQLITE                    OFF
 ENABLE_SRTP                      ON
 ENABLE_SWIFT_WRAPPER             OFF
 ENABLE_SWIFT_WRAPPER_COMPILATI   OFF
 ENABLE_TOOLS                     OFF
 ENABLE_TUNNEL                    OFF
 ENABLE_UNIT_TESTS                OFF
 ENABLE_UNMAINTAINED              OFF
 ENABLE_UPDATE_CHECK              OFF
 ENABLE_V4L                       OFF
 ENABLE_VCARD                     OFF
 ENABLE_VIDEO                     ON
 ENABLE_VPX                       OFF
 ENABLE_WEBRTC_AEC                OFF
 ENABLE_WEBRTC_AECM               ON
 ENABLE_WEBRTC_VAD                OFF
 ENABLE_XML2                      OFF
 ENABLE_ZLIB                      OFF
 ENABLE_ZRTP                      OFF
```

then compile with `cmake --build . --parallel 4`. Also tried `cmake --build .`. Both giving me the above error.

I guess some other features must be enabled?

Thanks.

Li

**Comment by powerqian** [comment]
Hi,

I tried to compile using the default settings without modification, but still failed. Seems like as long as `ENABLE_ADVANCED_IM` is ON, which will bring in `libxsd` in `liblinphone`, the compiling will fail.

If it can be built in your system, then should be the system tools version incompatibility. Here's my setup

- macOS Big Sur 11.3
- Xcode 12.5 (12E262)
- gcc information as follows
```
✗ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by KyronNextLevel** [comment]
Hello @powerqian.
We are currently doing a big work with videoconference feature, so huge parts of the code are being reworked.
This can lead to issues, especially in alpha builds.
Can you tell me if you see the same bug in release/5.0 (stable) and release/5.1 (to be released) ?

**Comment by powerqian** [comment]
> Hello @powerqian.
> We are currently doing a big work with videoconference feature, so huge parts of the code are being reworked.
> This can lead to issues, especially in alpha builds.
> Can you tell me if you see the same bug in release/5.0 (stable) and release/5.1 (to be released) ?

Hi @KyronNextLevel 

I just tried both 5.0 and 5.1 version of the linphone sdk in the Android project and seems the issue still exist even using the official linphone library. My sample app using the official linphone Android library with version `5.0.69`, and using the official Linphone Android app which specify the library to `5.1+`.

During testing, I made two calls, then creating the local conference for these two calls, then end call. After call is ended, the local conference is not ended. If I make a new call after that, I will see the conference row in the call page in Linphone Android app which uses `5.1+` linphone library. In my sample app that uses `5.0.69`, same situation, and I cannot form another local conference after that with error message saying the conference is still in TerminationPending state.

**Comment by KyronNextLevel** [comment]
Ok, thanks for the details. I'm pinning the issue

What is your provider server-side (I'm asking this to eventually reproduce the issue on our side) ?

**Comment by powerqian** [comment]
Server side is Asterisk (https://www.asterisk.org). May I ask why the server side is relevant in this case where the conference is started and ended locally by Linphone library?

Thanks.

**Comment by powerqian** [comment]
Hi @AndreaGianarda 

Thanks for the fix. I just tried and seems working properly now. However, I didn't even add `conference_event_log_enabled=0` in the `linphonerc`... 

Anyway, looking forward to the fix being included in the release branch.
