### ISSUE TITLE
Is bluetooth supposed to be functional on master?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-sdk#145]
When my phone is connected to a bluetooth device, such as my car's audio system, I don't seem to have any option to use the bluetooth speakers or mic with linphone-android.

I am positive I have been able to before though.  Is this something that got lost in the kotlin rewrite?

**Comment by Viish** [comment]
> Is bluetooth supposed to be functional on master?

Yes.

**Comment by brianjmurrell** [comment]
And so when Linphone shows no bluetooth options in the speaker button, how do we understand why?  Will something in the debug log help?  What should I be looking for?

**Comment by Viish** [comment]
Attach logs as asked in the bug report template and I'll check.

**Comment by brianjmurrell** [comment]
Hrm.  It does work with my HSP/HFP headset.  Wasn't working in the car.  I will try that again and get a log if still not working.

**Comment by brianjmurrell** [comment]
Did seem to work in the car also.  Which is very strange.  I tested it a few times when I found it not working in the car.

Audio dropout on SDK 5.0.0-alpha.60+946a9fd is horrible, but that's a different ticket.
