### ISSUE TITLE
how to send the OPTION command in Linphone sdk

### ISSUE THREAD

**Issue by nealkai** [BelledonneCommunications/linphone-sdk#149]
How to know the online status of the other party in a short period of time or before the call? I know that there is an option command to send, but linphone SDK does not see the interface. Ask for help. Thank you very much. I wish you a happy life.

**Comment by Viish** [comment]
Hi,
We have no API currently to send custom OPTION message.
However what you are looking for is "short term presence" and our SDK does support it through the LinphoneFriend object.
It isn't done in mobile apps as it's battery consuming but we do use it in our https://github.com/BelledonneCommunications/linphone-desktop app.
Cheers,
