### ISSUE TITLE
Can android sdk monitor the state of 183/180 during outgoing progress?

### ISSUE THREAD

**Issue by OumaSyuu** [BelledonneCommunications/linphone-sdk#15]
Hi, I want to do some filtering during outgoing call early media. Is there any android api that can identify the state of current call(183 session progress or 180 ringing)?

**Comment by Viish** [comment]
Hi,
The call state does that. If it is OutgoingEarlyMedia it means 183 has been received, if it is OutgoingRinging it means the 180 has been received.
Cheers,
