### ISSUE TITLE
SDK build inside desktop fails to build on M1 mac (cmake errors)

### ISSUE THREAD

**Issue by alexgurr** [BelledonneCommunications/linphone-sdk#154]
## Describe the bug
When trying to build the desktop app locally and following the build instructions, the build fails (see below under logs).

Command that fails -- cmake --build . --target install --parallel 10 --config RelWithDebInfo with the following errors:

```bash
make[11]: *** [simd/CMakeFiles/simd.dir/arm64/jsimd_neon.S.o] Error 1
make[10]: *** [simd/CMakeFiles/simd.dir/all] Error 2
make[9]: *** [all] Error 2
make[8]: *** [/Users/alexgurr/Documents/cloudwave/apps/linphone-desktop/build/WORK/WORK/desktop/Stamp/EP_turbojpeg/EP_turbojpeg-build] Error 2
make[7]: *** [CMakeFiles/EP_turbojpeg.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [sdk-prefix/src/sdk-stamp/sdk-build] Error 2
make[4]: *** [CMakeFiles/sdk.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [WORK/stamp/sdk-build] Error 2
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
make: *** [all] Error 2
```

## To Reproduce
The build steps in the README file on an M1 mac.

## Expected behavior
It builds correctly.

## Desktop (please complete the following information):
OS: macOS
Version: 11.2.3
SDK + desktop versions: latest

## SDK logs
[paste.ee/p/hF1vq](paste.ee/p/hF1vq)

**Comment by KyronNextLevel** [comment]
Hello @alexgurr 
This seems normal to me, as M1 Mac support was only introduced since release/5.1, which is still in the stabilization state (beta) but will be tagged soon.

Please use this branch and to not hesitate to open a new ticket (with complete logs, platform, versions) if you see build issues there.
