### ISSUE TITLE
App Crashed while update audio codec

### ISSUE THREAD

**Issue by RaviChavada** [BelledonneCommunications/linphone-sdk#157]
Hello, my application is rapidly crashed while updating audio coded

**A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16610 (FinalizerDaemon), pid 16596**
**SDK VERSION=4.5.20-pre.1+a029e3e**

**Comment by Viish** [comment]
Please attach SDK logs and symbolized stack trace

**Comment by RaviChavada** [comment]
Attached crash log file

[linphone crash log.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/6643302/linphone.crash.log.txt)

**Comment by Viish** [comment]
Bug found, will be fixed shortly, thanks.

**Comment by Viish** [comment]
Fix has been made in linphone-sdk master branch, I'll backport it to release/4.5 branch tomorrow.
