### ISSUE TITLE
liblinphone should add an Accept: application/pidf+xml header to SUBSCRIBE messages

### ISSUE THREAD

**Issue by JohnHughesAtlantech** [BelledonneCommunications/linphone-sdk#16]
I'm working with an Asterisk PABX and it rejects belle-sip's SUBSCRIBE messages because bell-sip does not include an Accept header specifying that it wants application/pidf+xml.

If the Accept header is added to the SUBSCRIBE request Asterisk will send valid NOTIFY responses.

This issue is present in the current linphone beta.

**Comment by JohnHughesAtlantech** [comment]
No, the bug is not in current linphone beta (since it no longer sends subscribes).  I was getting confused looking at the code for the old debian version of linphone

**Comment by JohnHughesAtlantech** [comment]
Part of the log:
`SUBSCRIBE sip:jacques@xxx.xxx.com SIP/2.0^M
Via: SIP/2.0/UDP 10.27.128.3:5060;branch=z9hG4bK.EeUMby4CA;rport^M
From: <sip:john@xxx.xxx.com>;tag=L4vrepOkv^M
To: sip:jacques@xxx.xxx.com^M
CSeq: 20 SUBSCRIBE^M
Call-ID: QlGkcAazee^M
Max-Forwards: 70^M
Supported: replaces, outbound, gruu^M
Event: presence^M
Expires: 600^M
Contact: <sip:john@10.27.128.3;transport=udp>;expires=3600;+sip.instance="<urn:uuid:abcdf51a-82e0-49b9-a8ab-2461011f25ec>"^M
User-Agent: Linphone Desktop/4.2.0-alpha-14-g0d3c37bd (Debian GNU/Linux bullseye/sid, Qt 5.12.5) LinphoneCore/4.4.0-alpha-131-g0883fe652^M
^M
SIP/2.0 489 Bad Event^M
Via: SIP/2.0/UDP 10.27.128.3:5060;branch=z9hG4bK.SKZYFYYt9;received=10.27.128.3;rport=5060^M
From: <sip:john@xxx.xxx.com>;tag=L4vrepOkv^M
To: sip:jacques@xxx.xxx.com;tag=as23f301f1^M
Call-ID: QlGkcAazee^M
CSeq: 21 SUBSCRIBE^M
Server: Asterisk PBX 13.14.1~dfsg-2+deb9u4^M
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE^M
Supported: replaces, timer^M
Content-Length: 0^M
^M

`

**Comment by HamburgerJungeJr** [comment]
I seem to be running into the same problem with our PBX.
Im running linphone Desktop 4.3.0-alpha-96-gfc5bc239 - Qt5.12.5 Core 5.0.0-alpha-72-g4ceaef65d

**Comment by KyronNextLevel** [comment]
Hello. This seems fixed in latest versions. Do not hesitate to re-open if you see the issue again.
Regards
