### ISSUE TITLE
linphone-sdk - android compile error - branch release 5.0

### ISSUE THREAD

**Issue by bunel** [BelledonneCommunications/linphone-sdk#161]
I tried to compile locally on Ubuntu linphone-sdk -> branch: release 5.0
The code comes configured with gradle wrapper 6.1.1 but It does not compile.
I changed /cmake/Android/gradle/wrapper/gradle-wrapper.properties -> and I configured it to use more recent gradle distributions
The sdk will compile subprojects properly only with graddle versions 7.0 and 7.1.
But there is still an error creating the android sdk AAR archive .

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Failed to query the value of task ':compileReleaseJavaWithJavac' property 'options.generatedSourceOutputDirectory'.
   > Querying the mapped value of map(java.io.File property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /home/bunel/aloniabelledone/alonia-linphone-android.git/build/linphone-sdk/bin/generated/ap_generated_sources/release/out)) org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@2ee97c57) before task ':compileReleaseJavaWithJavac' has completed is not supported
...
...
BUILD FAILED in 13s
CMake Error at /home/bunel/aloniabelledone/alonia-linphone-android.git/cmake/Android/GenerateSDK.cmake:49 (message):
  Gradle assemble failed

make[2]: *** [CMakeFiles/sdk.dir/build.make:71: CMakeFiles/sdk] Error 1
make[1]: *** [CMakeFiles/Makefile2:89: CMakeFiles/sdk.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

************************************
[build.log](https://github.com/BelledonneCommunications/linphone-sdk/files/6748002/build.log)
I atached here the log showing my attempts to build the sdk with different gradle versions.

Can I get some help to compile this version ?

**Comment by Viish** [comment]
Hi,
First of all, gradle is almost not use during SDK build, it is only used for AAR packaging.
Can you revert all your changes, clean your build directory and only attach build logs with current 5.0 version please?
Thanks.

**Comment by Viish** [comment]
Please keep using gradle 6.1.1 packed with SDK, we haven't tried building it with gradle 7 so I can't guarantee the build result.

**Comment by bunel** [comment]
Thank you !  I followed up your recommendation and used gradle 6.1.1 but unfortunately I get an error during cleaning phase -> before compiling... packaging.
Here is the error:
-----------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 691ms
CMake Error at /home/bunel/aloniabelledone/alonia-linphone-sdk-android.git/cmake/Android/GradleClean.cmake:34 (message):
  Gradle clean failed

make[2]: *** [CMakeFiles/gradle-clean.dir/build.make:70: CMakeFiles/gradle-clean] Error 1
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/gradle-clean.dir/all] Error 2
make: *** [Makefile:91: all] Error
-----------------------------------

I used the branch release 5.0 - cloned from git hub.

I atach here the log file.

I get the same error with gradle 6.5, 6.8, and 6.9 .

I will need probably to do some tweaking in my build environment and / or in the CMake files to be able to build it.

**Comment by Viish** [comment]
According to what I read on [internet](https://lmgtfy.app/?q=Could+not+initialize+class+org.codehaus.groovy.runtime.InvokerHelper), try with gradle 6.3.
Also check your Java SDK version (I use 11 it works fine, others say to use 14).
Finally you can try to add the following to the cmake/Android/build.gradle.cmake file, below sourceSets {} : 
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
