### ISSUE TITLE
Unable to establish first video call, but third (and sometimes second) are ok

### ISSUE THREAD

**Issue by stonefoxes** [BelledonneCommunications/linphone-sdk#162]
Action order:

Inside core init
  - `core.enableKeepAlive(true)`
  - `core.enableVideoCapture(true)`
and `core.start()` after

Incoming call from softphone inside local network

Accepting call inside CoreListenerStub
```Kotlin
override fun onCallStateChanged(core: Core, call: Call, cstate: Call.State?, msg: String) {
    when (cstate) {
        Call.State.IncomingReceived -> {

            val params = core.createCallParams(call)
            params?.enableVideo(true)
            call.enableCamera(true)

            params?.enableVideo(true)
            Log.d(logTag, "${params?.usedVideoPayloadType} PAYLOAD TYPE")
            // params?.enableAvpf(true)
            call.accept()
            
            // call.acceptWithParams(params)
            // val remoteAddress = call.remoteAddressAsString

            for (camera in core.videoDevicesList) {
                if (camera.contains("Back")) {
                    core.videoDevice = camera
                    Log.i(logTag, "CAMERA!!! $camera")
                }
            }
            try {
                val ad = core.audioDevices.filter {
                    it.type == AudioDevice.Type.Speaker
                } [0]
                core.currentCall?.outputAudioDevice = ad
                call.update(params)
            } catch (e: Exception) {
                Log.e(logTag, "$e")
            }

        }
        Call.State.StreamsRunning -> {
            // call.videoStats
        }
    }
    Log.d(logTag, "onCallStateChanged => $call $cstate $msg")
}
```

Actual behavior:
Green screen instead of video preview in my softphone (MicroSIP) for the first call
Repeat call until video starts working
Green screen for 1-2 seconds and video starts streaming for the second or third call (can't find consistent pattern for that)

Expected behavior:
Green screen for 1-2 seconds and video starts streaming for the first call

Logs with two calls unsuccessful and successful: https://gist.github.com/stonefoxes/4ee5affc8c41bda8c7778bd11a84431f

How can I solve this problem? Thanks in advance.

**Comment by Viish** [comment]
Hi,
First of all, do you reproduce the issue with our own android app? 
If yes, please provide logs from our app.
Cheers,

**Comment by stonefoxes** [comment]
@Viish No, both sample app and official linphone client for android works fine.

**Comment by Viish** [comment]
I recommend you check our tutorials to understand how to properly use our SDK since you confirm issue is in your app code: https://gitlab.linphone.org/BC/public/tutorials
