### ISSUE TITLE
Download the Docker image of the Android build environment

### ISSUE THREAD

**Issue by Roger1103** [BelledonneCommunications/linphone-sdk#167]
Hi,
`docker login gitlab.linphone.org:4567` 
I don't have an account. Where can I get an account?
Thanks!

**Comment by nadeesh19** [comment]
did u find a solution for this ?
I also need to know. please let me know if you find a way to do this.
Thank you!

**Comment by KyronNextLevel** [comment]
Hello. I have fixed this by enabling a read only access token. It is available in release/5.1 and master Readme.

Regards
