### ISSUE TITLE
Cannot build release/4.3

### ISSUE THREAD

**Issue by anilTaylan** [BelledonneCommunications/linphone-sdk#168]
Hi,
For a project of mine, I would like to use one of your earlier releases (release/4.3). However when I try to build the sdk, I'm getting some errors and I have not able to find any solution to these yet. I should note that this is not the case with release/4.5 or above, I can build them. Because, I was not able to find any solutions to my problem and the problem is specific to release/4.3, I would like to ask for your help. I'm using following commands in order;

git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
cd linphone-sdk
git branch
git switch release/4.3
git branch 
mkdir build && cd build
cmake .. -G Xcode -DLINPHONESDK_PLATFORM=IOS  -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=YES -DENABLE_SILK=OFF -DENABLE_ISAC=YES -DENABLE_MKV=OFF -DENABLE_GSM=YES -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF -DENABLE_VIDEO=YES
cmake --build . --config RelWithDebInfo

This sequence of commands works for release/4.5 and above but results with following errors for release/4.3. I am attaching a detailed log, for your consideration. I would really appreciate your help.

[output.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/6884756/output.txt)

clang: error: invalid iOS deployment version '-target armv7-apple-ios11.1', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

   The following build commands failed:
    	CompileC /Users/aniltaylanoner/Desktop/linphone-build/linphone18/linphone-sdk/build/ios-armv7/Autotools/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug-iphoneos/cmTC_46250.build/Objects-normal/armv7/testCCompiler.o /Users/aniltaylanoner/Desktop/linphone-build/linphone18/linphone-sdk/build/ios-armv7/Autotools/CMakeFiles/CMakeTmp/testCCompiler.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)

  Policy CMP0114 is not set to NEW.  In order to support the Xcode "new build
  system", this project must be updated to set policy CMP0114 to NEW.

The following build commands failed:
	PhaseScriptExecution Generate\ ios-armv7-prefix/src/ios-armv7-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-armv7-configure /Users/aniltaylanoner/Desktop/linphone-build/linphone18/linphone-sdk/build/linphone-sdk.build/RelWithDebInfo/ios-armv7.build/Script-974A22D5D7455B5E98FBF01B.sh
(1 failure)

**Comment by THaliloglu** [comment]
These can occur when you update Xcode to latest version. Try with lowering Xcode's command line tools version.  (e.g. 10.3 or 11.7)

**Comment by KyronNextLevel** [comment]
This error is the key :

"clang: error: invalid iOS deployment version '-target armv7-apple-ios11.1', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]"

Sorry but we won't fix this issue, as we support only the latest release.

Feel free to comment here, but I'm closing this issue
