### ISSUE TITLE
In Video call Recording only Remote side video is recorded

### ISSUE THREAD

**Issue by ronguleria** [BelledonneCommunications/linphone-sdk#171]
In Video call Recording only Remote side video is recorded. I want to record both user video

**Comment by ronguleria** [comment]
> This is not possible yet.

There is any way to record both users video call, with help of other Libs.

**Comment by Viish** [comment]
You can try with a screen recorder library maybe?
Otherwise if you want us to do it you can contact our sales department using the following [form ](https://linphone.org/contact#content-bottom3) and they will send you a quotation.
