### ISSUE TITLE
Video call not working

### ISSUE THREAD

**Issue by ronguleria** [BelledonneCommunications/linphone-sdk#173]
video not show in TextureView, 

Code
 core.enableVideoCapture(true)
        core.enableVideoDisplay(true)
        core.videoActivationPolicy.automaticallyAccept = true
        
        val params = core.createCallParams(null)
        params ?: return
        params.mediaEncryption = MediaEncryption.None
        params?.enableVideo(isVideoCall)
        
        currentCall?.core?.nativeVideoWindowId = findViewById(R.id.remote_video_texture)
        currentCall?.core?.nativePreviewWindowId =  findViewById(R.id.local_preview_texture)

**Comment by Viish** [comment]
Please attach logs

**Comment by ronguleria** [comment]
I Have Checked Code, and find this issue was generate by other lib.
