### ISSUE TITLE
ENABLE_GPL_THIRD_PARTIES - default value is NO 

### ISSUE THREAD

**Issue by licaon-kter** [BelledonneCommunications/linphone-sdk#175]
...although Readme says "it's YES by default": https://github.com/BelledonneCommunications/linphone-sdk/blob/5.0.14/README.md#licensing-gpl-third-parties-versus-non-gpl-third-parties

The check is here: https://github.com/BelledonneCommunications/linphone-sdk/blob/5.0.15/CMakeLists.txt#L92
But I can't find where this is _defined by default as YES_.

F-Droid's recipe does not define it as NO... but it builds as NO: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.linphone.yml#L747-L748

Also issues around here show users building "without defining" and ends up as NO by default: https://github.com/BelledonneCommunications/linphone-sdk/issues/94#issuecomment-739734799

**Comment by Viish** [comment]
Indeed the Readme file is wrong, default is disabled

**Comment by KyronNextLevel** [comment]
I created a MR in our Gitlab in order to fix the Readme issue : explain that default value for ENABLE_GPL_THIRD_PARTIES  is and remain disabled, thus I will be closing @licaon-kter pull request.

**Comment by KyronNextLevel** [comment]
This was fixed and merged in 5.1, 5.0, and master branches.
Thanks for reporting it.
