### ISSUE TITLE
Audio issue during VOIP calls

### ISSUE THREAD

**Issue by Nicolo-sudo** [BelledonneCommunications/linphone-sdk#178]
Hello,

I’m experiencing a strange audio issue which often occurs, but not always. When a new VOIP call starts, the audio is clear and the issue does not arise, but sometimes the audio becomes distorted making the call inaudible. The only solution for now is to close the call and make another one. 

I have noticed that after more or less one minute and half of conversation between the two device (with a custom Android system and the same app installed), the issue sometimes appears.

For better understanding, I have attached an example of that disturb that can be heard in call.
For all my test I'm using two different devices with the same configuration, including Echo cancelling, Adaptive Rate Control. I also tried to enable/disable audio codecs (like disabling opus and enabling GSM), I tried to make the calls without the video but the issue is still there. I also tried to keep only on one side the Echo Cancelling turned on, but no luck.

I suppose this issue is more related to the SDK than the App, because on mobile phones the sound is always perfect.
I have tried different versions of the Linphone SDK, and I noticed that with the Linphone Core 3.12 (Linphone Android 3.3.2) this audio issue doesn't appear. Unfortunately I'm not able to compile that version of the SDK, is still possibile to compile? By searching in the releases of this repo I cannot see the oldest 3.12, can you point me where can I download it?

This issue appears from the Linphone SDK 4.1 so far.

Thank you in advance

https://user-images.githubusercontent.com/56111426/132349948-9089993a-a00d-4869-8ebf-16e8bc0911c7.mp4

.

**Comment by Viish** [comment]
Hi,

Thanks for the report.
Have you tried with linphone-android current release (4.5.2, SDK 5.0.x)? If you have the issue, can you attach logs from the app?
The oldest SDK release I can find is [3.3.2](http://linphone.org/releases/old/maven_repository/org/linphone/liblinphone-sdk/3.3.2/)

Cheers,

**Comment by Nicolo-sudo** [comment]
Hi Viish,

Fist of all, thank you for your quick response.

I'have made some tests on the linphone-android app release ( (4.5.2, SDK 5.0.19) and I confirm that the audio issue is still present on that version of the SDK.

Below you can find the logs from the app:
[Uploading 613864c589064_9e7eadfdd99bbe458ce2.gz…]()

I will perform some test on the older version of the Linphone SDK you linked me, thanks.

**Comment by Viish** [comment]
Hi,

Thanks for the logs but I can't get the logs, the link isn't valid. Can you check?

Thanks.

**Comment by Nicolo-sudo** [comment]
Hi,

Sorry for the inconvenience, I copied the logs in a txt file.

[linphone_logs.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/7127236/linphone_logs.txt)

**Comment by Viish** [comment]
Thanks.

A lot of things in your logs that could cause your issue:
- Your device is not from a "main" company, so they may be doing things differently that the one we are used to ;
- Your device runs a very old version of Android (the oldest one we support) ;
- You are doing calls with PCMU/PCMA audio codec that is quite bad, and because it(s 8kHz we have to add a resampler ;
- You are on speakerphone ;
- You are doing bad video at the same time ;

So here's what you can try:
- Disable video and keep audio on earpiece ;
- Use Opus audio codec ;
- Try on a different smarphone ;

Hope it helps.
