### ISSUE TITLE
Android. Outgoing call in Progress state. App not sending BYE message after currentCall.terminate()

### ISSUE THREAD

**Issue by AzamatT89** [BelledonneCommunications/linphone-sdk#180]
I making a demo app to find out if we can use Linphone sdk to provide sip feature in our app.
Following the tutorial projects I made a sip account registration and incoming calls. 
Now, I have a problem with the outgoing calls. 

1. Make an outgoing call.
2. Do not wait the call is visible for receiving side and terminate it.

expected result - BYE message sent to server and call canceled
actual result - no message sent, call reached the destination

Where can there be a problem?

Linphone-sdk version: org.linphone.minimal:linphone-sdk-android-debug:5.0.21

[Logs. 23.09.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/7226103/Logs.23.09.txt)

**Comment by AzamatT89** [comment]
Sorry, I found out that problem not in RTP connection. Maybe it's in our server. So The issue not correct now.

**Comment by AzamatT89** [comment]
After INVITE message from the app if I call currentCall.terminate() method it will not send the BYE message to server. So the call will get destination even after aI terminate it

**Comment by Viish** [comment]
Please attach proper logs (in a file, with line breaks).

**Comment by AzamatT89** [comment]
> Please attach proper logs (in a file, with line breaks).
[Logs. 23.09.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/7226092/Logs.23.09.txt)

**Comment by AzamatT89** [comment]
I find out the problem. It was error in custom header From. And that error displayed in log.
I close the issue.
