### ISSUE TITLE
Pod install error when using the sample app

### ISSUE THREAD

**Issue by mathist** [BelledonneCommunications/linphone-sdk#182]
I'm not sure if this right place to post this issue, but...   when I use this sample:  https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/iOS/ - I get an error when I run `pod install`

[!] Couldn't determine repo type for URL: `https://gitlab.linphone.org/BC/public/podspec.git`: (<unknown>): mapping values are not allowed in this context at line 3 column 17

Here's my podfile:

```
platform :ios, '13.0'

source "https://gitlab.linphone.org/BC/public/podspec.git"

target 'LinphoneTest' do
  use_frameworks!

  pod 'linphone-sdk' , '4.5'
end
```

**Comment by benadzs** [comment]
Yep! I have the same. I tried everything...

- Install from local SDK (files)
- Clone the repo to my own repo and delete the linphone-sdk-novideo folder
- Remove the source line and add a git and a tag parameter to the `pod 'linphone-sdk'` line...

I wuld be very grateful if this issue can be fixed. Now I can't release new iOS applications via Azure Pipelines. I need to do it in manual way.

**Comment by benadzs** [comment]
Check this! https://stackoverflow.com/questions/69197167/pod-install-fails-on-linphone-sdk-in-azure-devops-pipeline

**Comment by KyronNextLevel** [comment]
If someones runs through this issue, please check this one :
[https://github.com/BelledonneCommunications/linphone-sdk/issues/207](url)
