### ISSUE TITLE
P-Asserted Identity iOS SDK

### ISSUE THREAD

**Issue by Patresko** [BelledonneCommunications/linphone-sdk#185]
How can I retrieve this information which im able to see in the log?

`P-Asserted-Identity: "DECT ..." <sip:XXXX@XX.XX.XX.XX;user=phone>`

I want to parse and show displayName for outgoing call instead of number.

**Comment by Patresko** [comment]
Can you reopen this? It was not solved with your answer.

I loading config

` try? mCore = factory.createCore(configPath: "\(configDir)MyConfig", factoryConfigPath: fileURL?.path, systemContext: nil)`

I get in log information about reading

`2021-10-20 15:09:11:475 liblinphone-message-Reading config information from /private/var/containers/Bundle/Application/24A70D8D-EED4-4A3D-AF77-9682F2228458/SIP Phone.app/linphonerc`

This is in linphonerc

```
[sip]
call_logs_use_asserted_id_instead_of_from=1
```
But call.remoteAddress still returning From and not P-Asserted-Identity

**Comment by Viish** [comment]
Also note that `call_logs_use_asserted_id_instead_of_from` property is only for incoming calls, not outgoing!
