### ISSUE TITLE
P-Asserted-Identity iOS SDK [SWIFT]

### ISSUE THREAD

**Issue by Patresko** [BelledonneCommunications/linphone-sdk#186]
How can I retrieve this information in SWIFT which im able to see in the log?

P-Asserted-Identity: "DECT ..." <sip:XXXX@XX.XX.XX.XX;user=phone>

I want to parse and show displayName for outgoing call instead of number.

**Comment by Viish** [comment]
Duplicate of https://github.com/BelledonneCommunications/linphone-sdk/issues/185
