### ISSUE TITLE
Getting error messages in syslog 

### ISSUE THREAD

**Issue by balaji07s** [BelledonneCommunications/linphone-sdk#188]
Hi,

I have recently installed  kamailio 5.5.2 on my  linux machine and after i make calls from softphones it is showing errors in the log , Kindly anyone help me with this.

Oct 30 18:11:41 balaji-Virtualbox kamailio[2781]: 27(2781) ERROR: {2 2 INVITE PS1XPCblBqE35MWzOu8awA..} db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Unknown column 'src_user' in 'field list' (1054)
Oct 30 18:11:41 balaji-Virtualbox kamailio[2781]: 27(2781) ERROR: {2 2 INVITE PS1XPCblBqE35MWzOu8awA..} <core> [db_query.c:244]: db_do_insert_cmd(): error while submitting query
Oct 30 18:11:41 balaji-Virtualbox kamailio[2781]: 27(2781) ERROR: {2 2 INVITE PS1XPCblBqE35MWzOu8awA..} acc [acc.c:490]: acc_db_request(): failed to insert into database
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) NOTICE: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} acc [acc.c:287]: acc_log_request(): ACC: transaction answered: timestamp=1635597727;method=BYE;from_tag=eb9fe459;to_tag=xy0ppd4;call_id=PS1XPCblBqE35MWzOu8awA..;code=200;reason=Ok;src_user=123;src_domain=192.168.1.8;src_ip=192.168.1.3;dst_ouser=456;dst_user=456;dst_domain=192.168.1.4
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) ERROR: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Unknown column 'src_user' in 'field list' (1054)
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) ERROR: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} <core> [db_query.c:244]: db_do_insert_cmd(): error while submitting query
Oct 30 18:12:07 balaji-Virtualbox kamailio[2783]: 29(2783) ERROR: {2 3 BYE PS1XPCblBqE35MWzOu8awA..} acc [acc.c:490]: acc_db_request(): failed to insert into database

**Comment by Viish** [comment]
Hi,

As these are logs from kamalio you should check with them as it probably is a database config issue.
Note we have zero experience with that proxy server, we only answer issues about our products.

Cheers,
