### ISSUE TITLE
Enable/Disable loudspeaker during call

### ISSUE THREAD

**Issue by daliborristic883** [BelledonneCommunications/linphone-sdk#193]
Is there any method to enable/disable loudspeaker during call on LinphoneSDK?

My application developed by Xamarin.
I hope to enable/disable loudspeaker during call.

Below codes are what I tried. but it isn't working.

`public void EnableSpeaker()
        {
			try
			{
				NSError error = AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.PlayAndRecord, AVAudioSessionCategoryOptions.DefaultToSpeaker);

				if (error == null)
				{
					if (AVAudioSession.SharedInstance().SetMode(AVAudioSession.ModeVoiceChat, out error))
					{
						if (AVAudioSession.SharedInstance().OverrideOutputAudioPort(AVAudioSessionPortOverride.Speaker, out error))
						{
							error = AVAudioSession.SharedInstance().SetActive(true);
							if (error != null)
								LoggerService.Log("Error", error.Description);
						}
					}
				}
			}
			catch (Exception ex)
			{
				LoggerService.Log("Error", $"Inside SetAudio:: Error:: {ex.Message} {ex.StackTrace}");
			}
		}

		public void DisableSpeaker()
        {
			try
			{
				NSError error = AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.PlayAndRecord, AVAudioSessionCategoryOptions.DefaultToSpeaker);
				if (error == null)
				{
					if (AVAudioSession.SharedInstance().SetMode(AVAudioSession.ModeVoiceChat, out error))
					{
						if (AVAudioSession.SharedInstance().OverrideOutputAudioPort(AVAudioSessionPortOverride.None, out error))
						{
							error = AVAudioSession.SharedInstance().SetActive(true);
							if (error != null)
								LoggerService.Log("Error", error.Description);
						}
					}
				}
			}
			catch (Exception ex)
			{
				LoggerService.Log("Error", $"Inside SetAudio:: Error:: {ex.Message} {ex.StackTrace}");
			}
		}`

Please help me.
Thanks.
Dalibor

**Comment by Viish** [comment]
Hi Dalibor,

Check this [wiki page](https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Liblinphone%205.0%20new%20features%20and%20how%20to%20use%20them/#HAudioroutes) and this [tutorial](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/ios/swift/2-IncomingCall) to learn how to use the Audio Route API of liblinphone.

Cheers,
