### ISSUE TITLE
Not able to compile linphone-sdk locally 

### ISSUE THREAD

**Issue by amit1576** [BelledonneCommunications/linphone-sdk#195]
@Viish ,

While compiling sdk i am encountering following issue.

Task :compileReleaseJavaWithJavac FAILED
/mnt/5.0.46-pre.1+8ba5376/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/compatibility/DeviceUtils31.java:70: error: cannot find symbol
                return android.os.Build.VERSION.MEDIA_PERFORMANCE_CLASS;
                                               ^
  symbol:   variable MEDIA_PERFORMANCE_CLASS
  location: class VERSION
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /mnt/5.0.46-pre.1+8ba5376/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/PushNotificationUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :parseDebugLocalResources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 1s
28 actionable tasks: 28 executed
CMake Error at /mnt/5.0.46-pre.1+8ba5376/linphone-sdk/cmake/Android/GenerateSDK.cmake:49 (message):
  Gradle assemble failed

CMakeFiles/sdk.dir/build.make:70: recipe for target 'CMakeFiles/sdk' failed
make[2]: *** [CMakeFiles/sdk] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/sdk.dir/all' failed
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Please suggest.

**Comment by Viish** [comment]
That's because you don't have installed Android S SDK platform.

**Comment by amit1576** [comment]
Hi @Viish,

I used to compile sdk on this very same machine till sdk 4.5. Is this Android S SDK platform required for latest linphone sdk. ?

**Comment by Viish** [comment]
Yes, as we use some Android S APIs on devices that run them.

**Comment by amit1576** [comment]
@Viish ,

Can you please tell me how to install the Android S SDK  platform, as I am unable to get any link?

**Comment by Viish** [comment]
Either use Android Studio's SDK manager or your command line tools: `sdkmanager platforms;android-31`

**Comment by amit1576** [comment]
Ok Thanks,
