### ISSUE TITLE
Cannot start the local conference again after ending for the first time

### ISSUE THREAD

**Issue by Mukesh2310** [BelledonneCommunications/linphone-sdk#197]
Hi @Viish,

I found an issue with the local conference, it is okay to start the local conference with multiple calls for the first time. However, after ending the local conference, it cannot be started again and prompting something like

**Switching conference [0x74af99d050] from state Created to TerminationPending
[Conference VM] Conference state changed: TerminationPending**

Seems like after the conference ended and changed the state to TerminationPending, Terminated & Deleted, it never reset to the correct state, and for all future attempts to start another local conference, it will fail by checking the state.

**Comment by amit1576** [comment]
Hi,

Is it resolved in Master branch of SDK ? 

Thanks,

**Comment by Viish** [comment]
> Is it resolved in Master branch of SDK ?

It seems so, I don't reproduce it.

**Comment by Mukesh2310** [comment]
> > Is it resolved in Master branch of SDK ?
> 
> It seems so, I don't reproduce it.

> 

Hi Viish, 

I observed that if I do not send gruu in support(using this code "core.removeSupportedTag("gruu")") then the issue is reproduced as per above.
