### ISSUE TITLE
Build SDK failed for Android when enable openh264

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-sdk#2]
I'm using ndk r20b and clone this project from master branch.

scanning dependencies of target EP_openh264
[ 79%] Creating directories for 'EP_openh264'
[ 79%] No download step for 'EP_openh264'
[ 80%] No patch step for 'EP_openh264'
[ 80%] No update step for 'EP_openh264'
[ 80%] Performing configure step for 'EP_openh264'
[ 80%] Forcing build for 'EP_openh264'
[ 80%] Performing build step for 'EP_openh264'
../../../../..//external/openh264/build/platform-android.mk:54: *** Compiler not found, bad NDKROOT or ARCH?.  Stop.
make[5]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_SDK_Master/linphone-sdk/build-android/WORK/android-arm64/Stamp/EP_openh264/EP_openh264-build] Error 2
make[4]: *** [CMakeFiles/EP_openh264.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
make: *** [all] Error 2

**Comment by Viish** [comment]
A fix for this issue is available on fix/android_embedded_openh264 branch that will be merged into release/4.3 branch soon.
