### ISSUE TITLE
[Bug]: List of Audiodevices never updated

### ISSUE THREAD

**Issue by raffael-gyr** [BelledonneCommunications/linphone-sdk#210]
### Context

I use the linphone-sdk in an Android app for our company. I want to do a call between the Android app on one device and a different Android phone. We use pbx4.cloudcall.ch as a SIP service.

### General information

- Device: Samsung Galaxy S9 (SM-G960F)
- OS: OneUI 2.5 based on Android 10
- Version of the App: None (It is not a problem in your app)
- Version of the SDK: 5.0.21

### Expected behaviour

I wanted to do a simple call with our Android client calling an Android phone. However, when pluging in my headset it doesn't appear in the list of audio devices and `onAudioDevicesListUpdated(core)` is never triggered.

### To Reproduce

1. Start the app without the headset plugged in
2. Plug in the headset
3. It doesn't matter how long I wait `onAudioDevicesListUpdated(core)` is never called and the list of audio devices never changes. Even when androids own BroadcastReceiver for `Intent.ACTION_HEADSET_PLUG` is called the list of audio devices of this SDK doesn't change.

### Additional context

Am I supposed to call some function to let the SDK know that I would want it to keep the list of audio devices updated?

**Comment by Viish** [comment]
Hi,

Please update your SDK to latest release (5.0.69) and attach logs showing the issue.

**Comment by raffael-gyr** [comment]
It still works the same way with version 5.0.69.
How am I supposed to attach logs? There is nothing in the logs.

**Comment by Viish** [comment]
Enable debug logs in advanced settings, restart your app, reproduce the issue and then click on upload logs button in advanced settings. Finally copy/paste the link here please.

**Comment by Viish** [comment]
Why did you became a ghost and closed this issue @raffael-gyr?

**Comment by raffaelgyr** [comment]
I closed this issue because it won't get resolved anyway. I obviously can't provide what you want. I do see the logs in AndroidStudio but when the headset is plugged in or out linphone doesn't print anything into logcat.  
*Yes, I do already call `Factory.instance().setDebugMode(true, "Linphone")`*

I became a ghost because I hoped that way it would not be as obvious for my employer that it was me asking this question. But since you tagged me by name, that failed. And now I am back with a new account.

**Comment by Viish** [comment]
> I closed this issue because it won't get resolved anyway. I obviously can't provide what you want.

And why is that? If you have the logs in adb logcat why can't you send them to me? 
Let me decide if they are helpful or not.
Also you can check if you reproduce this issue with our own linphone-android app.

> I became a ghost because I hoped that way it would not be as obvious for my employer that it was me asking this question.

Why don't you want your employer see you reporting an issue on an open-source project?

**Comment by raffaelgyr** [comment]
> And why is that? If you have the logs in adb logcat why can't you send them to me?

Because there is quite a lot of information in there that I am not sure if I am allowed to share it.

> Also you can check if you reproduce this issue with our own linphone-android app.

It works correctly in the linphone-android app.  
This is the log that is printed there when a headset is disconnected: [https://pastebin.com/e7AyEYBZ](https://pastebin.com/e7AyEYBZ).  
Those logs are never printed in my app.

> Why don't you want your employer see you reporting an issue on an open-source project?

Because I wasn't successful in my attempt to solve the problem and I didn't explicitly ask if I am allowed to post this question.

**Comment by Viish** [comment]
> It works correctly in the linphone-android app.
This is the log that is printed there when a headset is disconnected: https://pastebin.com/e7AyEYBZ.
Those logs are never printed in my app.

I guess you can see in your logs the following: `[Core Manager] Do you have a dependency on androidx.media:media:1.2.0 or newer?` ?
If yes, that will give you the solution on how to fix it.
If you had sent me your logs like I asked I would have been able to tell you that much sooner...

> Because I wasn't successful in my attempt to solve the problem and I didn't explicitly ask if I am allowed to post this question.

If you aren't allowed to send our own library logs that means you probably don't comply with the GPLv3 license...
Remind your company that we do sell proprietary licenses if they need, but if some day you publish a product using our SDK without proprietary license and without following GPLv3 license they expose themselves to legal pursuits.

**Comment by Viish** [comment]
> I was thinking more of account names, ip adresses, ids etc. that I am not sure I am allowed to share.

That you can anonymize before sending the logs to me with a find/replace, it's not relevant as information unless there is a network issue.

**Comment by raffaelgyr** [comment]
Sure, but I didn't want to take the risk to miss one.
