### ISSUE TITLE
How to fix error no such module for import linphone sdk macos

### ISSUE THREAD

**Issue by hushmand** [BelledonneCommunications/linphone-sdk#211]
I installed osx linphone-sdk using Pods With the following command in the Pod file

`pod 'linphone-sdk', '5.0.69', :source => ‘https://gitlab.linphone.org/BC/public/podspec-macos.git'
`

After executing command `pod install` and installing successfully Gives this error for `import linphonesw`

  No such module 'linphonesw'

<img width="470" alt="nC3GV" src="https://user-images.githubusercontent.com/14809049/153749075-123610f6-e10a-4b66-a7a8-0eaec7b908ed.png">

**Comment by siavashnamiranian** [comment]
i have the same issue
any solution?

**Comment by sianami** [comment]
Hi
i used this code https://gitlab.linphone.org/BC/public/linphone-sdk/-/commit/18cd2436eda9cb72023c4727691e4a2b764966d3
and now "import linphonesw" dont show No such module 'linphonesw' error
but in LinphoneWrapper.swift file "import linphone" show No such module 'linphone'
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/68529832/157125547-d22d4b8a-e8b6-4078-b621-57f02a17533a.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/68529832/157125562-d364f9a0-44c7-43aa-ab4d-9d0ac43f6b27.png)

**Comment by Viish** [comment]
@jehandelalune

**Comment by jehandelalune** [comment]
Hi,

it seems podspec was not compiled with swift wrapper in.
it should be fixed at least with version 5.1.24-pre.8+45e8f11f

Best regards

**Comment by hushmand** [comment]
Hi
I used version 5.1.24-pre.8+45e8f11f and it installed well.
But none of the features of Linphone, such as register, call, etc., work
