### ISSUE TITLE
Can't receive event Call.State.Error in onCallStateChanged

### ISSUE THREAD

**Issue by tanphat12041998** [BelledonneCommunications/linphone-sdk#220]
I use click to call on WebRTC to make calls on my mobile app, but the first event I get is Call.State.IncomingReceived and when I decline the call on the other device, I don't get the event Call.State.Error

**Comment by Viish** [comment]
That's because there is no error. When you answer a call on another device, the state of the call will be End followed by Released.

**Comment by tanphat12041998** [comment]
I don't answer the call, i decline the call, on my device has ring tone busy but i don't receive event error and call.errorInfo.reason is not busy
