### ISSUE TITLE
[issue]: App crash on Android 12, Samsung Galaxy S21 5G

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-sdk#222]
### Context

I use the linphone-sdk in the Linphone-Android version to make a VoIP app. 

### General information

- Device: Samsung Galaxy S21 5G
- OS: Android 12
- Version of the App: 4.6.3
- Version of the SDK: 5.1.24

### Expected behaviour

App shouldn't crash, but I don't know when this error occurs.

### To Reproduce

Hi, I'm monitoring my Android app with the Google Play Console, which reports any crashes that occur.

I found this one, the only problem is that I cannot know when this crash occurs...any ideas?

signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> myApp <<<

backtrace:
  #00  pc 0000000000001138  /apex/com.android.runtime/lib64/bionic/libdl.so (__cfi_slowpath+36)
  #00  pc 000000000009add8  /system/lib64/libaudioclient.so (android::ClientProxy::obtainBuffer(android::Proxy::Buffer*, timespec const*, timespec*)+956)
  #00  pc 0000000000059fbc  /system/lib64/libaudioclient.so (android::AudioRecord::obtainBuffer(android::AudioRecord::Buffer*, timespec const*, timespec*, unsigned long*)+376)
  #00  pc 000000000005974c  /system/lib64/libaudioclient.so (android::AudioRecord::processAudioBuffer()+1208)
  #00  pc 0000000000058fb4  /system/lib64/libaudioclient.so (android::AudioRecord::AudioRecordThread::threadLoop()+272)
  #00  pc 0000000000012170  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+460)
  #00  pc 00000000000beecc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+144)
  #00  pc 0000000000011960  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+404)
  #00  pc 00000000000b2fd0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #00  pc 0000000000052834  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by Viish** [comment]
Hi,

Given the stacktrace the crash is internal to the device's audio driver, there is no part of the stack trace that matches our SDK, so I can't do nothing.

Cheers,
