### ISSUE TITLE
[Bug]: Android App crashes occasionally during normal use

### ISSUE THREAD

**Issue by guodongAndroid** [BelledonneCommunications/linphone-sdk#224]
### Context

I use the linphone-sdk in the Linphone-android.
The version is 4.5.8.

### General information

- Device: rk3288
- OS: Android 7.1.2 API 25
- Version of the App:
- Version of the SDK: Linphone SDK 4.5.8

### Expected behaviour

We hope that the Linphone SDK does not crash.

### To Reproduce

Because the crash is sporadic and there are no specific steps to reproduce it, it has only occurred twice so far.
At the same time, because log collection is not enabled, there is no linphone1.log log file.

### Screenshots
![screenshot-1](https://user-images.githubusercontent.com/19586334/163740563-dfee552b-8329-480f-89e6-07e2df684407.png)
![screenshot-2](https://user-images.githubusercontent.com/19586334/163740572-ea132cda-be7c-43f2-8f61-963e1cf708c5.png)

### Logcat log
[linphone_crash.log](https://github.com/BelledonneCommunications/linphone-sdk/files/8502864/linphone_crash.log)

### Ndk-stack log
[ndk-stack.log](https://github.com/BelledonneCommunications/linphone-sdk/files/8502865/ndk-stack.log)
ndk-stack log uses ndk r16 version, linphone-sdk-android-debug-4.5.8 version, do you need any other information.

Looking forward to your reply.

**Comment by Viish** [comment]
Hi,
Sorry but we don't do support on older releases.
Latest SDK release is 5.1, so you are 2 major releases behind it, and there is a good chance your issue has been solved since.
By the way, now we recommend NDK r23b which is the latest LTS.
Cheers,

**Comment by guodongAndroid** [comment]
Thank you for your reply.
