### ISSUE TITLE
MacOS Features not working

### ISSUE THREAD

**Issue by hushmand** [BelledonneCommunications/linphone-sdk#226]
I installed macOS linphone-SDK But none of the features of Linphone, such as register, call, etc., work

This issue is used to install macOS linphone-sdk:
https://github.com/BelledonneCommunications/linphone-sdk/issues/211#issuecomment-1103603962

**Comment by KyronNextLevel** [comment]
Hello.
For now we don't have a way to end-to-end-test each package that we generate.

We have hundreds of issues for each project and I can't investigate it all, especially when it has little to no content...
The actual description is too vague and we can't take time to reproduce your issue.
Please open another issue and describe it explicitly with logs, reproduction pattern, version used, platform, logs and screenshots (I created the [Bug] template to help you with it) and I would take a look at it.
