### ISSUE TITLE
How to simplify SIP message to decrease the packet weight - Android

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-sdk#227]
Hello, I need to reduce the size of my SIP INVITE/REGISTER packet to less than 1400 byte (to use UDP protocol without fragmentation).

I managed to remove the "User-Agent" string, but now I need more.

1) Witch parts can I remove to still garantee the correct SIP packet?
 For example, for the contact:
 Contact: "---" <sip:---@---;pn-prid=---;pn-provider=fcm;pn-param=---;pn-silent=1;pn-timeout=0;transport=tls>;+sip.instance="<urn:uuid:---->";+org.linphone.specs="lime"

is there something I can remove?

2) I'm not so practice, where should I look to modify SIP packet?

Thank you.

**Comment by Viish** [comment]
Hi,

If you don't use push notifications you can disable them, that will remove all `pn-` params.
You can use `core.setSpecs("")` to remove the `org.linphone.specs` param.
Finally set the following in your factory rc to disable uuid:
```
[misc]
uuid=0
```

Cheers,
