### ISSUE TITLE
Android 4.4.0-beta compile error

### ISSUE THREAD

**Issue by X1opya** [BelledonneCommunications/linphone-sdk#23]
made an assembly based on r18b docker image

> Configure project :
As part of making the publishing plugins stable, the 'deferred configurable' behavior of the 'publishing {}' block has been deprecated. In Gradle 5.0 the 'enableFeaturePreview('STABLE_PUBLISHING')' flag will be removed and the new behavior will become the default. Please add 'enableFeaturePreview('STABLE_PUBLISHING')' to your settings file and do a test run by publishing to a local repository. If all artifacts are published as expected, there is nothing else to do. If the published artifacts change unexpectedly, please see the migration guide for more details: https://docs.gradle.org/4.10.1/userguide/publishing_maven.html#publishing_maven:deferred_configuration.
        at build_dzpvjz41mmlhkhqtsu7qa6b3q.run(/home/bc/linphone-sdk/build/build.gradle:30)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
Old java wrapper detected, adding it to sources and removing some incompatible classes

> Task :compileReleaseJavaWithJavac FAILED
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:24: error: cannot find symbol
import androidx.annotation.Keep;
                          ^
  symbol:   class Keep
  location: package androidx.annotation
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:25: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:27: error: package com.google.android.gms.common does not exist
import com.google.android.gms.common.ConnectionResult;
                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:28: error: package com.google.android.gms.common does not exist
import com.google.android.gms.common.GoogleApiAvailability;
                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:29: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.OnCompleteListener;
                                   ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:30: error: package com.google.android.gms.tasks does not exist
import com.google.android.gms.tasks.Task;
                                   ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:31: error: package com.google.firebase.iid does not exist
import com.google.firebase.iid.FirebaseInstanceId;
                              ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:32: error: package com.google.firebase.iid does not exist
import com.google.firebase.iid.InstanceIdResult;
                              ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:38: error: cannot find symbol
@Keep
 ^
  symbol: class Keep
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:27: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.FirebaseMessagingService;
                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:28: error: package com.google.firebase.messaging does not exist
import com.google.firebase.messaging.RemoteMessage;
                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:30: error: cannot find symbol
import org.linphone.core.Core;
                        ^
  symbol:   class Core
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:40: error: cannot find symbol
public class FirebaseMessaging extends FirebaseMessagingService {
                                       ^
  symbol: class FirebaseMessagingService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:53: error: cannot find symbol
    public void onMessageReceived(RemoteMessage remoteMessage) {
                                  ^
  symbol:   class RemoteMessage
  location: class FirebaseMessaging
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:30: error: package com.google.firebase does not exist
import com.google.firebase.FirebaseApp;
                          ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:32: error: cannot find symbol
import org.linphone.core.Call;
                        ^
  symbol:   class Call
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:33: error: cannot find symbol
import org.linphone.core.Core;
                        ^
  symbol:   class Core
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:34: error: cannot find symbol
import org.linphone.core.CoreListenerStub;
                        ^
  symbol:   class CoreListenerStub
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:63: error: cannot find symbol
    protected Core mCore;
              ^
  symbol:   class Core
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:70: error: cannot find symbol
    private CoreListenerStub mListener;
            ^
  symbol:   class CoreListenerStub
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:30: error: package androidx.media does not exist
import androidx.media.AudioAttributesCompat;
                     ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:31: error: package androidx.media.AudioAttributesCompat does not exist
import androidx.media.AudioAttributesCompat.Builder;
                                           ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:32: error: package androidx.media does not exist
import androidx.media.AudioManagerCompat;
                     ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:33: error: package androidx.media does not exist
import androidx.media.AudioFocusRequestCompat;
                     ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:39: error: cannot find symbol
import org.linphone.core.Core;
                        ^
  symbol:   class Core
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:40: error: cannot find symbol
import org.linphone.core.AudioDevice;
                        ^
  symbol:   class AudioDevice
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:76: error: cannot find symbol
    public CoreManager(Object context, Core core) {
                                       ^
  symbol:   class Core
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:108: error: cannot find symbol
    public Core getCore() {
           ^
  symbol:   class Core
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:46: error: cannot find symbol
    private AudioFocusRequestCompat mRingingRequest;
            ^
  symbol:   class AudioFocusRequestCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:47: error: cannot find symbol
    private AudioFocusRequestCompat mCallRequest;
            ^
  symbol:   class AudioFocusRequestCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:50: error: cannot find symbol
    private AudioDevice mPreviousDefaultOutputAudioDevice;
            ^
  symbol:   class AudioDevice
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:30: error: cannot find symbol
import androidx.annotation.RequiresApi;
                          ^
  symbol:   class RequiresApi
  location: package androidx.annotation
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:31: error: package androidx.core.app does not exist
import androidx.core.app.NotificationCompat;
                        ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:32: error: package androidx.core.app does not exist
import androidx.core.app.NotificationManagerCompat;
                        ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:34: error: cannot find symbol
import org.linphone.core.Core;
                        ^
  symbol:   class Core
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:35: error: cannot find symbol
import org.linphone.core.CoreListenerStub;
                        ^
  symbol:   class CoreListenerStub
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:36: error: cannot find symbol
import org.linphone.core.Factory;
                        ^
  symbol:   class Factory
  location: package org.linphone.core
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:56: error: cannot find symbol
    private CoreListenerStub mListener;
            ^
  symbol:   class CoreListenerStub
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:127: error: cannot find symbol
    @RequiresApi(api = Build.VERSION_CODES.O)
     ^
  symbol:   class RequiresApi
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:52: error: cannot find symbol
                            new OnCompleteListener<InstanceIdResult>() {
                                ^
  symbol:   class OnCompleteListener
  location: class FirebasePushHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:52: error: cannot find symbol
                            new OnCompleteListener<InstanceIdResult>() {
                                                   ^
  symbol:   class InstanceIdResult
  location: class FirebasePushHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:49: error: cannot find symbol
            FirebaseInstanceId.getInstance()
            ^
  symbol:   variable FirebaseInstanceId
  location: class FirebasePushHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:74: error: cannot find symbol
        GoogleApiAvailability googleApiAvailability = GoogleApiAvailability.getInstance();
        ^
  symbol:   class GoogleApiAvailability
  location: class FirebasePushHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:74: error: cannot find symbol
        GoogleApiAvailability googleApiAvailability = GoogleApiAvailability.getInstance();
                                                      ^
  symbol:   variable GoogleApiAvailability
  location: class FirebasePushHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebasePushHelper.java:76: error: cannot find symbol
        return resultCode == ConnectionResult.SUCCESS;
                             ^
  symbol:   variable ConnectionResult
  location: class FirebasePushHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:44: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:52: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:61: error: cannot find symbol
                Core core = CoreManager.instance().getCore();
                ^
  symbol:   class Core
  location: class FirebaseMessaging
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:75: error: cannot find symbol
        PackageManager pm = getPackageManager();
                            ^
  symbol:   method getPackageManager()
  location: class FirebaseMessaging
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:80: error: cannot find symbol
            if (packageName.equals(getPackageName())) {
                                   ^
  symbol:   method getPackageName()
  location: class FirebaseMessaging
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/firebase/FirebaseMessaging.java:84: error: cannot find symbol
                sendBroadcast(explicit);
                ^
  symbol:   method sendBroadcast(Intent)
  location: class FirebaseMessaging
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:93: error: cannot find symbol
            FirebaseApp.initializeApp(mContext);
            ^
  symbol:   variable FirebaseApp
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:139: error: cannot find symbol
        mListener = new CoreListenerStub() {
                        ^
  symbol:   class CoreListenerStub
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreManager.java:212: error: cannot find symbol
            Call call = mCore.getCurrentCall();
            ^
  symbol:   class Call
  location: class CoreManager
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:139: error: cannot find symbol
        AudioAttributesCompat audioAttrs = new AudioAttributesCompat.Builder()
        ^
  symbol:   class AudioAttributesCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:141: error: cannot find symbol
            .setContentType(AudioAttributesCompat.CONTENT_TYPE_MUSIC)
                            ^
  symbol:   variable AudioAttributesCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:140: error: cannot find symbol
            .setUsage(AudioAttributesCompat.USAGE_NOTIFICATION_RINGTONE)
                      ^
  symbol:   variable AudioAttributesCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:139: error: package AudioAttributesCompat does not exist
        AudioAttributesCompat audioAttrs = new AudioAttributesCompat.Builder()
                                                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:145: error: package AudioFocusRequestCompat does not exist
        mRingingRequest = new AudioFocusRequestCompat.Builder(AudioManagerCompat.AUDIOFOCUS_GAIN_TRANSIENT_EXCLUSIVE)
                                                     ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:145: error: cannot find symbol
        mRingingRequest = new AudioFocusRequestCompat.Builder(AudioManagerCompat.AUDIOFOCUS_GAIN_TRANSIENT_EXCLUSIVE)
                                                              ^
  symbol:   variable AudioManagerCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:150: error: cannot find symbol
        int result = AudioManagerCompat.requestAudioFocus(mAudioManager, mRingingRequest);
                     ^
  symbol:   variable AudioManagerCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:162: error: cannot find symbol
            AudioManagerCompat.abandonAudioFocusRequest(mAudioManager, mRingingRequest);
            ^
  symbol:   variable AudioManagerCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:179: error: cannot find symbol
        AudioAttributesCompat audioAttrs = new AudioAttributesCompat.Builder()
        ^
  symbol:   class AudioAttributesCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:181: error: cannot find symbol
            .setContentType(AudioAttributesCompat.CONTENT_TYPE_SPEECH)
                            ^
  symbol:   variable AudioAttributesCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:180: error: cannot find symbol
            .setUsage(AudioAttributesCompat.USAGE_VOICE_COMMUNICATION)
                      ^
  symbol:   variable AudioAttributesCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:179: error: package AudioAttributesCompat does not exist
        AudioAttributesCompat audioAttrs = new AudioAttributesCompat.Builder()
                                                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:184: error: package AudioFocusRequestCompat does not exist
         mCallRequest = new AudioFocusRequestCompat.Builder(AudioManagerCompat.AUDIOFOCUS_GAIN)
                                                   ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:184: error: cannot find symbol
         mCallRequest = new AudioFocusRequestCompat.Builder(AudioManagerCompat.AUDIOFOCUS_GAIN)
                                                            ^
  symbol:   variable AudioManagerCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:189: error: cannot find symbol
        int result = AudioManagerCompat.requestAudioFocus(mAudioManager, mCallRequest);
                     ^
  symbol:   variable AudioManagerCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:202: error: cannot find symbol
            AudioManagerCompat.abandonAudioFocusRequest(mAudioManager, mCallRequest);
            ^
  symbol:   variable AudioManagerCompat
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:232: error: cannot find symbol
        Core core = CoreManager.instance().getCore();
        ^
  symbol:   class Core
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:240: error: cannot find symbol
        Core core = CoreManager.instance().getCore();
        ^
  symbol:   class Core
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:242: error: package AudioDevice does not exist
        if (mPreviousDefaultOutputAudioDevice.getType() == AudioDevice.Type.Speaker) {
                                                                      ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:248: error: cannot find symbol
        for (AudioDevice audioDevice : core.getAudioDevices()) {
             ^
  symbol:   class AudioDevice
  location: class AudioHelper
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/audio/AudioHelper.java:249: error: package AudioDevice does not exist
            if (audioDevice.getType() == AudioDevice.Type.Speaker) {
                                                    ^
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:64: error: cannot find symbol
        Factory.instance();
        ^
  symbol:   variable Factory
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:70: error: cannot find symbol
        mListener = new CoreListenerStub() {
                        ^
  symbol:   class CoreListenerStub
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:90: error: cannot find symbol
            ^
  symbol:   class Core
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:135: error: can
not find symbol
        NotificationManagerCompat notificationManager = NotificationManagerCompat.from(this);
        ^
  symbol:   class NotificationManagerCompat
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:135: error: can
not find symbol
        NotificationManagerCompat notificationManager = NotificationManagerCompat.from(this);
                                                        ^
  symbol:   variable NotificationManagerCompat
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:156: error: can
not find symbol
                .setVisibility(NotificationCompat.VISIBILITY_SECRET)
                               ^
  symbol:   variable NotificationCompat
  location: class CoreService
/home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/service/CoreService.java:150: error: pac
kage NotificationCompat does not exist
        mServiceNotification = new NotificationCompat.Builder(this, SERVICE_NOTIFICATION_CHANNEL_ID)
                                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/bc/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/PushNotificationUtils.java uses un
checked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
82 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
10 actionable tasks: 1 executed, 9 up-to-date

**Comment by Viish** [comment]
Fixed by 5669ac68352dcc5cbd955625ee43424f428fec6c

**Comment by Viish** [comment]
Also it seems your docker image lacks a few Android components like androidx

**Comment by RaviChavada-dev** [comment]
From where I can download Linphone 4.4.0 android SDK

**Comment by Viish** [comment]
From our maven repository: https://linphone.org/maven_repository/org/linphone/linphone-sdk-android/
