### ISSUE TITLE
[Bug][iOS]: Sending DTMF stops outgoing audio

### ISSUE THREAD

**Issue by jeremynorman89** [BelledonneCommunications/linphone-sdk#231]
### Context

We use the linphone-sdk in an iOS app. We do not use sip.linphone.org, it is our own sip server.

### General information

- Device: iPhone 8 (but reproducible on all iPhones we have tested)
- OS: iOS 15
- Version of the SDK: 5.1.28 (bug was introduced in 5.0.71)

### Expected behaviour

I want to be able to use DTMF and also communicate with the other party.

### To Reproduce

1. Make a call
2. When the call is connected enter DTMF (any digit)
3. Note that audio has stopped

### Additional context

After DTMF is sent and the audio breaks, the following log message is spammed:

```
/Users/buildbot/builds/JASdzh_D/2/BC/public/linphone-sdk/oRTP/src/telephonyevents.c:116- assertiontev_pt!=-1failed
```

**Comment by Arguillq** [comment]
Hi,

I could not reproduce your issue on linphone-iphone 4.6.2 with SDK 5.1.30. 
I am be able to do much without some logs to analyse.

**Comment by Arguillq** [comment]
Could you please upload the application code you use to send your DTMFs ?

**Comment by jeremynorman89** [comment]
> Could you please upload the application code you use to send your DTMFs ?

Yes, sure. It's [here](https://github.com/open-voip-alliance/iOS-Phone-Lib/blob/eef0c44028df35bd57349b86303bd9957cd45fe9/iOSPhoneLib/iOSVoIPLib/Classes/Managers/Linphone/LinphoneManager.swift#L295).

All other methods called in the same way work perfectly fine. I've also tried calling `sendDtmf()` instead of `sendDtmfs()` but it doesn't change anything.

And to clarify something I said in the original post, this bug was introduced (at least for us) in version `5.0.71`. I can downgrade to `5.0.70` and it works fine, anything above that and we get this issue.

**Comment by jeremynorman89** [comment]
No problem at all, here are logs from `5.0.70` where it works great :D

[dtmf-bug-5-0-70-working.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/8716969/dtmf-bug-5-0-70-working.txt)

**Comment by Arguillq** [comment]
I believe the bug has been found, the fix will be integrated in 5.1. I'll updated you as soon as it is done !

**Comment by jeremynorman89** [comment]
Thank you so much!

**Comment by Arguillq** [comment]
Hello Jeremy,

a fix for your issue have been pushed for version 5.1.32
Can you give it a try and tell me if it worked on your side ?

**Comment by jeremynorman89** [comment]
That's fantastic that you've got a fix so quickly. I'll try it out asap. I don't see it in the [podspec](https://gitlab.linphone.org/BC/public/podspec) repo yet. Do you know when that would happen?

**Comment by jeremynorman89** [comment]
I've been able to test it and it works great. Thanks so much for the quick turnaround!
