### ISSUE TITLE
[Bug]: SIP contact contain ABCD1234.myApp.voip

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/linphone-sdk#232]
### Context

I use the linphone-sdk in my app based on linphone-iphone 

### General information

- Version of the App: 4.6.2
- Version of the SDK: 5.1.24

### Expected behaviour

My contact contain pn-param with ABCD1234, how can I modify this parameter and the others?

### To Reproduce

Just made a call and see the parameters generated in my PJSIP contact

**Comment by Viish** [comment]
You should take a look at the following wiki entry about push notifications : https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/

**Comment by mircoiplabs** [comment]
Hi, I tried to do the changes following the wiki you sent (like set use_legacy_push_notification_params=1 in linphonerc file), but when I do a call, I always see the same pn-param with ABCD1234.myPackage, which I suppose it's not a good thing...

In the < 5 sdk I used to set my "ios-token= ... " (the pn-prid renamed) removing all the others params, but changing in different ways the push params as the wiki says I do not obtain any relevant result. 

Any other options?

Thank you.

**Comment by brianomchugh** [comment]
Anyone figure this one out? If I was to compile from source, where do I change this value? Right now I am trying to set the "teamID" property but it has no effect:
```
            accountParams.registerEnabled = true
            accountParams.pushNotificationAllowed = true
            accountParams.pushNotificationConfig!.provider = "apns.dev"
            //This does nothing!
            accountParams.pushNotificationConfig!.teamId = "TESTID123"
            mAccount = try mCore!.createAccount(params: accountParams)
            mCore!.addAuthInfo(info: authInfo)
            try mCore!.addAccount(account: mAccount!)
            mCore!.defaultAccount = mAccount
```
