### ISSUE TITLE
[Bug]: Prebuilt iOS release is missing support for arm64-simulator

### ISSUE THREAD

**Issue by chrishendersonc4** [BelledonneCommunications/linphone-sdk#239]
### Context

I have a MacBook with Apple Silicon. The current prebuilt binaries at https://download.linphone.org/releases/ios/?C=M;O=D do not include support for the arm64-simulator, so I can't run my app with linphone's prebuilt binaries on the simulator. Running Xcode under Rosetta is not an option for us, as it is buggy and doesn't work with Apple Watch apps. To add support for the arm64 simulator, xcframework must be used instead of the regular .framework.

### General information

- Device: MacBook Pro M1 (2020)
- OS: iOS Simulator 15.5, macOS 12.2.1
- Version of the App: N/A
- Version of the SDK: 5.1.41

### Expected behaviour

Prebuilt binaries should be in the xcframework format and plug-and-play for arm64-simulator.

### To Reproduce

Try and build an app with prebuilt linphone-sdk on an M1 in Xcode (native--not Rosetta). It will fail.

### Additional context

I was able to generate a xcframework by running the following commands:

```
git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive
cd linphone-sdk
mkdir build
cd build
cmake .. -G Xcode -DLINPHONESDK_PLATFORM=IOS -DLINPHONESDK_IOS_PLATFORM="Both" -DLINPHONESDK_IOS_ARCHS="arm64,x86_64"
cmake --build . --config RelWithDebInfo
```

Yes, we could do this ourselves, but it'd be great if linphone-sdk came this way. 😄

### SDK logs URL

N/A

**Comment by HZ4ever228** [comment]
@chrishendersonc4, do you solve this? When i try ti use your instruction - on the last step - i have a ** BUILD FAILED ** problem. And, how to use that later, when its build? How to connect this with project?
I have m1 macbook.

**Comment by chrishendersonc4** [comment]
@HZ4ever228 I'm terribly sorry! I missed your response. Anyways, I was told that a fix should be included in linphone now. This should be a problem of the past.
