### ISSUE TITLE
How the country code can be disabled by default ?

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/linphone-sdk#24]
Hi,

I have a annoying issue - each time when I configure new SIP account using the generic form (or the Linphone form) there is a country code (prefix, e.g +1 for USA) added to configuration. I's a problem, because in 4-digits logins I need to always delete from the Prefix field of the account settings.

@Viish said "it is done by the SDK, not the app.
From the moment you connect using a phone number the dial prefix will be set in the proxy config."

_Originally posted by @Viish in https://github.com/BelledonneCommunications/linphone-android/issues/904#issuecomment-578642195_

I have tried editing dial-plan.cpp in linphone-sdk, but the Prefix is still there. Would you advise me which file to edit to get rid the Prefix ?

**Comment by Viish** [comment]
In coreapi/account-manager.c, remove or comment out the calls to linphone_proxy_config_set_dial_prefix() method.
