### ISSUE TITLE
sdk for android building successful when ANDROID_ARCHS=arm64 , but failed with "armv7" 

### ISSUE THREAD

**Issue by alun0829** [BelledonneCommunications/linphone-sdk#241]
Hi everyone, I'm trying to build linphone sdk for android on a Ubuntu VM 22.04 with the following steps:

$ git clone https://gitlab.linphone.org/BC/public/linphone-sdk --recursive -b release/5.1
$ docker pull gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android-r20:20210914_update_java11
$ cd linphone-sdk-5.1
$ docker run -it --volume=$PWD:/home/bc/linphone-sdk gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android-r20:20210914_update_java11 /bin/bash -i
$ mkdir /home/bc/linphone-sdk/build && cd /home/bc/linphone-sdk/build
$ cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS=armv7
$ make -j 8

The build was successful when I tried by "-DLINPHONESDK_ANDROID_ARCHS=arm64" , and it always fails when set up "-DLINPHONESDK_ANDROID_ARCHS=armv7" with the following errors :
(I have tried sdk source code: release/5.1  release/5.0 release/4.5 , but all got the same error.)

<pre><code>
BUILD SUCCESSFUL in 1s
1 actionable task: 1 up-to-date
[  0%] Built target gradle-clean
[  9%] Creating directories for 'android-armv7'
[ 18%] No download step for 'android-armv7'
[ 27%] No update step for 'android-armv7'
[ 36%] No patch step for 'android-armv7'
[ 45%] Performing configure step for 'android-armv7'
loading initial cache file /home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7-prefix/tmp/android-armv7-cache-RelWithDebInfo.cmake
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - broken
CMake Error at /opt/cmake3/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_e89cc/fast && make[3]: Entering directory '/home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    /usr/bin/make  -f CMakeFiles/cmTC_e89cc.dir/build.make CMakeFiles/cmTC_e89cc.dir/build
    make[4]: Entering directory '/home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_e89cc.dir/testCCompiler.c.o
    /opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security   -fPIE -MD -MT CMakeFiles/cmTC_e89cc.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_e89cc.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_e89cc.dir/testCCompiler.c.o -c /home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_e89cc
    /opt/cmake3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e89cc.dir/link.txt --verbose=1
    /opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -march=armv7-a -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security   -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,--gc-sections   CMakeFiles/cmTC_e89cc.dir/testCCompiler.c.o -o cmTC_e89cc  -latomic -lm 
    /opt/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: cmTC_e89cc: Input/output error
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_e89cc.dir/build.make:99: recipe for target 'cmTC_e89cc' failed
    make[4]: *** [cmTC_e89cc] Error 1
    make[4]: Leaving directory '/home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_e89cc/fast' failed
    make[3]: *** [cmTC_e89cc/fast] Error 2
    make[3]: Leaving directory '/home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    
  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt

-- Configuring incomplete, errors occurred!
See also "/home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeOutput.log".
See also "/home/bc/linphone-sdk/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeError.log".
CMakeFiles/android-armv7.dir/build.make:94: recipe for target 'android-armv7-prefix/src/android-armv7-stamp/android-armv7-configure' failed
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-configure] Error 1
CMakeFiles/Makefile2:140: recipe for target 'CMakeFiles/android-armv7.dir/all' failed
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
</code></pre>

Did i missing something? 
I have attached one file is the build output: [CMakeError.log](https://github.com/BelledonneCommunications/linphone-sdk/files/8889259/CMakeError.log)

Thanks!

**Comment by Viish** [comment]
Hi

Can you try with `gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android-r23:20220609_android_33` docker image?

Cheers,

**Comment by alun0829** [comment]
Hi. Thanks for your post.I tried the docker image and got the same errors:
<pre><code>
Welcome to Gradle 7.0.2!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :clean UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 21s
1 actionable task: 1 up-to-date
[  0%] Built target gradle-clean
[  9%] Creating directories for 'android-armv7'
[ 18%] No download step for 'android-armv7'
[ 27%] No update step for 'android-armv7'
[ 36%] No patch step for 'android-armv7'
[ 45%] Performing configure step for 'android-armv7'
loading initial cache file /home/bc/linphone-sdk/build_android_x86/android-armv7-prefix/tmp/android-armv7-cache-RelWithDebInfo.cmake
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is Clang 12.0.9
-- The CXX compiler identification is Clang 12.0.9
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - broken
CMake Error at /opt/cmake3/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_93c36/fast && make[3]: Entering directory '/home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    /usr/bin/make  -f CMakeFiles/cmTC_93c36.dir/build.make CMakeFiles/cmTC_93c36.dir/build
    make[4]: Entering directory '/home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_93c36.dir/testCCompiler.c.o
    /opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fPIE -MD -MT CMakeFiles/cmTC_93c36.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_93c36.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_93c36.dir/testCCompiler.c.o -c /home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_93c36
    /opt/cmake3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_93c36.dir/link.txt --verbose=1
    /opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi21 --gcc-toolchain=/opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections   CMakeFiles/cmTC_93c36.dir/testCCompiler.c.o -o cmTC_93c36  -latomic -lm 
    ld: error: cannot open output file cmTC_93c36: Input/output error
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_93c36.dir/build.make:99: recipe for target 'cmTC_93c36' failed
    make[4]: *** [cmTC_93c36] Error 1
    make[4]: Leaving directory '/home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_93c36/fast' failed
    make[3]: *** [cmTC_93c36/fast] Error 2
    make[3]: Leaving directory '/home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeTmp'
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "/home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeOutput.log".
See also "/home/bc/linphone-sdk/build_android_x86/android-armv7/CMakeFiles/CMakeError.log".
CMakeFiles/android-armv7.dir/build.make:94: recipe for target 'android-armv7-prefix/src/android-armv7-stamp/android-armv7-configure' failed
make[2]: *** [android-armv7-prefix/src/android-armv7-stamp/android-armv7-configure] Error 1
CMakeFiles/Makefile2:140: recipe for target 'CMakeFiles/android-armv7.dir/all' failed
make[1]: *** [CMakeFiles/android-armv7.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

</code></pre>


the build output file:[CMakeError.log](https://github.com/BelledonneCommunications/linphone-sdk/files/8895607/CMakeError.log)

Then i tried by "-DLINPHONESDK_ANDROID_ARCHS=arm64" ,the build was successful.

**Comment by alun0829** [comment]
> Hi
> 
> Can you try with `gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android-r23:20220609_android_33` docker image?
> 
> Cheers,

Hi, thanks for your supported! I tried copying the SDK source codes to the docker container, the build was successful.
The build can not work for vmhgfs when -DLINPHONESDK_ANDROID_ARCHS=armv7,  but arm64 was fined.

**Comment by Viish** [comment]
Have you tried removing your build directory and starting fresh?
This looks weird: `ld: error: cannot open output file cmTC_16f71: Input/output error`

Also we do use those docker images every day for an all platforms build, so there shouldn't be any issue with it.
