### ISSUE TITLE
How to find the source code of the native method in linphone-sdk-android?

### ISSUE THREAD

**Issue by August1023** [BelledonneCommunications/linphone-sdk#245]
Can the source code of the native method in linphone-sdk-android be found in liblinphone? I haven't found some native methods. How to map the native method in linphone-sdk-android to the method in liblinphone?

**Comment by Viish** [comment]
For example core.iterate() will be linphone_core_iterate() in C. Same for setters (core.setOutputAudioDevice is linphone_core_set_output_audio_device), etc...
