### ISSUE TITLE
Crash: Fatal signal 11 (SIGSEGV1), code 1 (SEGV_MAPERR), Android Changing Audio Device

### ISSUE THREAD

**Issue by baojiao9799** [BelledonneCommunications/linphone-sdk#248]
### Context

I use the linphone-sdk for an Android app to do VOIP calling. I've added linphone-sdk-android to the app using the maven repository. One thing I'm using it for is routing the audio between different audio devices during a call.

### General information

- Device: Galaxy Tab S7
- OS: Android 12
- Version of the App: n/a
- Version of the SDK: 5.1.55

- Device: Redmi Note 11
- OS: Android 11
- Version of the App: n/a
- Version of the SDK: 5.1.55

- Device: Redmi Note 11
- OS: Android 11
- Version of the App: 4.7.0
- Version of the SDK: 5.2.0

### Expected behaviour

I want to change the output audio device during a call with the audio correctly routed to the specified device and without the app crashing.

### To Reproduce

1. After the call is connected, connect a wired or bluetooth audio device
2. Toggle between different audio devices
3. Eventually, audio will stop coming through the selected device, and upon switching a couple more times, the app will crash
4. See the segmentation fault

### Additional context

I also checked out master of linphone-android, which uses 5.2+ for the linphone sdk version and was able to reproduce the crash with a wired headset on the Redmi Note 11 device. The crash does seem to be device-dependent, with it being easier to reproduce on some devices than other devices. 

My Android App Log Leading Up to Crash:
[android_app_seg_fault_log.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/9310638/android_app_seg_fault_log.txt)

Native backtrace:
[audio_device_native_stack_trace.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/9310639/audio_device_native_stack_trace.txt)

Linphone Android App Log Leading Up to Crash (native backtrace at end of log): 
[linphone_android_logcat_native_stacktrace.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/9310646/linphone_android_logcat_native_stacktrace.txt)

**Comment by Viish** [comment]
Hi @baojiao9799,

This crashed is caused by AAudioStream_waitForStateChange method that does crash quite often...
Latest version of 5.2.0-alpha SDK should fix that.
