### ISSUE TITLE
iOS 16 with XCode 14 no longer support VOIP socket

### ISSUE THREAD

**Issue by chanffdavid** [BelledonneCommunications/linphone-sdk#250]
The following message comes from XCode 14 on iOS 16 iPhone

Run LinPhone SDK 1.5.58 with LinPhone-iPhone 4.6.6 

libsp.dylib`spd_checkin_socket.cold.1:
    0x226af4364 <+0>:  adrp   x8, 141669
    0x226af4368 <+4>:  adrp   x9, 0
    0x226af436c <+8>:  add    x9, x9, #0xa3f            ; "Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead"
    0x226af4370 <+12>: str    x9, [x8, #0x400]
->  0x226af4374 <+16>: brk    #0x1

**Comment by grit96** [comment]
I am also encountering this on Xcode 14 and iOS 16

**Comment by Viish** [comment]
Don't worry we are aware of that and we are working on a fix.

**Comment by Viish** [comment]
https://github.com/BelledonneCommunications/linphone-sdk/issues/251

**Comment by xunuosi** [comment]
Waite this fix coming

**Comment by mrgoutam** [comment]
Right now the best solution is uninstall Xcode 14 and install Xcode 13.4.1.
This issue will not come.

**Comment by Viish** [comment]
@mrgoutam, this issue has been fixed in 5.1.60 SDK release.

**Comment by bbatuhandogan** [comment]
> @mrgoutam, this issue has been fixed in 5.1.60 SDK release.

Hello, I faced the same problem. What solution did you use? Thanks in advance

**Comment by Viish** [comment]
@bbatuhandogan Here's the fix: https://gitlab.linphone.org/BC/public/belle-sip/-/blob/6df7534aa3213f3a27a054e7f76a79778c5b3265/src/transports/stream_channel.c#L225

**Comment by bbatuhandogan** [comment]
> @bbatuhandogan Here's the fix: https://gitlab.linphone.org/BC/public/belle-sip/-/blob/6df7534aa3213f3a27a054e7f76a79778c5b3265/src/transports/stream_channel.c#L225

I greatly appreciate it. Have a nice day.

**Comment by eskov-ea** [comment]
> @bbatuhandogan Here's the fix: https://gitlab.linphone.org/BC/public/belle-sip/-/blob/6df7534aa3213f3a27a054e7f76a79778c5b3265/src/transports/stream_channel.c#L225

Hi, may you tell how it can get fixed with linphone-sdk?

**Comment by goutam-xtremsoft** [comment]
Two steps I have done. Working fine for all of my clients.
1. removed **AFNetworking** pod
2. removed below lines 

`[inputStream setProperty:NSStreamNetworkServiceTypeVoIP forKey:NSStreamNetworkServiceType] ;
  [outputStream  setProperty:NSStreamNetworkServiceTypeVoIP forKey:NSStreamNetworkServiceType] ;
`

I was using `NSInputStream`, `NSOutputStream`.
2nd point is important.

**Comment by Jigs6720** [comment]
https://gitlab.linphone.org/BC/public/belle-sip/-/blob/6df7534aa3213f3a27a054e7f76a79778c5b3265/src/transports/stream_channel.c#L225 where to find this in my xcode project
