### ISSUE TITLE
[Bug]: Crash on registration when build with iOS SDK 16.0 and run in iOS 16

### ISSUE THREAD

**Issue by astralus-vanstijn** [BelledonneCommunications/linphone-sdk#251]
### Context

I use the linphone-sdk in to build an iOS app with voice functionality.
I've callkit enabled and today updated my mac (uses now Xcode 14 with iOS SDK 16.0) and iphone (is now iOS 16.0)

Now every time i call the registration function to register the account the app crashes. i was able to extract this message from the call stack:

Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead

I also tested with my second device an older iPhone SE first generation that only has iOS 15.7 and there the SDK has no problems.

### General information

- Device: iPhone 13 mini
- OS: iOS 16
- Version of the App: n/a
- Version of the SDK: 5.1.57

### Expected behaviour

SDK registers the account and is ready the send and receive calls

### To Reproduce

- Compile a project on Xcode 14.0
- Start a app with the linphone-sdk on an iOS 16 device with connected debugger.
- Register SIP account
- App will crash with the error

**Comment by grit96** [comment]
I am also encountering this on Xcode 14 and iOS 16

**Comment by Viish** [comment]
Don't worry we are aware of that and we are working on a fix.

**Comment by guidedways** [comment]
@Viish sorry this is unrelated to linphone-sdk - we don't use VoIP sockets in our app and the app has no such functionality. Yet it crashes at launch with this exact message. What framework / API calls may we be using (or one of our 3rd party libraries using) that could cause this? Any tip would be appreciated.

**Comment by guidedways** [comment]
Okay - turned out to be Firebase. Updated and that fixed it for us.

**Comment by Viish** [comment]
Fix is available in 5.1.60 or newer SDK release, as well as on master branch.

**Comment by Jigs6720** [comment]
there is not version 5.1.60 available. but i had installed 5.1.61 after then i am getting this errors.
