### ISSUE TITLE
[Bug]: In linphon sdk build

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-sdk#267]
### Context

admin@ip-10-1-233-38:~/linphone-sdk/build$ cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=ON -DENABLE_G729B_CNG=ON -DENABLE_VIDEO=ON -DENABLE_ADVANCED_IM=ON -DENABLE_DB_STORAGE=ON
CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    bctoolbox/cmake/BcToolboxCMakeUtils.cmake

CMake Error at CMakeLists.txt:35 (bc_compute_full_version):
  Unknown CMake command "bc_compute_full_version".

-- Configuring incomplete, errors occurred!
See also "/home/admin/linphone-sdk/build/CMakeFiles/CMakeOutput.log".
admin@ip-10-1-233-38:~/linphone-sdk/build$ cat /home/admin/linphone-sdk/build/CMakeFiles/CMakeOutput.log 
The system is: Linux - 4.19.0-21-cloud-amd64 - x86_64
admin@ip-10-1-233-38:~/linphone-sdk/build$

### General information

Device: cloud Machine

### Expected behaviour

New SDK

### To Reproduce

admin@ip-10-1-233-38:~/linphone-sdk/build$ cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=ON -DENABLE_G729B_CNG=ON -DENABLE_VIDEO=ON -DENABLE_ADVANCED_IM=ON -DENABLE_DB_STORAGE=ON
CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    bctoolbox/cmake/BcToolboxCMakeUtils.cmake

CMake Error at CMakeLists.txt:35 (bc_compute_full_version):
  Unknown CMake command "bc_compute_full_version".

-- Configuring incomplete, errors occurred!
See also "/home/admin/linphone-sdk/build/CMakeFiles/CMakeOutput.log".
admin@ip-10-1-233-38:~/linphone-sdk/build$ cat /home/admin/linphone-sdk/build/CMakeFiles/CMakeOutput.log 
The system is: Linux - 4.19.0-21-cloud-amd64 - x86_64
admin@ip-10-1-233-38:~/linphone-sdk/build$

**Comment by Viish** [comment]
Did you check the submodules were correctly cloned?
You need to use `git submodules update --recursive --init` after cloning the SDK.

**Comment by disolaterX** [comment]
I did that too this was the output


➜  linphone-sdk git:(master) git submodule update --init --recursive

Submodule 'bcg729' (git@github.com:BelledonneCommunications/bcg729.git) registered for path 'bcg729'
Submodule 'bcmatroska2' (git@github.com:BelledonneCommunications/bcmatroska2.git) registered for path 'bcmatroska2'
Submodule 'bctoolbox' (git@github.com:BelledonneCommunications/bctoolbox.git) registered for path 'bctoolbox'
Submodule 'bcunit' (git@github.com:BelledonneCommunications/bcunit.git) registered for path 'bcunit'
Submodule 'belcard' (git@github.com:BelledonneCommunications/belcard.git) registered for path 'belcard'
Submodule 'belle-sip' (git@github.com:BelledonneCommunications/belle-sip.git) registered for path 'belle-sip'
Submodule 'belr' (git@github.com:BelledonneCommunications/belr.git) registered for path 'belr'
Submodule 'bzrtp' (git@github.com:BelledonneCommunications/bzrtp.git) registered for path 'bzrtp'
Submodule 'cmake-builder' (git@github.com:BelledonneCommunications/linphone-cmake-builder.git) registered for path 'cmake-builder'
Submodule 'external/bv16-floatingpoint' (https://gitlab.linphone.org/BC/public/external/bv16-floatingpoint.git) registered for path 'external/bv16-floatingpoint'
Submodule 'external/codec2' (https://gitlab.linphone.org/BC/public/external/codec2.git) registered for path 'external/codec2'
Submodule 'external/decaf' (https://gitlab.linphone.org/BC/public/external/decaf.git) registered for path 'external/decaf'
Submodule 'external/ffmpeg' (https://gitlab.linphone.org/BC/public/external/ffmpeg.git) registered for path 'external/ffmpeg'
Submodule 'external/gsm' (https://gitlab.linphone.org/BC/public/external/gsm.git) registered for path 'external/gsm'
Submodule 'external/jsoncpp' (https://github.com/open-source-parsers/jsoncpp.git) registered for path 'external/jsoncpp'
Submodule 'external/libjpeg-turbo' (https://gitlab.linphone.org/BC/public/external/libjpeg-turbo.git) registered for path 'external/libjpeg-turbo'
Submodule 'external/liboqs' (https://gitlab.linphone.org/BC/public/external/liboqs.git) registered for path 'external/liboqs'
Submodule 'external/libvpx' (https://gitlab.linphone.org/BC/public/external/libvpx.git) registered for path 'external/libvpx'
Submodule 'external/libxml2' (https://gitlab.linphone.org/BC/public/external/libxml2.git) registered for path 'external/libxml2'
Submodule 'external/libyuv' (https://gitlab.linphone.org/BC/public/external/libyuv.git) registered for path 'external/libyuv'
Submodule 'external/mbedtls' (https://gitlab.linphone.org/BC/public/external/mbedtls.git) registered for path 'external/mbedtls'
Submodule 'external/opencore-amr' (https://gitlab.linphone.org/BC/public/external/opencore-amr.git) registered for path 'external/opencore-amr'
Submodule 'external/openh264' (https://gitlab.linphone.org/BC/public/external/openh264.git) registered for path 'external/openh264'
Submodule 'external/openldap' (https://gitlab.linphone.org/BC/public/external/openldap.git) registered for path 'external/openldap'
Submodule 'external/opus' (https://gitlab.linphone.org/BC/public/external/opus.git) registered for path 'external/opus'
Submodule 'external/soci' (https://gitlab.linphone.org/BC/public/external/soci.git) registered for path 'external/soci'
Submodule 'external/speex' (https://gitlab.linphone.org/BC/public/external/speex.git) registered for path 'external/speex'
Submodule 'external/sqlite3' (https://gitlab.linphone.org/BC/public/external/sqlite3.git) registered for path 'external/sqlite3'
Submodule 'external/srtp' (https://gitlab.linphone.org/BC/public/external/srtp.git) registered for path 'external/srtp'
Submodule 'external/vo-amrwbenc' (https://gitlab.linphone.org/BC/public/external/vo-amrwbenc.git) registered for path 'external/vo-amrwbenc'
Submodule 'external/xerces-c' (https://gitlab.linphone.org/BC/public/external/xerces-c.git) registered for path 'external/xerces-c'
Submodule 'external/zlib' (https://gitlab.linphone.org/BC/public/external/zlib.git) registered for path 'external/zlib'
Submodule 'external/zxing-cpp' (https://gitlab.linphone.org/BC/public/external/zxing-cpp.git) registered for path 'external/zxing-cpp'
Submodule 'liblinphone' (git@github.com:BelledonneCommunications/liblinphone.git) registered for path 'liblinphone'
Submodule 'lime' (git@github.com:BelledonneCommunications/lime.git) registered for path 'lime'
Submodule 'mediastreamer2' (git@github.com:BelledonneCommunications/mediastreamer2.git) registered for path 'mediastreamer2'
Submodule 'msaaudio' (git@github.com:BelledonneCommunications/msaaudio.git) registered for path 'msaaudio'
Submodule 'msamr' (git@github.com:BelledonneCommunications/msamr.git) registered for path 'msamr'
Submodule 'msandroidcamera2' (git@github.com:BelledonneCommunications/msandroidcamera2.git) registered for path 'msandroidcamera2'
Submodule 'mscodec2' (https://gitlab.linphone.org/BC/public/mscodec2.git) registered for path 'mscodec2'
Submodule 'msoboe' (git@github.com:BelledonneCommunications/msoboe.git) registered for path 'msoboe'
Submodule 'msopenh264' (git@github.com:BelledonneCommunications/msopenh264.git) registered for path 'msopenh264'
Submodule 'mssilk' (git@github.com:BelledonneCommunications/mssilk.git) registered for path 'mssilk'
Submodule 'mswasapi' (git@github.com:BelledonneCommunications/mswasapi.git) registered for path 'mswasapi'
Submodule 'mswebrtc' (git@github.com:BelledonneCommunications/mswebrtc.git) registered for path 'mswebrtc'
Submodule 'mswinrtvid' (git@github.com:BelledonneCommunications/mswinrtvid.git) registered for path 'mswinrtvid'
Submodule 'ortp' (git@github.com:BelledonneCommunications/ortp.git) registered for path 'ortp'
Submodule 'postquantumcryptoengine' (git@github.com:BelledonneCommunications/postquantumcryptoengine.git) registered for path 'postquantumcryptoengine'
Cloning into '/home/disolaterx/linphone-sdk/bcg729'...
Cloning into '/home/disolaterx/linphone-sdk/bcmatroska2'...
Cloning into '/home/disolaterx/linphone-sdk/bctoolbox'...
Cloning into '/home/disolaterx/linphone-sdk/bcunit'...
Cloning into '/home/disolaterx/linphone-sdk/belcard'...
Cloning into '/home/disolaterx/linphone-sdk/belle-sip'...
Cloning into '/home/disolaterx/linphone-sdk/belr'...
Cloning into '/home/disolaterx/linphone-sdk/bzrtp'...
Cloning into '/home/disolaterx/linphone-sdk/cmake-builder'...
Cloning into '/home/disolaterx/linphone-sdk/external/bv16-floatingpoint'...
Cloning into '/home/disolaterx/linphone-sdk/external/codec2'...
Cloning into '/home/disolaterx/linphone-sdk/external/decaf'...
Cloning into '/home/disolaterx/linphone-sdk/external/ffmpeg'...
Cloning into '/home/disolaterx/linphone-sdk/external/gsm'...
Cloning into '/home/disolaterx/linphone-sdk/external/jsoncpp'...
Cloning into '/home/disolaterx/linphone-sdk/external/libjpeg-turbo'...
Cloning into '/home/disolaterx/linphone-sdk/external/liboqs'...
Cloning into '/home/disolaterx/linphone-sdk/external/libvpx'...
Cloning into '/home/disolaterx/linphone-sdk/external/libxml2'...
Cloning into '/home/disolaterx/linphone-sdk/external/libyuv'...
Cloning into '/home/disolaterx/linphone-sdk/external/mbedtls'...
Cloning into '/home/disolaterx/linphone-sdk/external/opencore-amr'...
Cloning into '/home/disolaterx/linphone-sdk/external/openh264'...
Cloning into '/home/disolaterx/linphone-sdk/external/openldap'...
Cloning into '/home/disolaterx/linphone-sdk/external/opus'...
Cloning into '/home/disolaterx/linphone-sdk/external/soci'...
Cloning into '/home/disolaterx/linphone-sdk/external/speex'...
Cloning into '/home/disolaterx/linphone-sdk/external/sqlite3'...
Cloning into '/home/disolaterx/linphone-sdk/external/srtp'...
Cloning into '/home/disolaterx/linphone-sdk/external/vo-amrwbenc'...
Cloning into '/home/disolaterx/linphone-sdk/external/xerces-c'...
Cloning into '/home/disolaterx/linphone-sdk/external/zlib'...
Cloning into '/home/disolaterx/linphone-sdk/external/zxing-cpp'...
Cloning into '/home/disolaterx/linphone-sdk/liblinphone'...
Cloning into '/home/disolaterx/linphone-sdk/lime'...
Cloning into '/home/disolaterx/linphone-sdk/mediastreamer2'...
Cloning into '/home/disolaterx/linphone-sdk/msaaudio'...
Cloning into '/home/disolaterx/linphone-sdk/msamr'...
Cloning into '/home/disolaterx/linphone-sdk/msandroidcamera2'...
Cloning into '/home/disolaterx/linphone-sdk/mscodec2'...
Cloning into '/home/disolaterx/linphone-sdk/msoboe'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:BelledonneCommunications/msoboe.git' into submodule path '/home/disolaterx/linphone-sdk/msoboe' failed
Failed to clone 'msoboe'. Retry scheduled
Cloning into '/home/disolaterx/linphone-sdk/msopenh264'...
Cloning into '/home/disolaterx/linphone-sdk/mssilk'...
Cloning into '/home/disolaterx/linphone-sdk/mswasapi'...
Cloning into '/home/disolaterx/linphone-sdk/mswebrtc'...
Cloning into '/home/disolaterx/linphone-sdk/mswinrtvid'...
Cloning into '/home/disolaterx/linphone-sdk/ortp'...
Cloning into '/home/disolaterx/linphone-sdk/postquantumcryptoengine'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:BelledonneCommunications/postquantumcryptoengine.git' into submodule path '/home/disolaterx/linphone-sdk/postquantumcryptoengine' failed
Failed to clone 'postquantumcryptoengine'. Retry scheduled
Cloning into '/home/disolaterx/linphone-sdk/msoboe'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:BelledonneCommunications/msoboe.git' into submodule path '/home/disolaterx/linphone-sdk/msoboe' failed
Failed to clone 'msoboe' a second time, aborting

**Comment by Viish** [comment]
Try cloning from gitlab instead: `https://gitlab.linphone.org/BC/public/linphone-sdk.git`

**Comment by disolaterX** [comment]
@Viish Have a look

2023-01-29 16:19:49.397 [info] Cloning into '/home/disolaterx/linphone-sdk'...
git@gitlab.linphone.org: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Viish** [comment]
You can't clone from our gitlab using git, but you can using https.

**Comment by CuongPhi** [comment]
> Did you check the submodules were correctly cloned? You need to use `git submodules update --recursive --init` after cloning the SDK.

git submodules update --recursive --init => git submodule update --recursive --init
