### ISSUE TITLE
Xamarin build

### ISSUE THREAD

**Issue by lucasbrahm** [BelledonneCommunications/linphone-sdk#268]
Xamarin builds stop being generated after 5.1.74 version.

Usually the build versions are generated and can be downloaded in this link:
https://download.linphone.org/releases/xamarin/

**Comment by julonexus** [comment]
Hi
From 5.2, the Xamarin is now generated in the Nuget registry at https://gitlab.linphone.org/BC/public/linphone-sdk/-/packages
Regards
