### ISSUE TITLE
Emply contact after built sdk with codec g729

### ISSUE THREAD

**Issue by tpov** [BelledonneCommunications/linphone-sdk#271]
I have a problem, I built sdk, and I then started to display an empty contact list, I did not collect correctly

Build configuration ->

- Successfully Android SDK download after below mention command execute
$ mkdir build
$ cd build

$ export ANDROID_HOME=$HOME/Android/Sdk && export PATH=$PATH:$ANDROID_HOME/tools && export PATH=$PATH:/home/user/Android/Sdk/ndk/24.0.8215888 && export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

$ cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=OFF -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=OFF -DENABLE_GSM=OFF -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF

$ cmake --build .

**Comment by tpov** [comment]
> I have a problem, I built sdk, and I then started to display an empty contact list, I did not collect correctly
> 
> Build configuration ->
> 
> * Successfully Android SDK download after below mention command execute
>   $ mkdir build
>   $ cd build
> 
> $ export ANDROID_HOME=$HOME/Android/Sdk && export PATH=$PATH:$ANDROID_HOME/tools && export PATH=$PATH:/home/user/Android/Sdk/ndk/24.0.8215888 && export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
> 
> $ cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=OFF -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=OFF -DENABLE_GSM=OFF -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF
> 
> $ cmake --build .

**Comment by Viish** [comment]
It may be related to the `-DENABLE_VCARD=OFF` option. vCard is used by our SDK to store contact information.
