### ISSUE TITLE
[Bug]: Unable to build XCode Project on 5.2.0+

### ISSUE THREAD

**Issue by wboyd600** [BelledonneCommunications/linphone-sdk#273]
### Context

I use the linphone-sdk for an iOS app to do VOIP calling. I'm trying to use the 'linphone-sdk' pod on version 5.2.18 (also tried 5.2.0) sourced from https://gitlab.linphone.org/BC/public/podspec.git.

I have been successfully building the app with version 5.1.73 using CocoaPods sourced from https://gitlab.linphone.org/BC/public/podspec.git. 

When trying to update to the latest CocoaPods Version, I am getting 20 build errors for each framework saying this:

"Multiple commands produce '/Users/username/Library/Developer/Xcode/DerivedData/project-name-bizbhbgihtqaogeqnxcfbufhtjxj/Build/Products/Debug-iphonesimulator/project-name.app/Frameworks/bctoolbox-ios.framework'"

Clicking the drop-down on the errors says:

"That command depends on command in Target 'project-name' (project 'project-name'): script phase “[CP] Embed Pods Frameworks”"

The `Embed Pods Framework` section on our target hasn't changed. The script is just:
`"${PODS_ROOT}/Target Support Files/Pods-project-name/Pods-project-name-frameworks.sh"`

With Input File List as:
`${PODS_ROOT}/Target Support Files/Pods-project-name/Pods-project-name-${CONFIGURATION}-input-files.xcfilelist`

And Output File List as:
`${PODS_ROOT}/Target Support Files/Pods-project-name/Pods-project-name-frameworks-${CONFIGURATION}-output-files.xcfilelist`

### General information

- Device: iPod Touch (7th generation) iOS 15.7.2
- OS:  macOS Monterery Version 12.6
- XCode Version: 14.2
- Version of the App: N/A
- Version of the SDK: 5.2.18

### Expected behaviour

I expected to be able to build the app after updating the Pod to `5.2.0` and `5.2.18`.

### To Reproduce

Attempt to build an iOS project in XCode 14.2 after to updating to the most recent Pod sourced from https://gitlab.linphone.org/BC/public/podspec.git.

**Comment by arjenfvellinga** [comment]
I'm experiencing the same problem.

This ticket https://github.com/CocoaPods/CocoaPods/issues/11737 on the CocoaPods projects suggests it's related to the introduction of .xcframework .

@wboyd600 did you find a solution or workaround?

**Comment by arjenfvellinga** [comment]
Same problem with the [1.12.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.0) release of CocoaPods

**Comment by JulianBissekkou** [comment]
This also happens in `5.2.27`

**Comment by arjenfvellinga** [comment]
Found the following solution (?) in another [ticket](https://github.com/CocoaPods/CocoaPods/issues/8122), but I don't know what the exact impact is or side effects  are. Add to your pod file

`install! 'cocoapods', :disable_input_output_paths => true`

It could increase the build time.

**Comment by JulianBissekkou** [comment]
> Found the following solution (?) in another [ticket](https://github.com/CocoaPods/CocoaPods/issues/8122), but I don't know what the exact impact is or side effects  are. Add to your pod file:
> 
> 
> 
> `install! 'cocoapods', :disable_input_output_paths => true`
> 
> 
> 
> It could increase the build time.

In my case this caused a runtime crash
