### ISSUE TITLE
Demo app link not found

### ISSUE THREAD

**Issue by johnnylee194** [BelledonneCommunications/linphone-sdk#278]
As described in the [Readme.md](https://github.com/BelledonneCommunications/linphone-sdk#demo-app), the demo app link can't be found

![image](https://user-images.githubusercontent.com/43883/217991272-1cded641-c122-4c14-b1b1-aeab5d853d1a.png)

**Comment by Viish** [comment]
Sorry, indeed there is an issue with the link that specifies a branch that seems to no longer exist.
Proper link is https://gitlab.linphone.org/BC/public/linphone-windows10
I'll fix the README, thanks for reporting it!
