### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by oenama** [BelledonneCommunications/linphone-sdk#296]
### General information

- Device: Mac OS 
- OS: Ventura 13.2
- Version of the SDK: 5.3.0 
- Xcode Version 14.3

cmake .. -G Ninja -DLINPHONESDK_PLATFORM:STRING=IOS  -DENABLE_G729=YES  -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF

building SKD for ios error : 
** BUILD INTERRUPTED **

warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'sdk' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/sdk' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'sdk' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ALL_BUILD' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'gen-frameworks' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/gen-frameworks' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'gen-frameworks' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ios-arm64-simulator' from project 'linphone-sdk')
note: Run script build phase 'Generate ios-arm64-simulator-prefix/src/ios-arm64-simulator-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-arm64-simulator-force_build' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-arm64-simulator' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/ios-arm64-simulator' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-arm64-simulator' from project 'linphone-sdk')
note: Run script build phase 'Generate ios-arm64-simulator-prefix/src/ios-arm64-simulator-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-arm64-simulator-build' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-arm64-simulator' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-arm64-simulator-complete' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-arm64-simulator' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ios-x86_64' from project 'linphone-sdk')
note: Run script build phase 'Generate ios-x86_64-prefix/src/ios-x86_64-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-x86_64-force_build' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-x86_64' from project 'linphone-sdk')
note: Run script build phase 'Generate ios-x86_64-prefix/src/ios-x86_64-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-x86_64-build' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-x86_64' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/ios-x86_64' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-x86_64' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-x86_64-complete' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-x86_64' from project 'linphone-sdk')

** BUILD FAILED **
The following build commands failed:
	PhaseScriptExecution Generate\ ios-arm64-simulator-prefix/src/ios-arm64-simulator-stamp/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/ios-arm64-simulator-build /Users/username/Desktop/linphone-new/linphone-sdk/build/build/linphone-sdk.build/Debug-iphonesimulator/ios-arm64-simulator.build/Script-0A1C17F56D330715D593B320.sh (in target 'ios-arm64-simulator' from project 'linphone-sdk')
(1 failure)

**Comment by Viish** [comment]
Please try with latest version from release/5.2 branch, Simon made a fix for XCode 14.3 build.

**Comment by Usman-basalte** [comment]
@oenama I am having the same error. Did you find any solution for this error?

**Comment by ogrodowski-tomasz** [comment]
I get the same error but. Using Xcode 15.2 tho. Any update on that issue?

**Comment by Viish** [comment]
There is a breaking change in XCode 15 that prevents our SDK from building. Use Ninja instead of XCode and it will be ok.
