### ISSUE TITLE
Error build SDK with xerces-c in Android NDK

### ISSUE THREAD

**Issue by tpov** [BelledonneCommunications/linphone-sdk#308]
[ 21%] Building CXX object src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUCS4Transcoder.cpp.o
[ 21%] Building CXX object src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUni.cpp.o
[ 22%] Building CXX object src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUri.cpp.o
[ 22%] Building CXX object src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLURL.cpp.o
[ 22%] Building CXX object src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUTF16Transcoder.cpp.o
PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DHAVE_CONFIG_H -I/home/user/linphone-sdk/build/WORK/android-arm64/Build/xerces -I/home/user/linphone-sdk/external/xerces-c/src -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions -Os -g -DNDEBUG -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUTF16Transcoder.cpp.o -MF CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUTF16Transcoder.cpp.o.d -o CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUTF16Transcoder.cpp.o -c /home/user/linphone-sdk/external/xerces-c/src/xercesc/util/XMLUTF16Transcoder.cpp
1.	<eof> parser at end of file
2.	Optimizer
 #0 0x00000000047d91d8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x47d91d8)
 #1 0x00000000047d8340 llvm::sys::RunSignalHandlers() (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x47d8340)
 #2 0x00000000047a3dc3 (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x47a3dc3)
 #3 0x00000000047a3fa1 (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x47a3fa1)
 #4 0x00007ff67830a980 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12980)
 #5 0x00000000065bec46 llvm::VPTransformState::get(llvm::VPValue*, llvm::VPIteration const&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65bec46)
 #6 0x00000000065be8b9 llvm::InnerLoopVectorizer::scalarizeInstruction(llvm::Instruction*, llvm::VPReplicateRecipe*, llvm::VPIteration const&, bool, llvm::VPTransformState&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65be8b9)
 #7 0x00000000065be760 llvm::VPReplicateRecipe::execute(llvm::VPTransformState&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65be760)
 #8 0x00000000065be31e llvm::VPBasicBlock::execute(llvm::VPTransformState*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65be31e)
 #9 0x00000000065be047 llvm::VPRegionBlock::execute(llvm::VPTransformState*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65be047)
#10 0x00000000065bdf6c llvm::VPRegionBlock::execute(llvm::VPTransformState*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65bdf6c)
#11 0x00000000066fabf1 llvm::VPlan::execute(llvm::VPTransformState*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66fabf1)
#12 0x00000000062fd91e llvm::LoopVectorizationPlanner::executePlan(llvm::ElementCount, unsigned int, llvm::VPlan&, llvm::InnerLoopVectorizer&, llvm::DominatorTree*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x62fd91e)
#13 0x000000000663a48f llvm::LoopVectorizePass::processLoop(llvm::Loop*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x663a48f)
#14 0x0000000005edebea llvm::LoopVectorizePass::runImpl(llvm::Function&, llvm::ScalarEvolution&, llvm::LoopInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::BlockFrequencyInfo&, llvm::TargetLibraryInfo*, llvm::DemandedBits&, llvm::AAResults&, llvm::AssumptionCache&, std::__1::function<llvm::LoopAccessInfo const& (llvm::Loop&)>&, llvm::OptimizationRemarkEmitter&, llvm::ProfileSummaryInfo*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5edebea)
#15 0x0000000005eddbb9 llvm::LoopVectorizePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5eddbb9)
#16 0x0000000005edd89b (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5edd89b)
#17 0x0000000005c6168a llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5c6168a)
#18 0x0000000005c61521 clang::TemplateDeclInstantiator::VisitPragmaDetectMismatchDecl(clang::PragmaDetectMismatchDecl*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5c61521)
#19 0x0000000005ec7112 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5ec7112)
#20 0x0000000005ec6dd1 (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5ec6dd1)
#21 0x00000000063538c6 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x63538c6)
#22 0x00000000065d66c8 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x65d66c8)
#23 0x00000000060524d5 (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x60524d5)
#24 0x0000000005ea25a9 clang::ParseAST(clang::Sema&, bool, bool) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x5ea25a9)
#25 0x00000000063c128d clang::FrontendAction::Execute() (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x63c128d)
#26 0x00000000063c112d clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x63c112d)
#27 0x00000000063c1541 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x63c1541)
#28 0x00000000066a9f54 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a9f54)
#29 0x00000000066a6de3 (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a6de3)
#30 0x00000000066a6c92 (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a6c92)
#31 0x00000000066a6c61 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a6c61)
#32 0x00000000066a69f4 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a69f4)
#33 0x00000000066a685f clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a685f)
#34 0x00000000066a66f2 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66a66f2)
#35 0x00000000066752ee main (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x66752ee)
#36 0x00007ff677349c87 __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:344:0
#37 0x00000000064cce69 _start (/home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang+++0x64cce69)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
Target: aarch64-none-linux-android21
Thread model: posix
InstalledDir: /home/user/Android/Sdk/ndk/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/XMLUTF16Transcoder-5340b1.cpp
clang++: note: diagnostic msg: /tmp/XMLUTF16Transcoder-5340b1.sh
clang++: note: diagnostic msg: 

********************
src/CMakeFiles/xerces-c-static.dir/build.make:1013: recipe for target 'src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUTF16Transcoder.cpp.o' failed
make[8]: *** [src/CMakeFiles/xerces-c-static.dir/xercesc/util/XMLUTF16Transcoder.cpp.o] Error 139
CMakeFiles/Makefile2:97: recipe for target 'src/CMakeFiles/xerces-c-static.dir/all' failed
make[7]: *** [src/CMakeFiles/xerces-c-static.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make[6]: *** [all] Error 2
CMakeFiles/EP_xerces.dir/build.make:87: recipe for target '/home/user/linphone-sdk/build/WORK/android-arm64/Stamp/EP_xerces/EP_xerces-build' failed
make[5]: *** [/home/user/linphone-sdk/build/WORK/android-arm64/Stamp/EP_xerces/EP_xerces-build] Error 2
CMakeFiles/Makefile2:251: recipe for target 'CMakeFiles/EP_xerces.dir/all' failed
make[4]: *** [CMakeFiles/EP_xerces.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/android-arm64.dir/build.make:87: recipe for target 'android-arm64-prefix/src/android-arm64-stamp/android-arm64-build' failed
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
CMakeFiles/Makefile2:114: recipe for target 'CMakeFiles/android-arm64.dir/all' failed
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
user@ubuntu:~/linphone-sdk/build$ ^C

**Comment by tpov** [comment]
I build https://gitlab.linphone.org/BC/public/linphone-sdk/-/commit/d6c7561ffaecb43bce24e5f34c1a8e023fde6503

**Comment by Viish** [comment]
Yes we are aware of this crash using NDK 25c, use 25b and everything will be fine.
