### ISSUE TITLE
windows 10 x64 build error in decaf

### ISSUE THREAD

**Issue by debugcommand** [BelledonneCommunications/linphone-sdk#32]
1.decaf\src\CMakeLists.txt  39
if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64") # x86_64
CMAKE_SYSTEM_PROCESSOR always AMD64
2.decaf\src\include\arch_x86_64\arch_intrinsics.h
__uint128_t not defined  in windows 10

-cmake -G "Visual Studio 15 2017 Win64" ..
-open vs2017 build
-error:
-linphone-sdk\external\decaf\src\include\constant_time.h(151): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 C:\workspace\codes\linphone-gitlab\linphone-sdk\external\decaf\src\p25519\arch_32\f_impl.c) [C:\workspace\codes\linphone-gitlab\linphone-sdk\build_64\WORK\desktop\Build\decaf\src\p25519\p25519.vcxproj] [C:\workspace\codes\linphone-gitlab\linphone-sdk\build_64\desktop\EP_decaf.vcxproj]

**Comment by debugcommand** [comment]
look like some project don't support to build x64 in visual studio

**Comment by KyronNextLevel** [comment]
Hello.
As of now, 64 bit build isn't supported yet. 
As far as I know, 32 bit build is actually sufficient.

Please tell me why you would need 64 bits build of the SDK.
I would put this on the roadmap if it is really needed.

Regards

**Comment by debugcommand** [comment]
@KyronNextLevel 
i want used in Uinty,it's need x64 dll on windows platform,then i can debug on Unity editor.
but now,i had to wrapped Android SDK for Unity,it's too troublesome to debug

**Comment by KyronNextLevel** [comment]
@debugcommand 
I see...
Unity 5 has a 32 bits editor https://unity3d.com/fr/get-unity/download/archive
If your game doesn't need a lot of memory, you can go with 32 bits.
If not, please send us a development request by filling [our typeform (click on "contact us")](https://linphone.org/contact#content-bottom3).
Our team will then come back to you.
Regards

**Comment by debugcommand** [comment]
final,unspported unity editor,wrapper native android for unity,it is working!

**Comment by TheNeSSePa** [comment]
can u give me you linphone native android unity sdk ?

**Comment by TheNeSSePa** [comment]
> final,unspported unity editor,wrapper native android for unity,it is working!

can u give me you linphone native android unity sdk ?
