### ISSUE TITLE
[Bug]: Build fails with cmake ENABLE_ZRTP argument

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-sdk#324]
### Context

I'm trying to build a custom Linphone SDK for Android.

### General information

- Device: Virtual machine
- OS: Ubuntu 22.04.2 LTS
- Version of the App: 
- Version of the SDK: 5.2.94 5100 (release/5.2 branch)

### Expected behaviour

When the mediastreamer component is building, there are a lot of ZRTP errors thrown which result in a build failure. Even when I explicitly disable ZTRTP within the cmake command.

`/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:912:59: error: unused parameter 'sessions' [-Werror,-Wunused-parameter]
MSZrtpContext* ms_zrtp_context_new(MSMediaStreamSessions *sessions, MSZrtpParams *params){
                                                          ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:912:83: error: unused parameter 'params' [-Werror,-Wunused-parameter]
MSZrtpContext* ms_zrtp_context_new(MSMediaStreamSessions *sessions, MSZrtpParams *params){
                                                                                  ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:917:63: error: unused parameter 'sessions' [-Werror,-Wunused-parameter]
MSZrtpContext* ms_zrtp_multistream_new(MSMediaStreamSessions *sessions, MSZrtpContext* activeContext) {
                                                              ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:917:88: error: unused parameter 'activeContext' [-Werror,-Wunused-parameter]
MSZrtpContext* ms_zrtp_multistream_new(MSMediaStreamSessions *sessions, MSZrtpContext* activeContext) {
                                                                                       ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:922:45: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
void ms_zrtp_enable_go_clear(MSZrtpContext *ctx, bool_t enable) {};
                                            ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:922:57: error: unused parameter 'enable' [-Werror,-Wunused-parameter]
void ms_zrtp_enable_go_clear(MSZrtpContext *ctx, bool_t enable) {};
                                                        ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:923:42: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
int ms_zrtp_channel_start(MSZrtpContext *ctx) { return 0;}
                                         ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:925:42: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
void ms_zrtp_sas_verified(MSZrtpContext* ctx){}
                                         ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:926:48: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
void ms_zrtp_sas_reset_verified(MSZrtpContext* ctx){}
                                               ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:927:48: error: unused parameter 'db' [-Werror,-Wunused-parameter]
MSZrtpPeerStatus ms_zrtp_get_peer_status(void *db, const char *peerUri, bctbx_mutex_t *dbMutex) {return MS_ZRTP_PEER_STATUS_UNKNOWN;}
                                               ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:927:64: error: unused parameter 'peerUri' [-Werror,-Wunused-parameter]
MSZrtpPeerStatus ms_zrtp_get_peer_status(void *db, const char *peerUri, bctbx_mutex_t *dbMutex) {return MS_ZRTP_PEER_STATUS_UNKNOWN;}
                                                               ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:927:88: error: unused parameter 'dbMutex' [-Werror,-Wunused-parameter]
MSZrtpPeerStatus ms_zrtp_get_peer_status(void *db, const char *peerUri, bctbx_mutex_t *dbMutex) {return MS_ZRTP_PEER_STATUS_UNKNOWN;}
                                                                                       ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:928:45: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
void ms_zrtp_context_destroy(MSZrtpContext *ctx){}
                                            ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:929:53: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
void ms_zrtp_reset_transmition_timer(MSZrtpContext* ctx) {};
                                                    ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:930:51: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
int ms_zrtp_transport_modifier_new(MSZrtpContext* ctx, RtpTransportModifier **rtpt, RtpTransportModifier **rtcpt ) {return 0;}
                                                  ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:930:79: error: unused parameter 'rtpt' [-Werror,-Wunused-parameter]
int ms_zrtp_transport_modifier_new(MSZrtpContext* ctx, RtpTransportModifier **rtpt, RtpTransportModifier **rtcpt ) {return 0;}
                                                                              ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:930:108: error: unused parameter 'rtcpt' [-Werror,-Wunused-parameter]
int ms_zrtp_transport_modifier_new(MSZrtpContext* ctx, RtpTransportModifier **rtpt, RtpTransportModifier **rtcpt ) {return 0;}
                                                                                                           ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:931:63: error: unused parameter 'tp' [-Werror,-Wunused-parameter]
void ms_zrtp_transport_modifier_destroy(RtpTransportModifier *tp)  {}
                                                              ^
/home/ddegendt/linphone-sdk/mediastreamer2/src/crypto/zrtp.c:932:49: error: unused parameter 'zrtp_context' [-Werror,-Wunused-parameter]
void ms_zrtp_set_stream_sessions(MSZrtpContext *zrtp_context, MSMediaStreamSessions *stream_sessions) {}
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[8]: *** [src/CMakeFiles/mediastreamer.dir/build.make:594: src/CMakeFiles/mediastreamer.dir/crypto/zrtp.c.o] Error 1
make[8]: *** Waiting for unfinished jobs....
make[7]: *** [CMakeFiles/Makefile2:250: src/CMakeFiles/mediastreamer.dir/all] Error 2
make[6]: *** [Makefile:136: all] Error 2
make[5]: *** [CMakeFiles/EP_ms2.dir/build.make:88: /home/ddegendt/linphone-sdk/build/WORK/android-arm64/Stamp/EP_ms2/EP_ms2-build] Error 2
make[4]: *** [CMakeFiles/Makefile2:206: CMakeFiles/EP_ms2.dir/all] Error 2
make[3]: *** [Makefile:91: all] Error 2
make[2]: *** [CMakeFiles/android-arm64.dir/build.make:88: android-arm64-prefix/src/android-arm64-stamp/android-arm64-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:170: CMakeFiles/android-arm64.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
`

### To Reproduce

Even when I add the -ENABLE_ZRTP=NO argument, ZRTP is somehow included when the mediastreamer module is compiled. Removing this parameter from the cmake command makes the build complete succesfully.

**Comment by Viish** [comment]
Hi @driesken,

What cmake options are you using? What NDK version are you using?
Can you attach the whole build logs?

Also make sure you are on the latest commit on release/5.2 branch (currently d11ee80e4f7ee67e876656286d94ffda49ac1d4e) and that your submodules are updated (git submodule update --recursive --init).

**Comment by Viish** [comment]
Indeed we don't have added the required BCTBX_UNUSED macro in the ZRTP stubs in mediastreamer2, guess we don't often build it without ZRTP...
We'll make the fix, thanks for reporting it!

**Comment by driesken** [comment]
@Viish 

Building with the -DENABLE_STRICT=OFF argument also seems to fail:
`-- Install configuration: "RelWithDebInfo"
-- Installing: /home/ddegendt/linphone-sdk/build/linphone-sdk/android-armv7/lib/libbellesip.a
[ 79%] Completed 'EP_bellesip'
[ 80%] Built target EP_bellesip
make[3]: *** [Makefile:91: all] Error 2
make[2]: *** [CMakeFiles/android-armv7.dir/build.make:88: android-armv7-prefix/src/android-armv7-stamp/android-armv7-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:144: CMakeFiles/android-armv7.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
`

If interessted, I've attached the build logs as well.
[buildlogs2.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/12238238/buildlogs2.txt)

For now, ommiting the -DENABLE_ZRTP is enough for me.

**Comment by Viish** [comment]
@driesken That's weird...

Can you checkout SDK branch `fix/missing_unused` (it's right above latest release/5.2 commit) and confirm it does build correctly on your computer too?

Thanks in advance.

**Comment by driesken** [comment]
@Viish I've build the checkout branch with the following cmake options but it throws an non related error I suppose.
`export CMAKE_OPTIONS="-DENABLE_VIDEO=YES -DENABLE_AAUDIO=YES -DENABLE_CAMERA2=YES -DENABLE_FFMPEG=NO -DENABLE_VPX=NO -DENABLE_OPENH264=NO -DENABLE_EMBEDDED_OPENH264=YES -DENABLE_MPEG4=NO -DENABLE_H263P=NO -DENABLE_NON_FREE_CODECS=ON -DENABLE_QRCODE=ON -DENABLE_LIME=NO -DENABLE_LIME_X3DH=NO -DENABLE_ADVANCED_IM=NO -DENABLE_VCARD=YES -DENABLE_DB_STORAGE=YES -DENABLE_ZRTP=NO -DENABLE_MKV=NO -DENABLE_OPUS=YES -DENABLE_G729=NO -DENABLE_G729B_CNG=NO -DENABLE_JPEG=YES -DENABLE_ILBC=NO -DENABLE_ISAC=NO -DENABLE_WEBRTC_AEC=NO -DENABLE_WEBRTC_AECM=NO -DENABLE_WEBRTC_VAD=NO -DENABLE_UPDATE_CHECK=NO -DENABLE_UNIT_TESTS=YES -DENABLE_FLEXIAPI=NO"
`

`/home/ddegendt/linphone-sdk/liblinphone/src/c-wrapper/api/c-call.cpp:699:57: error: unused parameter 'call' [-Werror,-Wunused-parameter]
void linphone_call_confirm_go_clear(const LinphoneCall *call) {
`

Build logs:
[buildlogs3.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/12238646/buildlogs3.txt)

**Comment by Viish** [comment]
Thanks! How about now with SDK commit `4938179acb5c1ffd3643f2c0a85ae38d43e95ecb` (don't forget to update submodules)

**Comment by driesken** [comment]
That one fixed it, build has been succesfull. Thanks!

**Comment by Viish** [comment]
You're welcome. I'll merge the fix in release/5.2 as soon as the CI completes.
