### ISSUE TITLE
Top mic doesn't work in spearker mode on Samsung s10e

### ISSUE THREAD

**Issue by qw1nzup** [BelledonneCommunications/linphone-sdk#33]
bottom mic is turned on when we turn on speaker mode 

excepted results:
Top mic should be tunred on when we turn on speaker mode  - it is a default behaviour of skeaker mode.

[MediaRecorder.AudioSource.MIC](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#MIC) - bottom mic
[MediaRecorder.AudioSource.CAMCORDER](https://developer.android.com/reference/android/media/MediaRecorder.AudioSource#CAMCORDER) - top mic

**Comment by KyronNextLevel** [comment]
Hello. You got a workaround idea by my colleague in your linphone-android ticket.
As of now, without manual flags, those settings are managed automatically by the audiomanager.
We are working on audio routes to manage it ourselves, but it is still ongoing development.
