### ISSUE TITLE
Win10 build error

### ISSUE THREAD

**Issue by Denny0503** [BelledonneCommunications/linphone-sdk#34]
-- Selecting Windows SDK version  to target Windows 10.0.18363.
  -- Using mbedTLS
  -- Using Decaf
  -- DTLS SRTP available
  -- Configuring done
  -- Generating done
  -- Build files have been written to: D:/linphone-sdk-build/WORK/desktop/Build/bctoolbox
  Forcing build for 'EP_bctoolbox'
  Performing build step for 'EP_bctoolbox'
  用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
  版权所有(C) Microsoft Corporation。保留所有权利。

    bctoolbox.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bctoolbox\src\Release\bctoolbox.dll
    bctoolbox-tester.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bctoolbox\src\Release\bctoolbox-tester.dll
D:\linphone-sdk-build\linphone-sdk\desktop\bin\decaf.dll : fatal error LNK1107: 文件无效或损坏: 无法在 0x2B8 处读取 [D:\linphone-sdk-build\WORK\desktop\Build\bctoolbox\tester\bctoolbox_tester_exe.vcxproj] [D:\linphone-sdk-build\desktop\EP_bctoolbox.vcxproj]

**Comment by KyronNextLevel** [comment]
Hello.
Some info is missing for me to investigate.
To help you I need to see what you have entered as cmake commands (both configure and build).
Please send me those logs and I'll give it a look.

**Comment by Denny0503** [comment]
Here is the logs：

  Creating directories for 'sdk'
  Building Custom Rule D:/linphone-sdk/CMakeLists.txt
  No download step for 'sdk'
  No update step for 'sdk'
  No patch step for 'sdk'
  Performing configure step for 'sdk'
  loading initial cache file D:/linphone-sdk-build/sdk-prefix/tmp/sdk-cache-RelWithDebInfo.cmake
  CMake Warning (dev) in CMakeLists.txt:
    No project() command is present.  The top-level CMakeLists.txt file must
    contain a literal, direct call to the project() command.  Add a line of
    code such as
  
      project(ProjectName)
  
    near the top of the file, but after cmake_minimum_required().
  
    CMake is pretending there is a "project(Project)" command on the first
    line.
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  -- Using configuration file 'D:/linphone-sdk/cmake-builder/configs/config-desktop.cmake'
  -- Up-to-date: D:/linphone-sdk-build/linphone-sdk/desktop/include/MSVC/inttypes.h
  -- Up-to-date: D:/linphone-sdk-build/linphone-sdk/desktop/include/MSVC/stdint.h
  -- Including builder linphone
  -- Including builder bctoolbox
  -- Including builder mbedtls
  -- Including builder bcunit
  -- Including builder decaf
  -- Including builder bellesip
  -- Including builder zlib
  -- Including builder ortp
  -- Including builder ms2
  -- Including builder gsm
  -- Including builder opus
  -- Including builder speex
  -- Including builder bv16
  -- Including builder turbojpeg
  -- Including builder vpx
  绯荤粺鎵句笉鍒版寚瀹氱殑璺緞銆?
  -- Including builder matroska2
  -- Including builder srtp
  -- Including builder bzrtp
  -- Including builder sqlite3
  -- Including builder xml2
  -- Including builder ms2plugins
  -- Including builder mswebrtc
  -- Including builder mswasapi
  -- Including builder mswinrtvid
  -- Including builder belr
  -- Including builder soci
  -- Including builder libxsd
  -- Including builder xerces
  -- Including builder belcard
  -- Including builder lime
  -- Configuring done
  -- Generating done
  -- Build files have been written to: D:/linphone-sdk-build/desktop/Autotools
  -- Enabled features:
   * Unit tests, Enable unit tests support with BCUnit library.
   * Tools, Enable tools binary compilation.
   * Xml2, Enable bc version of libxml2
   * Sqlite, Enable bc version of sqlite3
   * Zlib, Enable bc version of zlib
   * CXX wrapper, Build the C++ wrapper for Liblinphone.
   * CSharp wrapper, Build the C# wrapper from Liblinphone.
   * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
   * VCARD, Enable vCard 4 support in Linphone and Liblinphone.
   * Assets, Enable packaging of assets (ringtones) when building the SDK.
   * Advanced IM, Enable advanced instant messaging such as group chat.
   * DB Storage, Enable the database storage.
   * Mbedtls, Crypto stack implementation based on mbeddtls.
   * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
   * SRTP, SRTP media encryption support.
   * ZRTP, ZRTP media encryption support.
   * WebRTC AEC, WebRTC echo canceller support.
   * WASAPI, Windows Audio Session API (WASAPI) sound card support.
   * GSM, GSM audio encoding/decoding support.
   * OPUS, OPUS audio encoding/decoding support.
   * Speex, Speex audio encoding/decoding support.
   * BV16, BroadVoice 16 audio encoding/decoding support.
   * Video, Ability to capture and display video.
   * jpeg, JPEG support with libjpeg-turbo.
   * MKV, MKV playing and recording support.
   * VPX, VPX (VP8) video encoding/decoding support.
  
  -- Disabled features:
   * Embedded OpenH264, Embed the openh264 library instead of downloading it from Cisco.
   * Theora, Theora video encoding/decoding support.
   * Static only, Enable compilation of libraries in static mode.
   * Packaging, Enable packaging
   * Source packaging, Enable source packaging
   * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
   * Doc, Enable documentation generation with Doxygen and Sphinx
   * unmaintained, Allow inclusion of unmaintained code in the build.
   * Soci mysql, Enable mysql support of SOCI
   * Sanitizer, Enable Clang sanitizer
   * GTK UI, Enable the GTK user interface of Linphone.
   * Swift wrapper, Build the Swift wrapper from Liblinphone.
   * Jazzy doc, Build the Swift doc from Liblinphone.
   * Java wrapper, Build the Java wrapper from Liblinphone.
   * LIME, Enable Linphone IM Encryption support in  Liblinphone.
   * NLS, Enable internationalization of Linphone and Liblinphone.
   * Update Check, Enable update check.
   * Polarssl, Crypto stack implementation based on polarssl.
   * Tunnel, Secure tunnel for SIP/RTP (require license).
   * RTP Map always in SDP, Always include rtpmap in SDP.
   * mDNS, Multicast DNS support
   * Non free codecs, Allow inclusion of non-free codecs in the build.
   * WebRTC AECM, WebRTC echo canceller for mobile support.
   * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
   * AMRWB, AMR wide-band audio encoding/decoding support (require license).
   * Codec2, Codec2 audio encoding/decoding support.
   * G729, G.729 audio encoding/decoding support.
   * G729B CNG, G.729 annex B confort noise generation.
   * G726, G.726 audio encoding/decoding support.
   * iLBC, iLBC audio encoding/decoding support.
   * ISAC, ISAC audio encoding/decoding support.
   * Silk, Silk audio encoding/decoding support.
   * WebRTC VAD, WebRTC voice activation detector support.
   * V4L, Ability to capture and display video using libv4l2 .
   * qrcode, QRCode support with zxing.
   * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
   * H263, H263 video encoding/decoding support (require license).
   * H263p, H263+ video encoding/decoding support (require license).
   * MPEG4, MPEG4 video encoding/decoding support (require license).
   * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
   * X264, H.264 video encoding support with the x264 library (require license).
   * AAudio, AAudio Android sound card for Android 8+.
   * Camera2, Android capture filter using Camera2 API for Android 8+
   * PCAP, PCAP support.
  
  -- Configuring done
  -- Generating done
  -- Build files have been written to: D:/linphone-sdk-build/desktop
  Forcing build for 'desktop'
  Performing build step for 'sdk'
  用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
  版权所有(C) Microsoft Corporation。保留所有权利。
  
    Forcing build for 'EP_bcunit'
    Performing build step for 'EP_bcunit'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      bcunit.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bcunit\BCUnit\Sources\RelWithDebInfo\bcunit.dll
    Performing install step for 'EP_bcunit'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      bcunit.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bcunit\BCUnit\Sources\RelWithDebInfo\bcunit.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_bcunit'
    Forcing build for 'EP_decaf'
    Performing build step for 'EP_decaf'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      p25519.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\p25519\p25519.dir\RelWithDebInfo\p25519.lib
      CURVE25519.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\curve25519\CURVE25519.dir\RelWithDebInfo\CURVE25519.lib
      p448.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\p448\p448.dir\RelWithDebInfo\p448.lib
      CURVE448.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\ed448goldilocks\CURVE448.dir\RelWithDebInfo\CURVE448.lib
      decaf.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\RelWithDebInfo\decaf.dll
    Performing install step for 'EP_decaf'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      p25519.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\p25519\p25519.dir\RelWithDebInfo\p25519.lib
      CURVE25519.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\curve25519\CURVE25519.dir\RelWithDebInfo\CURVE25519.lib
      p448.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\p448\p448.dir\RelWithDebInfo\p448.lib
      CURVE448.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\ed448goldilocks\CURVE448.dir\RelWithDebInfo\CURVE448.lib
      decaf.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\decaf\src\RelWithDebInfo\decaf.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_decaf'
    Forcing build for 'EP_mbedtls'
    Performing build step for 'EP_mbedtls'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      mbedcrypto.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\mbedtls\library\RelWithDebInfo\mbedcrypto.lib
      mbedx509.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\mbedtls\library\RelWithDebInfo\mbedx509.lib
      mbedtls.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\mbedtls\library\RelWithDebInfo\mbedtls.lib
    Performing install step for 'EP_mbedtls'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      mbedcrypto.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\mbedtls\library\RelWithDebInfo\mbedcrypto.lib
      mbedx509.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\mbedtls\library\RelWithDebInfo\mbedx509.lib
      mbedtls.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\mbedtls\library\RelWithDebInfo\mbedtls.lib
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_mbedtls'
    Creating directories for 'EP_bctoolbox'
    Building Custom Rule D:/linphone-sdk/cmake-builder/CMakeLists.txt
    No download step for 'EP_bctoolbox'
    No update step for 'EP_bctoolbox'
    No patch step for 'EP_bctoolbox'
    Performing configure step for 'EP_bctoolbox'
    loading initial cache file D:/linphone-sdk-build/WORK/desktop//tmp/EP_bctoolbox/EP_bctoolbox-cache-RelWithDebInfo.cmake
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_bctoolbox/EP_bctoolbox-cache-RelWithDebInfo.cmake:8 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_bctoolbox/EP_bctoolbox-cache-RelWithDebInfo.cmake:13 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_bctoolbox/EP_bctoolbox-cache-RelWithDebInfo.cmake:23 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Selecting Windows SDK version  to target Windows 10.0.18363.
    -- Using mbedTLS
    -- Using Decaf
    -- DTLS SRTP available
    -- Configuring done
    -- Generating done
    -- Build files have been written to: D:/linphone-sdk-build/WORK/desktop/Build/bctoolbox
    Forcing build for 'EP_bctoolbox'
    Performing build step for 'EP_bctoolbox'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      bctoolbox.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bctoolbox\src\RelWithDebInfo\bctoolbox.dll
      bctoolbox-tester.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bctoolbox\src\RelWithDebInfo\bctoolbox-tester.dll
D:\linphone-sdk-build\linphone-sdk\desktop\bin\decaf.dll : fatal error LNK1107: 文件无效或损坏: 无法在 0x308 处读取 [D:\linphone-sdk-build\WORK\desktop\Build\bctoolbox\tester\bctoolbox_tester_exe.vcxproj] [D:\linphone-sdk-build\desktop\EP_bctoolbox.vcxproj]
    Forcing build for 'EP_zlib'
    Performing build step for 'EP_zlib'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      zlibstatic.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\zlib\RelWithDebInfo\zlib.lib
    Performing install step for 'EP_zlib'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      zlibstatic.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\zlib\RelWithDebInfo\zlib.lib
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_zlib'
    Forcing build for 'EP_bv16'
    Performing build step for 'EP_bv16'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      bv16.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bv16\RelWithDebInfo\bv16.dll
    Performing install step for 'EP_bv16'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      bv16.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\bv16\RelWithDebInfo\bv16.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_bv16'
    Forcing build for 'EP_sqlite3'
    Performing build step for 'EP_sqlite3'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      sqlite3.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\sqlite3\RelWithDebInfo\sqlite3.dll
    Performing install step for 'EP_sqlite3'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      sqlite3.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\sqlite3\RelWithDebInfo\sqlite3.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_sqlite3'
    Forcing build for 'EP_xml2'
    Performing build step for 'EP_xml2'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      xml2.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\xml2\RelWithDebInfo\xml2.dll
    Performing install step for 'EP_xml2'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      xml2.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\xml2\RelWithDebInfo\xml2.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_xml2'
    Forcing build for 'EP_gsm'
    Performing build step for 'EP_gsm'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      gsm.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\gsm\RelWithDebInfo\gsm.dll
    Performing install step for 'EP_gsm'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      gsm.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\gsm\RelWithDebInfo\gsm.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_gsm'
    Forcing build for 'EP_xerces'
    Performing build step for 'EP_xerces'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      xerces-c.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\xerces\src\RelWithDebInfo\xerces-c.dll
    Performing install step for 'EP_xerces'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      xerces-c.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\xerces\src\RelWithDebInfo\xerces-c.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_xerces'
    Performing configure step for 'EP_libxsd'
    loading initial cache file D:/linphone-sdk-build/WORK/desktop//tmp/EP_libxsd/EP_libxsd-cache-RelWithDebInfo.cmake
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_libxsd/EP_libxsd-cache-RelWithDebInfo.cmake:8 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_libxsd/EP_libxsd-cache-RelWithDebInfo.cmake:13 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_libxsd/EP_libxsd-cache-RelWithDebInfo.cmake:23 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Selecting Windows SDK version  to target Windows 10.0.18363.
    -- Configuring done
    -- Generating done
    -- Build files have been written to: D:/linphone-sdk-build/WORK/desktop/Build/libxsd
    Forcing build for 'EP_libxsd'
    Performing build step for 'EP_libxsd'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
    Performing install step for 'EP_libxsd'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_libxsd'
    Performing configure step for 'EP_soci'
    loading initial cache file D:/linphone-sdk-build/WORK/desktop//tmp/EP_soci/EP_soci-cache-RelWithDebInfo.cmake
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_soci/EP_soci-cache-RelWithDebInfo.cmake:8 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_soci/EP_soci-cache-RelWithDebInfo.cmake:13 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning (dev) at D:/linphone-sdk-build/WORK/desktop/tmp/EP_soci/EP_soci-cache-RelWithDebInfo.cmake:23 (set):
      implicitly converting 'LIST' to 'STRING' type.
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Selecting Windows SDK version  to target Windows 10.0.18363.
    -- Configuring SOCI: 
    -- SOCI_VERSION                             = 4.0.0 
    -- SOCI_ABI_VERSION                         = 4_0 
    -- SOCI_SHARED                              = YES 
    -- SOCI_STATIC                              = NO 
    -- SOCI_FRAMEWORK                           =  
    -- SOCI_TESTS                               = NO 
    -- SOCI_ASAN                                = OFF 
    -- SOCI_CXX_C11                             =  
    -- LIB_SUFFIX                               =  
    -- Looking for SOCI dependencies: 
    -- CMAKE_THREAD_LIBS_INIT                   =  
    -- MySQL: disabled, since WITH_MYSQL=OFF 
    -- ODBC: disabled, since WITH_ODBC=OFF 
    -- Oracle: disabled, since WITH_ORACLE=OFF 
    -- PostgreSQL: disabled, since WITH_POSTGRESQL=OFF 
    -- SQLite3: 
    -- SQLITE3_INCLUDE_DIR                      = D:/linphone-sdk-build/linphone-sdk/desktop/include 
    -- SQLITE3_LIBRARIES                        = D:/linphone-sdk-build/linphone-sdk/desktop/lib/sqlite3.lib 
    -- Firebird: disabled, since WITH_FIREBIRD=OFF 
    -- DB2: disabled, since WITH_DB2=OFF 
    -- Configuring SOCI core library: 
    -- SOCI_CORE_TARGET                         = soci_core 
    -- SOCI_CORE_TARGET_OUTPUT_NAME             = soci_core_4_0 
    -- SOCI_CORE_DEPS_LIBS                      =  
    -- SOCI_CORE_INCLUDE_DIRS                   = D:/linphone-sdk-build/WORK/desktop/Build/soci D:/linphone-sdk/external/soci/include D:/linphone-sdk-build/WORK/desktop/Build/soci/include D:/linphone-sdk/external/soci/include/private D:/linphone-sdk-build/WORK/desktop/Build/soci/src/core 
    -- WITH_BOOST                               =  
    -- COMPILE_DEFINITIONS                      = _CRT_SECURE_NO_DEPRECATE _CRT_SECURE_NO_WARNINGS _CRT_NONSTDC_NO_WARNING _SCL_SECURE_NO_WARNINGS SOCI_ABI_VERSION="4_0" SOCI_LIB_PREFIX="soci_" SOCI_LIB_SUFFIX=".dll" SOCI_DEBUG_POSTFIX="" 
    -- 
    -- Configuring SOCI backend libraries: 
    -- SQLite3 - SOCI backend for SQLite 3 
    -- SOCI_SQLITE3                             = ON 
    -- SOCI_SQLITE3_TARGET                      = soci_sqlite3 
    -- SOCI_SQLITE3_OUTPUT_NAME                 = soci_sqlite3_4_0 
    -- SOCI_SQLITE3_COMPILE_DEFINITIONS         = _CRT_SECURE_NO_DEPRECATE _CRT_SECURE_NO_WARNINGS _CRT_NONSTDC_NO_WARNING _SCL_SECURE_NO_WARNINGS SOCI_ABI_VERSION="4_0" 
    -- SOCI_SQLITE3_INCLUDE_DIRECTORIES         = D:/linphone-sdk-build/WORK/desktop/Build/soci D:/linphone-sdk/external/soci/include D:/linphone-sdk-build/WORK/desktop/Build/soci/include D:/linphone-sdk/external/soci/include/private D:/linphone-sdk/external/soci/include/private D:/linphone-sdk-build/linphone-sdk/desktop/include 
    -- 
    -- 
    -- Package file name is SOCI-4.0.0
    -- Configuring done
    -- Generating done
    -- Build files have been written to: D:/linphone-sdk-build/WORK/desktop/Build/soci
    Forcing build for 'EP_soci'
    Performing build step for 'EP_soci'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      soci_core.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\soci\bin\RelWithDebInfo\soci_core_4_0.dll
      soci_sqlite3.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\soci\bin\RelWithDebInfo\soci_sqlite3_4_0.dll
    Performing install step for 'EP_soci'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      soci_core.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\soci\bin\RelWithDebInfo\soci_core_4_0.dll
      soci_sqlite3.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\soci\bin\RelWithDebInfo\soci_sqlite3_4_0.dll
      -- Install configuration: "RelWithDebInfo"
      -- Installing: D:/linphone-sdk-build/linphone-sdk/desktop/cmake/SOCI-relwithdebinfo.cmake
    Completed 'EP_soci'
    Forcing build for 'EP_matroska2'
    Performing build step for 'EP_matroska2'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      corec-objects.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\matroska2\corec\corec\corec-objects.dir\RelWithDebInfo\corec-objects.lib
      ebml2-objects.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\matroska2\libebml2\ebml2-objects.dir\RelWithDebInfo\ebml2-objects.lib
      bcmatroska2.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\matroska2\libmatroska2\RelWithDebInfo\bcmatroska2.lib
    Performing install step for 'EP_matroska2'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      corec-objects.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\matroska2\corec\corec\corec-objects.dir\RelWithDebInfo\corec-objects.lib
      ebml2-objects.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\matroska2\libebml2\ebml2-objects.dir\RelWithDebInfo\ebml2-objects.lib
      bcmatroska2.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\matroska2\libmatroska2\RelWithDebInfo\bcmatroska2.lib
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_matroska2'
    Forcing build for 'EP_opus'
    Performing build step for 'EP_opus'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      opus.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\opus\RelWithDebInfo\opus.dll
    Performing install step for 'EP_opus'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      opus.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\opus\RelWithDebInfo\opus.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_opus'
    Forcing build for 'EP_speex'
    Performing build step for 'EP_speex'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      speex.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\speex\libspeex\RelWithDebInfo\speex.dll
      speexdsp.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\speex\libspeex\RelWithDebInfo\speexdsp.dll
    Performing install step for 'EP_speex'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      speex.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\speex\libspeex\RelWithDebInfo\speex.dll
      speexdsp.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\speex\libspeex\RelWithDebInfo\speexdsp.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_speex'
    Forcing build for 'EP_srtp'
    Performing build step for 'EP_srtp'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      srtp.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\srtp\RelWithDebInfo\srtp2.dll
    Performing install step for 'EP_srtp'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      srtp.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\srtp\RelWithDebInfo\srtp2.dll
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_srtp'
    Forcing build for 'EP_turbojpeg'
    Performing build step for 'EP_turbojpeg'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      turbojpeg.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\turbojpeg\RelWithDebInfo\turbojpeg.lib
    Performing install step for 'EP_turbojpeg'
    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.9.21+g9802d43bc3
    版权所有(C) Microsoft Corporation。保留所有权利。
    
      turbojpeg.vcxproj -> D:\linphone-sdk-build\WORK\desktop\Build\turbojpeg\RelWithDebInfo\turbojpeg.lib
      -- Install configuration: "RelWithDebInfo"
    Completed 'EP_turbojpeg'
    Forcing build for 'EP_vpx'
    Performing build step for 'EP_vpx'
    Performing install step for 'EP_vpx'
    Completed 'EP_vpx'

**Comment by Denny0503** [comment]
I configure the projects just as default by the program cmake-gui, and then build the project.

**Comment by KyronNextLevel** [comment]
Hello. I tried to build in release mode from master branch without issues.
I have the same options enabled as you.
Commands launched for release :
`cmake .. -G "Visual Studio 15 2017" -DLINPHONESDK_PLATFORM=Desktop -DENABLE_CSHARP_WRAPPER=YES -DENABLE_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=Release`
`cmake --build . --target sdk --config Release -- /maxcpucount /nodeReuse:true /p:TrackFileAccess=false`

Commands launched for RelWithDebInfo :
`cmake .. -G "Visual Studio 15 2017" -DLINPHONESDK_PLATFORM=Desktop -DENABLE_CSHARP_WRAPPER=YES -DENABLE_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo`
`cmake --build . --target sdk --config RelWithDebInfo -- /maxcpucount /nodeReuse:true /p:TrackFileAccess=false`

I used win 10 sdk 17763 to target win 10 18363.

Did you strictly follow the SDK readme for Windows build (especially concerning dependencies)?
If you try to build with the commands I gave you, is it working for you?

If not, could you please try to re-clone entirely the SDK (with --recursive) and re-build?

Regards

**Comment by Denny0503** [comment]
That is ok，thank you! I just forget  install the "Windows Universal Platform development"。
And then I compile the project with the commands you gave successfully。
