### ISSUE TITLE
Query related to local video stream customisation

### ISSUE THREAD

**Issue by RonitEcosmobian** [BelledonneCommunications/linphone-sdk#352]
Hi

I want to provide customisation of the video stream to be previewed and send as the remote stream. Customisation is for adding effects like blur in the background like a portrait effect of camera to show an object or face and the background is blur.

I'm using the Linphone SDK V5.2.110.

It's kind on an urgent basis, would highly appreciate your quick reply.

Thanks

**Comment by Viish** [comment]
Hi,

You can do it in mediastreamer2 project, it contains the filters for decoding video & displaying it, you would need to create a new filter in the chain between the two to do the modification.
As we haven't done it ourselves I can't help you more, sorry.

Cheers,

**Comment by RonitEcosmobian** [comment]
Hi,

Could you give us in brief the steps required and files to be modified in order to implement such filters or can you provide recent code or architecture related documentation?

**Comment by Viish** [comment]
@RonitEcosmobian,

Take a look at https://github.com/BelledonneCommunications/mediastreamer2/blob/master/src/voip/audiostream.c, it's that fille that handles all filters.
Sorry but I can't help much more, I don't have much expertise on that part of the project.

Good luck.
