### ISSUE TITLE
[Bug]: Errors while cloning linphone-sdk repo

### ISSUE THREAD

**Issue by glush** [BelledonneCommunications/linphone-sdk#356]
### Context

I use the linphone-sdk in the Linphone-desktop Linux version with sip.linphone.org for my company. I want to do a simple call between an Android application and FreeSwitch server.

### General information

- Device: Windows 11 desktop + WSL2 Ubuntu 18 image
- OS: Windows 11 + WSL
- Version of the App:
- Version of the SDK: `bc-dev-android-r25b:20230706_add_deps_for_av1`

### Expected behaviour

I'm cloning  submodules into linphone-sdk repo with

git submodule update --init --recursive

expecting all submodules copied locally. But for some modules i'd receive errors cloning:

fatal: repository 'https://github.com/BelledonneCommunications/msoboe.git/' not found
fatal: clone of 'https://github.com/BelledonneCommunications/msoboe.git' into submodule path '/home/glush/bc/linphone-sdk/msoboe' failed
...
fatal: repository 'https://github.com/BelledonneCommunications/postquantumcryptoengine.git/' not found
fatal: clone of 'https://github.com/BelledonneCommunications/postquantumcryptoengine.git' into submodule path '/home/glush/bc/linphone-sdk/postquantumcryptoengine' failed
...
fatal: repository 'https://github.com/BelledonneCommunications/msoboe.git/' not found
fatal: clone of 'https://github.com/BelledonneCommunications/msoboe.git' into submodule path '/home/glush/bc/linphone-sdk/msoboe' failed

### To Reproduce

1. mkdir bc
2. cd bc
3.  git clone https://github.com/BelledonneCommunications/linphone-sdk/
4. cd linphone-sdk
5. git submodule update --init --recursive

### Additional context

Also I did not found this repo's at https://github.com/orgs/BelledonneCommunications/repositories

**Comment by glush** [comment]
git clone --recurse-submodules -j8 https://github.com/BelledonneCommunications/linphone-sdk/

Just stucked at msoboe module.

**Comment by glush** [comment]
git clone --recurse-submodules -j8 https://github.com/BelledonneCommunications/linphone-sdk/

Just stucked at msoboe module.

**Comment by Viish** [comment]
Hi,

Try cloning from our gitlab instead: https://gitlab.linphone.org/BC/public/linphone-sdk.git

Cheers,

**Comment by glush** [comment]
It works. Thnx.
