### ISSUE TITLE
[Bug]:Dual card dual standby mobile phone, mobile traffic switch between. Occasionally, no invite message is sent after the network switchover, resulting in abnormal call termination.

### ISSUE THREAD

**Issue by jysssssssssssssss** [BelledonneCommunications/linphone-sdk#358]
### Context

use sdk linphone-sdk-android-5.2.110.aar，Dual card dual standby mobile phone, mobile traffic switch between. Occasionally, no invite message is sent after the network switchover, resulting in abnormal call termination.

### General information

- Device: nova 7 Pro 5G
- OS: Harmony OS 4.0
- Version of the SDK:linphone-sdk-android-5.2.110

### Expected behaviour

Dual card dual standby mobile phone, mobile traffic switch between, the call can continue, will not hang up abnormally

### To Reproduce

Switch mobile traffic multiple times after starting a call. no send "invite"  sip message,the call is finied for a moment.
### Additional context

[log.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/13554736/log.txt)

### SDK logs URL

https://github.com/BelledonneCommunications/linphone-sdk/files/13554736/log.txt

**Comment by Viish** [comment]
Hi @jysssssssssssssss,

Please attach full debug logs from SDK.

Cheers,

**Comment by jysssssssssssssss** [comment]
[fulllog.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/13558297/fulllog.txt)
Thanks.

**Comment by Viish** [comment]
Thanks @jysssssssssssssss.

@AndreaGianarda can you take a look at it please?
In the logs at `2023-12-05 18:00:44.243` network is reachable again but no RE-INVITE is sent.

**Comment by jysssssssssssssss** [comment]
@Viish 
Thanks。
this is the bug. how to sent RE-INVITE  at  this time again,has any method to config?

**Comment by jysssssssssssssss** [comment]
Before invite I have call setCapabilityNegotiationReinviteEnabled(true),  setCapabilityNegotiationsEnabled(true) in CallParams,  when receive 'onNetworkReachable' callback, I call 'update' method in current call. but is not work.
