### ISSUE TITLE
Intermittent Crash on Call Termination in Android SDK 4.5.26

### ISSUE THREAD

**Issue by q5580237** [BelledonneCommunications/linphone-sdk#363]
### Context

I am experiencing an intermittent crash (about 50% occurrence rate) in the Linphone Android SDK version 4.5.26 on Android 9 devices. The crash occurs when attempting to terminate a call using `core.terminate()`. This issue is observed across various Android 9 devices. The expected behavior is for the call to terminate normally, but instead, the app crashes.

### General information

- Device: All Android 9 devices
- OS: Android  9
- Version of the SDK: 4.5.26

### Expected behaviour

The call should terminate normally without crashing the app.

### To Reproduce

1. Add a hang-up listener to the app.
2. Make a call.
3. After the call is successfully established, use `core.terminate()` to hang up.
4. Observe that the app crashes approximately 50% of the time when this process is followed.

### Additional context

![crash_1](https://github.com/BelledonneCommunications/linphone-sdk/assets/30224408/8da88af2-1fac-45bf-9a0a-4a212439bea2)

**Comment by Viish** [comment]
Hi,

Sorry but we only support the current release of our SDK which is currently 5.2.X (5.3.0 will be out soon).
In your case 4.5.26 is a very old releases (many years old) so we won't help you.
Please update to latest release and if you still reproduce, re-open this issue.

Cheers,
