### ISSUE TITLE
[Bug]: Can't compile jsoncpp with Xcode 15

### ISSUE THREAD

**Issue by FedorKiselev76** [BelledonneCommunications/linphone-sdk#367]
### Context

I am trying to compile SDK.

### General information

- Device: Mac os
- OS: Sonoma 14.2
- Version of the SDK: 5.2

### Expected behaviour

Since Xcode 15 and with new cmake jsoncpp can't be compiled for arm64 but no problems with ios-arm64-simulator and ios-x86_64 .

cmake version 3.28.0

Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

HEAD -> 5.2, tag: 5.2.112, origin/release/5.2

/opt/homebrew/Cellar/cmake/3.28.0/bin/cmake -S/usr/local/src/linphone-sdk-orig/external/jsoncpp -B/usr/local/src/linphone-sdk-orig/build_ios/WORK/ios-arm64/Build/jsoncp
p
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk
-- Using sdk version: 17.2
-- JsonCpp Version: 1.9.4
CMake Error at src/lib_json/CMakeLists.txt:140 (target_compile_features):
  target_compile_features no known features for CXX compiler

  ""

  version .

CMake Error at src/lib_json/CMakeLists.txt:176 (target_compile_features):
  target_compile_features no known features for CXX compiler

  ""

  version .

-- Configuring incomplete, errors occurred!

### To Reproduce

cmake --build . --parallel 5

**Comment by weidongliu** [comment]
I encountered this problem using Xcode 15.2 as well. Did you resolve it? @FedorKiselev76

**Comment by AndreaGianarda** [comment]
Hi,

I confirm that a workaround is to use Ninja instead of Xcode. Nonetheless, we are working to resolving the issue as quickly as possible.

Thanks for your understanding,

Andrea

**Comment by smorlat** [comment]
Hi,

When using --preset ios-sdk, please use Ninja or "Unix Makefiles" cmake generator.
Indeed, the multi-architecture build does not work with XCode generator due to XCode 15 internal changes.

Best regards,

Simon
