### ISSUE TITLE
[Bug]: Installing linphone sdk for iOS keeps failing

### ISSUE THREAD

**Issue by ogrodowski-tomasz** [BelledonneCommunications/linphone-sdk#385]
### Context

I want to build linphone-sdk from source code using cmake because i need G729 codec enabled.
i perform following commands:
- cloned gitlab repo with all submodules
- cmake --preset=ios-sdk -G Xcode -B build-ios -DLINPHONESDK_IOS_ARCHS="arm64,x86_64" -DENABLE_AAUDIO=ON -DENABLE_G729=ON -DENABLE_GPL_THIRD_PARTIES=ON
and then:
cmake --build build-ios --parallel 8

And after a couple of minutes of building i get a failure message:
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Generate\ mediastreamer2/src/CMakeFiles/mediastreamer2-voipdescs-header <path>/linphone-sdk/build-ios/ios-arm64-simulator/build/linphone-sdk.build/Release-iphonesimulator/mediastreamer2-voipdescs-header.build/Script-24C2FE84F422F3732DA25072.sh (in target 'mediastreamer2-voipdescs-header' from project 'linphone-sdk')
(1 failure)
Command PhaseScriptExecution failed with a nonzero exit code

warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'gen-frameworks' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/gen-frameworks' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'gen-frameworks' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ALL_BUILD' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'sdk' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/sdk' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'sdk' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ios-arm64-simulator' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/ios-arm64-simulator' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-arm64-simulator' from project 'linphone-sdk')
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ios-arm64' from project 'linphone-sdk')
note: Run script build phase 'Generate CMakeFiles/ios-arm64' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ios-arm64' from project 'linphone-sdk')
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Generate\ CMakeFiles/ios-arm64-simulator <path>/linphone-sdk/build-ios/build/linphone-sdk.build/Release-iphonesimulator/ios-arm64-simulator.build/Script-3FC75B60E1E4EE6A0B5D2688.sh (in target 'ios-arm64-simulator' from project 'linphone-sdk')
(1 failure)

### General information

Tried to build it using both Xcode or Ninja. Both failed. Without parallel option it still fails.
I am using mac with os Ventura 13.5 (with Intel chip, not Apple Silicon), Xcode 15.2

### Expected behaviour

Build should pass successfully

### To Reproduce

Use commands i mentioned earlier

**Comment by HPR10** [comment]
same problem here, I have build in xcode 14 and in xcode 15 it fails due to syntax error in the code

**Comment by ogrodowski-tomasz** [comment]
I managed to install this SDK. The problem for me was that I had a "space" in the installation path. As a result, one of the processes ended in failure and everything else fell apart. Maybe it will help...
