### ISSUE TITLE
[Bug]: Build Error for Android in Ubuntu 22.04

### ISSUE THREAD

**Issue by raposeidon** [BelledonneCommunications/linphone-sdk#398]
### Context

**Error building SDK for Android.
I added an amr codec build, but I get an error.
If don't add an option to the amr codec, there's no build error.**

errorcode is

```
CMake Error at cmake/ExternalDependencies.cmake:1145 (add_dependencies):
  The dependency target "opencore-amr" of target "sdk" does not exist.
Call Stack (most recent call first):
  cmake/ExternalDependencies.cmake:1147 (add_opencore_amr)
  CMakeLists.txt:108 (include)


CMake Error at cmake/ExternalDependencies.cmake:1383 (add_dependencies):
  The dependency target "vo_amrwbenc" of target "sdk" does not exist.
Call Stack (most recent call first):
  cmake/ExternalDependencies.cmake:1385 (add_vo_amrwbenc)
  CMakeLists.txt:108 (include)
```

_The same error occurs with the openh264 codec._

### General information

- OS: ubuntu 22.04
- Version of the SDK: master branch

### Expected behaviour

clean build.

### To Reproduce

1. mkdir build
2. cd build
3. cmake .. --preset android-arm64 -DLINPHONESDK_BUILD_TYPE=Android
4. make

### Additional context

my cmake preset is bellow:
      "name": "android-common",
      "inherits": "default",
      "hidden": true,
      "generator": "Unix Makefiles",
      "cacheVariables": {
        "BUILD_BCG729_SHARED_LIBS": "OFF",
        "BUILD_BCUNIT_SHARED_LIBS": "OFF",
        "BUILD_BELCARD_SHARED_LIBS": "OFF",
        "BUILD_BELLESIP_SHARED_LIBS": "OFF",
        "BUILD_BELR_SHARED_LIBS": "OFF",
        "BUILD_BV16_SHARED_LIBS": "OFF",
        "BUILD_BZRTP_SHARED_LIBS": "OFF",
        "BUILD_DECAF_SHARED_LIBS": "OFF",
        "BUILD_GSM_SHARED_LIBS": "OFF",
        "BUILD_LIBXML2_SHARED_LIBS": "OFF",
        "BUILD_LIBYUV_SHARED_LIBS": "OFF",
        "BUILD_LIME_SHARED_LIBS": "OFF",
        "BUILD_MBEDTLS_SHARED_LIBS": "OFF",
        "BUILD_MBEDTLS_WITH_FATAL_WARNINGS": "OFF",
        "BUILD_OPENLDAP_SHARED_LIBS": "OFF",
        "BUILD_OPUS_SHARED_LIBS": "OFF",
        "BUILD_PQCRYPTO_SHARED_LIBS": "OFF",
        "BUILD_SOCI_SHARED_LIBS": "OFF",
        "BUILD_SPEEX_SHARED_LIBS": "OFF",
        "BUILD_SQLITE3_SHARED_LIBS": "OFF",
        "BUILD_XERCESC_SHARED_LIBS": "OFF",
        "BUILD_ZLIB": "OFF",
        "CMAKE_BUILD_TYPE": "RelWithDebInfo",
        "ENABLE_ANDROIDSND": "ON",
        "ENABLE_CXX_WRAPPER": "OFF",
        "ENABLE_DAEMON": "OFF",
        "ENABLE_FLEXIAPI": "ON",
        "ENABLE_FLOAT_API": "OFF",
        "ENABLE_FIXED_POINT": "ON",
        "ENABLE_ISAC": "OFF",
        "ENABLE_JAVA_WRAPPER": "ON",
        "ENABLE_JNI": "OFF",
        "ENABLE_LDAP": "ON",
        "ENABLE_AAUDIO": "ON",
        "ENABLE_OBOE": "OFF",
        "ENABLE_RELATIVE_PREFIX": "ON",
        "ENABLE_SCREENSHARING": "OFF",
        "ENABLE_STRICT": "OFF",
        "ENABLE_TOOLS": "OFF",
        "ENABLE_UNIT_TESTS": "OFF",
        "ENABLE_TESTS_COMPONENT": "OFF",
        "ENABLE_VCARD": "OFF",
        "ENABLE_QRCODE": "OFF",
        "ENABLE_WEBRTC_AECM": "ON",
        "ENABLE_ADVANCED_IM": "OFF",
        "ENABLE_DB_STORAGE": "OFF",
        "ENABLE_LIME_X3DH": "OFF",
        "ENABLE_JSONCPP": "OFF",
        "ENABLE_GSM": "OFF",
        "ENABLE_BV16": "OFF",
        "ENABLE_G729": "OFF",
        "ENABLE_VPX": "OFF",
        "ENABLE_THEORA": "OFF",
        "ENABLE_ZRTP": "OFF",
        "ENABLE_AMRNB": "ON",
        "ENABLE_AMRWB": "ON",
        "BUILD_VO_AMRWBENC_SHARED_LIBS": "OFF",
        "BUILD_VO_OPENCORE_AMR_SHARED_LIBS": "OFF",
        "ENABLE_NON_FREE_FEATURES": "ON",
        "LINPHONESDK_PLATFORM": "Android"
    }

**Comment by Viish** [comment]
Hi,

Indeed the AMR build seems broken.
We'll take a look at it, thanks!

Cheers,

**Comment by Viish** [comment]
Hi,

Fixed was merged into master branch.

Cheers,

**Comment by raposeidon** [comment]
Hi,

Thank you for responding quickly.

Cheers.
