### ISSUE TITLE
Inconsistent behaviour in Linphone 4.x regarding retrying INVITEs which get a 302 response 

### ISSUE THREAD

**Issue by krv372** [BelledonneCommunications/linphone-sdk#4]
In Linphone 3.3.0 when you send an INVITE message and server responds with 302, Linphone automatically retries the request with a new INVITE to the server that is specified in Contact header field of 302. It sends a completely new INVITE with no Proxy-Authorization.

In Linphone 4.3. when Linphone retries the request (to a 302) it sends a Proxy-Authorization header which belongs to the previous INVITE and contains address and information of that server. This causes the server to respond with a 403 Not Relaying!

**Comment by krv372** [comment]
:(

**Comment by smorlat** [comment]
Hi,

Thank you for your report.
I created this merge request that should fix this issue:
https://gitlab.linphone.org/BC/public/linphone-sdk/merge_requests/697

After validation it will go to release/4.3 branch.

Best regards,

Simon

**Comment by krv372** [comment]
hi , Thank you for your response. 
I check and run your change codes. the Proxy-Authorization header  was removed but i have another problem.
in linphone 4.3 after received 302 message and server send second ip address, when Linphone send Redirected Invite message it send to previous server .

**example:**
received [432] new bytes from [TCP://91.200.50.152:14777]:
SIP/2.0 302 Moved Temporarily!
 ...
 Contact: <sip:..@91.200.50.154:14777;transport=tcp>
 ...
--------------------
 message sent to [TCP://**91.200.50.152**:14777], size: [1442] bytes:
INVITE sip:...@**91.200.50.154**:14777;transport=tcp SIP/2.0
....
 From: "..." <sip: .... @91.200.50.152>...
 To: "..." <sip:.... @91.200.50.154>
......
--------------------

**Comment by smorlat** [comment]
Merged in release/4.3 branch.
