### ISSUE TITLE
Issue receiving incoming Chat Messages

### ISSUE THREAD

**Issue by brianomchugh** [BelledonneCommunications/linphone-sdk#400]
I am following the BasicChat [tutorial](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/ios/swift/5-BasicChat). I can create a ChatRoom and send messages to it, but when I receive an incoming message linphone-sdk automatically creates a ChatRoom using the local IP instead of the proxy IP:
```
Unable to find chat room in RAM: ConferenceId(peer=sip:remoteuser@18.9.8.7,local=sip:localuser@192.1.2.3:53241;transport=tcp).
```

When really I want it to just use the proxy IP since  mCore.defaultAccount?.params?.identityAddress = "sip:localuser@18.9.8.7". Like this:
```
ConferenceId(peer=sip:remoteuser@18.9.8.7,local=sip:localuser@18.9.8.7).
```

I know I am missing something stupid here.... how can I make it work?

**Comment by DhivyaSureshkumar1** [comment]
Did you find what mistake you did. Because I AM FACING SAME PROBLEM.

**Comment by brianomchugh** [comment]
> Did you find what mistake you did. Because I AM FACING SAME PROBLEM.

No, the SDK works this way by design (so it is not a bug/mistake). You will either need to modify linphone SDK to work with your SIP Server, or set up your SIP server to send the right IP in the SIP headers. In my case I was trying to use FreeSwitch, but it was not compatible with Linphone SDK (for chat at least)
