### ISSUE TITLE
[Bug]: Can't compile linphone-sdk with tunnel support

### ISSUE THREAD

**Issue by Flixnore** [BelledonneCommunications/linphone-sdk#405]
### Context

I want to compile the linphone sdk with tunnel support enabled.

### General information

- Device: Macbook Pro
- OS: Ventura 13.6
- Version of the App:
- Version of the SDK: Building off of master

### Expected behaviour

I expect to be able to use the -DENABLE_TUNNEL flag successfully and compile the sdk with tunnel support.

### To Reproduce

1. Clone the sdk and install dependencies
2. Configure the sdk using
```
cmake --preset=ios-arm64 -G Xcode -B build -DLINPHONESDK_IOS_ARCHS="arm64" -DENABLE_TUNNEL=ON
```
3. Configuration fails due to being unable to clone repo `git@gitlab.linphone.org:BC/private/tunnel.git`
See Error:
```
...
git@gitlab.linphone.org: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.
...
CMake Error at cmake/BCProjects.cmake:206 (add_subdirectory):
  add_subdirectory given source "tunnel" which is not an existing directory.
Call Stack (most recent call first):
  cmake/BCProjects.cmake:209 (add_tunnel)
  CMakeLists.txt:113 (include)
...
```

### Additional context

This fails because the tunnel repository is private.

CMakeLists.txt ENABLE_TUNNEL flag includes `cmake/TunnelClone.cmake`. This is the file which clones the repo. I don't have access to that private repository, thus I can't clone or enable tunnel support in the linphone sdk.t

**Comment by Viish** [comment]
Hi @Flixnore,

Indeed our tunnel implementation isn't open-source, that's why you can't clone the project.

I recommend you to contact the company I work for (Belledonne communications) using the contact form on our website https://linphone.org/contact#content-bottom3 to request a quotation if you're interested.

Cheers,
