### ISSUE TITLE
Crashes at android app

### ISSUE THREAD

**Issue by qw1nzup** [BelledonneCommunications/linphone-sdk#41]
I attached 3 stack traces from firebase crashlytics
[lp_crash_3.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/4935304/lp_crash_3.txt)
[lp_crash_2.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/4935305/lp_crash_2.txt)
[lp_crash_1.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/4935306/lp_crash_1.txt)

Could you check and give some workaround?

**Comment by Viish** [comment]
The file you attached are worthless.
I need symbolized stack traces and if possible with matching SDK logs.
