### ISSUE TITLE
How to determine the online status of my account

### ISSUE THREAD

**Issue by happyfsyy** [BelledonneCommunications/linphone-sdk#414]
Hello, how do I know if my account is online?

When my program launches, I will know if my registration fails or if it succeeds.

However, if the sip server suddenly loses power while the program is running, my account should be offline at this time, how do I get this notification? I can't register my account with sip server every 30 seconds, that would be stupid.

I wonder if I can use Linphone's heartbeat mechanism to know the status of the sip server based on its feedback?

Thank you in advance

**Comment by Viish** [comment]
I've transferred the issue as linphone-android is only for issues related to the app itself, not our SDK APIs.
