### ISSUE TITLE
how to use Linphone-sdk to create a chatroom ?

### ISSUE THREAD

**Issue by avalanche15** [BelledonneCommunications/linphone-sdk#418]
@Viish Hello,Excuse me。 I have some questions have to ask you. Now I use linphone-sdk and want to send messages directly between the two clients. freeswitch is deployed on my server. SIP/2.0 407 Proxy Authentication Required is displayed, is there something I didn't set?
Or is it the server?

This is the code I wrote to verify that the chat room was created successfully and the message was sent successfully
`    if (!lc) return;
    bctbx_list_t *participantList = nullptr;
    QStringList participants = {"sip:1001@47.92.32.187"};
    for (const QString &participant : participants) {
        LinphoneAddress *addr = linphone_address_new(participant.toUtf8().constData());
        if (addr) {
            participantList = bctbx_list_append(participantList, addr);
        } else {
            // Handle address creation error
            qDebug()<<"addr Cleanup and return";
            // Cleanup and return
            bctbx_list_free_with_data(participantList, (void (*)(void *)) linphone_address_unref);
            return;
        }
    }
    LinphoneChatRoomParams *params = linphone_chat_room_params_new();
    if (!params) {
        // Handle params creation error
        qDebug()<<"params Cleanup and return";
        bctbx_list_free_with_data(participantList, (void (*)(void *)) linphone_address_unref);
        return;
    }

    LinphoneChatRoom *chatRoom = linphone_core_create_chat_room_6(lc, params, nullptr, participantList);
    if (!chatRoom) {
        // Handle chat room creation error
        qDebug()<<"chatRoom Cleanup and return";
        linphone_chat_room_params_unref(params);
        bctbx_list_free_with_data(participantList, (void (*)(void *)) linphone_address_unref);
        return;
    }

    LinphoneChatMessage *message = linphone_chat_room_create_message_from_utf8(chatRoom, "create conference yes");
    if (message) {

        linphone_chat_message_send(message);
        linphone_chat_message_unref(message); // Clean up the message
    }else{

        qDebug()<<"chatRoom Cleanup and return";
    }

    linphone_chat_room_params_unref(params); // Clean up the params
    bctbx_list_free_with_data(participantList, (void (*)(void *)) linphone_address_unref); // Clean up the participant list`

**Comment by Viish** [comment]
Hi @avalanche15,

`407 Proxy Authentication Required` means your Freeswitch requires you to be authenticated.
For that you need to configure an Account (using an AccountParams object) and an AuthInfo.
Take a look at our `AccountLogin` tutorials here: https://gitlab.linphone.org/BC/public/tutorials

Cheers,

**Comment by avalanche15** [comment]
> Hi @avalanche15,
> 
> `407 Proxy Authentication Required` means your Freeswitch requires you to be authenticated. For that you need to configure an Account (using an AccountParams object) and an AuthInfo. Take a look at our `AccountLogin` tutorials here: https://gitlab.linphone.org/BC/public/tutorials
> 
> Cheers,

But I show that you can register and register successfully, and the program can make voice and video calls, which can not rule out the problem of setting?

**Comment by Viish** [comment]
As you're not using Flexisip but Freeswitch, you can only do "Basic" chat rooms (not group ones).
Take a look at our BasicChat tutorials then (not the AdvancedChat or GroupChat ones as they require our conference server).

**Comment by avalanche15** [comment]
> As you're not using Flexisip but Freeswitch, you can only do "Basic" chat rooms (not group ones). Take a look at our BasicChat tutorials then (not the AdvancedChat or GroupChat ones as they require our conference server).

Well, is it because I am using freeswitch and the desktop configuration is based on Flexisip, so I can't use the desktop downloaded from the official website to send messages?
