### ISSUE TITLE
Is there a listener for the first decoded video frame? 

### ISSUE THREAD

**Issue by hotmule** [BelledonneCommunications/linphone-sdk#43]
I want to show progress, if call started, but video is still loading and when the firs frame received resize video to fullscreen

**Comment by Viish** [comment]
You can use https://www.linphone.org/snapshots/docs/liblinphone/multilang/reference/java/linphone_call_listener.html?highlight=video%20frame#linphone.CallListener.onNextVideoFrameDecoded(linphone.Call)
