### ISSUE TITLE
[Bug]: can't compile 5.3.85 when speex is enabled

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-sdk#430]
### Context

Trying to compile latest SDK for testing with iOS

### General information

- Device: Mbook M1
- OS: Sonoma 14.6
- Version of the App:
- Version of the SDK: 5.3.85

### Expected behaviour

On xcode 16 tried to compile local SDK with speex enabled and got error

### To Reproduce

1. Clone SDK repo: 
git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git
git submodule update --recursive --init
mkdir build-ios 
cmake --preset=ios-sdk -G Ninja -B build-ios  -DENABLE_LDAP=NO -DENABLE_AV1=NO -DENABLE_ISAC=NO -DENABLE_BV16=NO -DENABLE_CODEC2=NO
cmake --build build-ios --parallel 16

2. Error when compiling because of speex. When I try again with -DENABLE_SPEEX=NO the SDK compiles fine, but then when making a call in iOS simulator I get a mediastreamer crash...

### Additional context

Using Xcode 16 with iOS SDK 18.0 but when compiling with speex I get an error:

clang: **error: unsupported option '-mno-thumb' for target 'arm64-apple-darwin'**

```
-- Configuring done (28.2s)
-- Generating done (0.4s)
-- Build files have been written to: /Users/peter/Documents/dev/linphone-sdk.5.3/build-ios/ios-arm64
[24/2351] Linking C static library lib/libeverest.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: lib/libeverest.a the table of contents is empty (no object file members in the library define global symbols)
[34/2351] Linking C static library lib/libp256m.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: lib/libp256m.a the table of contents is empty (no object file members in the library define global symbols)
[635/2351] Linking CXX shared library lib/bctoolbox.framework/bctoolbox
ld: warning: -bitcode_bundle is no longer supported and will be ignored
[838/2351] Building C object external/speex/libspeex/CMakeFiles/speex.dir/bits.c.o
FAILED: external/speex/libspeex/CMakeFiles/speex.dir/bits.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --target=arm64-apple-darwin -DHAVE_CONFIG_H -DSHORTCUTS -I/Users/peter/Documents/dev/linphone-sdk.5.3/external/speex/include -I/Users/peter/Documents/dev/linphone-sdk.5.3/build-ios/ios-arm64/external/speex -I/Users/peter/Documents/dev/linphone-sdk.5.3/build-ios/ios-arm64/external/speex/speex -fembed-bitcode -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.0.sdk -miphoneos-version-min=14.6 -fcolor-diagnostics   -marm -w -MD -MT external/speex/libspeex/CMakeFiles/speex.dir/bits.c.o -MF external/speex/libspeex/CMakeFiles/speex.dir/bits.c.o.d -o external/speex/libspeex/CMakeFiles/speex.dir/bits.c.o -c /Users/peter/Documents/dev/linphone-sdk.5.3/external/speex/libspeex/bits.c
clang: error: unsupported option '-mno-thumb' for target 'arm64-apple-darwin'
[848/2351] Building CXX object external/soci/src/core/CMakeFiles/soci_core_static.dir/soci-simple.cpp.o
/Users/peter/Documents/dev/linphone-sdk.5.3/external/soci/src/core/soci-simple.cpp:685:10: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
  685 |     std::sprintf(wrapper.date_formatted, "%d %d %d %d %d %d",
```

**Comment by harut420** [comment]
Hi @petervnv 
try with pull tag 5.3.85.   i think what you are compiling is master and not the 5.3.85 . Then there is no reason to creare the mkdir build-ios.

So i have compiled with following cmq ... on following hw.

-----------------------------------------
sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
MacBookPro17,1
-----------------------------------------
git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git linphone-sdk-5.3.85
cd linphone-sdk-5.3.85
git checkout 5.3.85
git submodule update --init --recursive
cmake --preset=ios-sdk -G Ninja -B build-ios -D YOUR-OPTIONS .........
cmake --build build-ios  

no issue with it. 
  adding: linphone-sdk/apple-darwin/XCFrameworks/linphonetester.xcframework/Info.plist (deflated 52%)
  adding: linphone-sdk/apple-darwin/share/ (stored 0%)
  adding: linphone-sdk/apple-darwin/share/linphonesw/ (stored 0%)
  adding: linphone-sdk/apple-darwin/share/linphonesw/LinphoneWrapper.swift (deflated 84%)

Hope this help

Harut420

**Comment by petervnv** [comment]
Thanks @harut420 

I followed your steps exactly and I always get the same speex related compilation error.
I will try downgrading to xcode 15.4 and iOS SDK 17.5 as I suspect that maybe the cause of the compilation error.

Cheers

**Comment by petervnv** [comment]
Just to add that downgrading Xcode and the iOS fixed it.
Thanks!
