### ISSUE TITLE
Linphone SDK build can not get Camera list on Android10

### ISSUE THREAD

**Issue by zfjia** [BelledonneCommunications/linphone-sdk#45]
Hi, 
    I compiled linphone sdk master version with android r21b, using following cmake configuration: 
    cmake  .. -DLINPHONESDK_PLATFORM=Android
    cmake --build .
    Everything is OK.
    After generate linphone android apk, There is only StaticImage option in CameraList, How can I get Front Camera and Back Camera?
    when i use linphone's maven aar to build linphone android, both cameras are in the list.
    What i missed?

**Comment by Viish** [comment]
Hi,
Did you grant the Camera permission to your app?
Without it we can't get the list of camera devices.
Cheers,

**Comment by zfjia** [comment]
Thanks for your reply.
I grant all privileges for debug app. but there is only static picture options.

**Comment by Viish** [comment]
Please enable debug logs in application (settings->advaned), restart the app and send them to me (send logs button in about page)

**Comment by zfjia** [comment]
hi, Viish
   My app's debug log file has been uploaded, see https://www.linphone.org:444//tmp/5f20d8f238449_dcb1b5ca29c2be2462d6.gz

**Comment by Viish** [comment]
Hi,
Problem is quite simple: you didn't just build using `cmake .. -DLINPHONESDK_PLATFORM=Android`, you did something else.
Result is the Camera2 plugin hasn't been build (it is enabled automatically when platform is set to Android).
Go into your build folder, do a `cmake .. -DENABLE_CAMERA2=ON` and build again and you will be fine.
