### ISSUE TITLE
[Bug]: Unable to record calls

### ISSUE THREAD

**Issue by daerimin** [BelledonneCommunications/linphone-sdk#458]
### Context

I use the SDK with the Swift wrapper in an iOS app that contains VoIP functionality.  I want to record both incoming & outgoing calls to a .wav file in the app's Documents directory.

### General information

- Device: iPhone 15 Simulator
- OS: 18
- Version of the App: 1.0
- Version of the SDK: 5.3.96

### Expected behaviour

I expect a .wav file to appear at the specified location in the app's Documents directory.  It does not appear, and CallParams.isRecording is always false.

### To Reproduce

onCallStateChanged:

```
if state == .Connected {
                let filePath = CallRecordingManager().generateRecordingFilePath(for: call, direction: SIP.shared.currentCall?.dir == .Incoming ? "IN" : "OUT")
                print("filepath = \(filePath)")
                do {
                    if let params = call.params {
                        params.recordFile = filePath
                        try call.update(params: params)
                        call.startRecording()
                        print("Started Recording to \(filePath)")
                    }
                    else {
                        print("Call had no 'Params'")
                    }
                }
                catch {
                    print("Failed Updating Call Params: \(error)")
                }
}
```

Console output:

```
filepath = /Users/[redacted]/Library/Developer/CoreSimulator/Devices/1890D65D-4F2D-4F08-BAC2-DC949679ABAB/data/Containers/Data/Application/28F6CAD1-6952-4088-906E-8C10D85D22B5/Documents/CallRecordings/OUT-STAR664-120624-101628.wav
2024-12-06 15:16:28 +0000: Call State: Updating [Updating call]
Started Recording to /Users/[redacted]/Library/Developer/CoreSimulator/Devices/1890D65D-4F2D-4F08-BAC2-DC949679ABAB/data/Containers/Data/Application/28F6CAD1-6952-4088-906E-8C10D85D22B5/Documents/CallRecordings/OUT-STAR664-120624-101628.wav
            HALSystem.cpp:2170   AudioObjectPropertiesChanged: no such object
           AQMEIO_HAL.cpp:2720  timeout
AudioHardware-mac-imp.cpp:2706   AudioDeviceStop: no device with given ID
iOSSimulatorAudioDevice-32919-1: Abandoning I/O cycle because reconfig pending
2024-12-06 15:16:31 +0000: Call State: StreamsRunning [Streams running]
Recording: false
```

**Comment by Viish** [comment]
Hi @daerimin,

The recordFile must be set before the call is accepted (state == Connected) for recording to work.

Cheers,

**Comment by daerimin** [comment]
I sincerely apologize but I am not able to figure this out without instruction.  Is there any documentation I can read that explains how to do this correctly.  Or, would you mind showing me a quick example of how to handle recording for incoming & outgoing calls?  I don't mean to take up your time, but I have spent days on this with no success.
