### ISSUE TITLE
Build Error for android linphone-sdk

### ISSUE THREAD

**Issue by Mukesh2310** [BelledonneCommunications/linphone-sdk#52]
I am compiling the latest source from git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive

I am using fedora terminal :

**1. Create and go inside a directory where the SDK will be built:**
mkdir build && cd build

**2. Export path**
export ANDROID_HOME=$HOME/Android/Sdk && export PATH=$PATH:$ANDROID_HOME/tools && export PATH=$PATH:/opt/android-sdk/ndk-bundle

**3. Execute CMake to configure the project:**
cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=OFF -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=OFF -DENABLE_GSM=OFF -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF -DENABLE_LIME_X3DH=NO 

**4. Build the SDK:**
cmake --build .

**NDK 19c and NDK 21 both create the same error.**

please help in this regard.... how i have to do it .

Error is below mention :

Scanning dependencies of target sdk
[100%] Generating the SDK (zip file and aar)

> Configure project :
Found plugin: libmsandroidcamera2.so
Found plugin: libmswebrtc.so

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':extractReleaseAnnotations'.
> Could not resolve all task dependencies for configuration ':lintClassPath'.
   > Could not resolve com.android.tools.lint:lint-gradle:27.0.1.
     Required by:
         project :
      > Could not resolve com.android.tools.lint:lint-gradle:27.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.0.1/lint-gradle-27.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/27.0.1/lint-gradle-27.0.1.pom'.
               > Connection reset
      > Could not resolve com.android.tools.lint:lint-gradle:27.0.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/27.0.1/lint-gradle-27.0.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/27.0.1/lint-gradle-27.0.1.pom'.
               > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
CMake Error at /usr/src/mobileapp/mukeshbackup/LatestSDK/linphone-sdk/cmake/Android/GenerateSDK.cmake:49 (message):
  Gradle assemble failed

gmake[2]: *** [CMakeFiles/sdk.dir/build.make:58: CMakeFiles/sdk] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/sdk.dir/all] Error 2
gmake: *** [Makefile:84: all] Error 2

**Comment by Viish** [comment]
Seems to be an issue with your network:
`Connection reset`
