### ISSUE TITLE
linphone lib crashes

### ISSUE THREAD

**Issue by Pokkerolli** [BelledonneCommunications/linphone-sdk#53]
Hi,

We analyzed crashes in our application and as a result revealed a list of crashes that come from this library. Can we expect to fix this crashes?

Regards, Julia

[signal 11 function void.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174396/signal.11.function.void.txt)
[signal 11 getNextFrameSize() const.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174397/signal.11.getNextFrameSize.const.txt)
[signal 11 IndirectReferenceTable.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174398/signal.11.IndirectReferenceTable.txt)
[signal 11 je_free.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174399/signal.11.je_free.txt)
[signal 11 linphone_configure_op_with_proxy.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174400/signal.11.linphone_configure_op_with_proxy.txt)
[signal 11 RefBase RefBase.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174401/signal.11.RefBase.RefBase.txt)
[signal 11 RosAlloc Run.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174402/signal.11.RosAlloc.Run.txt)
[signal 11 sqlite3FindFunction.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174403/signal.11.sqlite3FindFunction.txt)
[signal 11 strcmp.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174404/signal.11.strcmp.txt)
[signal 11 TaskProcessor.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174405/signal.11.TaskProcessor.txt)
[signal 11 Thread.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174406/signal.11.Thread.txt)
[signal 11 tree_iterator.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174407/signal.11.tree_iterator.txt)
[singal 11 RegexMatcher.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174408/singal.11.RegexMatcher.txt)
[single 11 anonlibc_malloc.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174409/single.11.anonlibc_malloc.txt)
[single 11 unknown.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174410/single.11.unknown.txt)
[tgkill.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174411/tgkill.txt)
[UnsatisfiedLinkError.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174412/UnsatisfiedLinkError.txt)
[abort.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174413/abort.txt)
[signal 7 RefBase incStrong.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174414/signal.7.RefBase.incStrong.txt)
[signal 11  arena_run_reg_alloc filter_list.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174415/signal.11.arena_run_reg_alloc.filter_list.txt)
[signal 11 __memcpy.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174416/signal.11.__memcpy.txt)
[signal 11 android RefBase decStrong.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174417/signal.11.android.RefBase.decStrong.txt)
[signal 11 android_atomic_add.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174418/signal.11.android_atomic_add.txt)
[signal 11 arena_run_tree_remove.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174419/signal.11.arena_run_tree_remove.txt)
[signal 11 bctbx_iterator.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174420/signal.11.bctbx_iterator.txt)
[signal 11 belle_sip_channel_queue_message.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174421/signal.11.belle_sip_channel_queue_message.txt)
[signal 11 belle_sip_header_address_get_uri.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174422/signal.11.belle_sip_header_address_get_uri.txt)
[signal 11 belle_sip_object_cast.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174423/signal.11.belle_sip_object_cast.txt)
[signal 11 CheckNoHeldMonitors.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174424/signal.11.CheckNoHeldMonitors.txt)
[signal 11 ConcurrentCopying.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174425/signal.11.ConcurrentCopying.txt)
[signal 11 freeDataNoInit.txt](https://github.com/BelledonneCommunications/linphone-sdk/files/5174426/signal.11.freeDataNoInit.txt)

**Comment by Pokkerolli** [comment]
Hi.

Any news on my question?

Regards, Julia

**Comment by Viish** [comment]
Cf https://github.com/BelledonneCommunications/linphone-android/issues/1159
