### ISSUE TITLE
 Unknown CMake command "bc_compute_full_version

### ISSUE THREAD

**Issue by adminmastor** [BelledonneCommunications/linphone-sdk#54]
cmake .. -DENABLE_G729=YES -DENABLE_SILK=YES -DLINPHONESDK_PLATFORM=Android -DCMAKE_BUILD_TYPE=RelWithDebInfo 
CMake Error at CMakeLists.txt:33 (include):
  include could not find load file:

    bctoolbox/cmake/BcToolboxCMakeUtils.cmake

CMake Error at CMakeLists.txt:35 (bc_compute_full_version):
  Unknown CMake command "bc_compute_full_version".

-- Configuring incomplete, errors occurred!

**Comment by Viish** [comment]
Check your submdules are up-to-date:
`git submodule sync && git submodule update --recursive --init`
