### ISSUE TITLE
Remote video stream not visible on a Rockchip device

### ISSUE THREAD

**Issue by tejas-n** [BelledonneCommunications/linphone-sdk#62]
Hi, we are facing an issue on our Rockchip Android tablet. After a connection is established, the remote video stream is not visible  at all which we probably think might be due to H264 codec issues.

We came across this issue https://github.com/BelledonneCommunications/linphone-android/issues/1153 where another kind of Rockchip device issue was described. So we tried the solution suggested there which was to add our model number(`{"rockchip", "VT-TAB173-RK-GEN2", "rk3288"}`) to `media-codec-h264-decoder.cpp` similar to https://github.com/BelledonneCommunications/mediastreamer2/commit/e757ca913d87b3bbab878d3701f0bbe6e4620c78 and rebuilding the SDK and this seemed to have worked!

So do you think this is the right solution? If it is, can you add it to the SDK, please?

**Comment by Viish** [comment]
Hi,
Yes, seeing the number of people having issue with rockchip devices, I'm currently changing the algorithm a bit to generalize the workaround independently of the name of the device (using just the manufacturer and platform).
I'll keep you updated when this is available.
Cheers,

**Comment by Roger1103** [comment]
rk3288

> 嗨，
> 是的，看到有大量关于Rockchip设备的问题，我目前正在对算法进行一些更改，以独立于设备名称（仅使用制造商和平台）来推广解决方法。
> 可用时，我会及时通知您。
> 干杯，

Rk3399 has the same problem

**Comment by tejas-n** [comment]
Thanks for the update, @Viish.
Cheers!

**Comment by Viish** [comment]
It has been merged in master & release/4.4 branch, and I added rk3399 device.

**Comment by tejas-n** [comment]
Thanks, @Viish!

**Comment by Roger1103** [comment]
> It has been merged in master & release/4.4 branch, and I added rk3399 device.

I don't see any devices that add RK3399

**Comment by Roger1103** [comment]
> It has been merged in master & release/4.4 branch, and I added rk3399 device.

@Viish I don't see any devices that add RK3399

**Comment by Viish** [comment]
SDK commit 30625bf93d9ab448f9d11d595a300cc7a15bada0 for master, 30625bf93d9ab448f9d11d595a300cc7a15bada0 for release/4.4.
Mediastreamer2 commit ec4efbc724da296e451659746583b758cc1e63b2 for master, ca2c09326740ecaa3f1787cf8446c8f4c7f37836 for release/4.4.
