### ISSUE TITLE
sdk build error

### ISSUE THREAD

**Issue by nzkar** [BelledonneCommunications/linphone-sdk#67]
Hi,

When I try to build the sdk locally, I get the error below.

**
CMake Error in CMakeLists.txt:
  The CMAKE_CXX_COMPILER:

    /android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
**

Step by step,
I add sdk/tools, sdk/platform-tools and ndk to my build path. mkdir build and cmake .. -DLINPHONESDK_PLATFORM=Android. (also tried it with -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" ). Configuration is successful however when I build with "cmake --build .", the error is thrown.

Thank you.

**Comment by Viish** [comment]
Have you exported the ANDROID_NDK_HOME env variable like this?
`export ANDROID_NDK_HOME=/home/sberfini/Tools/android-ndk-r21d`

**Comment by nzkar** [comment]
I tried it still the same error.

**Comment by nzkar** [comment]
The output of cmake configuration shows 

* AAudio, AAudio Android sound card for Android 8+.
* GTK UI, Enable the GTK user interface of Linphone.
* CXX wrapper, Build the C++ wrapper for Liblinphone.

as disabled features why so? Are they disabled by default?

**Comment by Viish** [comment]
> Are they disabled by default?

Yes.
Please attach the full build output logs if you still can't build.

**Comment by nzkar** [comment]
I still can't build.

Here is the shell output.

Bacs-MacBook-Pro:~ nancy$ cd Downloads/nancysdk/linphone-sdk/build/
Bacs-MacBook-Pro:build nancy$ cmake .. -DLINPHONESDK_PLATFORM=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=ON -DENABLE_G729B_CNG=ON -DENABLE_VIDEO=ON -DENABLE_ADVANCED_IM=ON -DENABLE_DB_STORAGE=ON
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Enabled features:
 * Arch suffix, Append the android abi to shared libraries
 * Xml2, Enable bc version of libxml2
 * Sqlite, Enable bc version of sqlite3
 * Zlib, Enable bc version of zlib
 * Mbedtls, Crypto stack implementation based on mbeddtls.
 * SRTP, SRTP media encryption support.
 * ZRTP, ZRTP media encryption support.
 * WebRTC AEC, WebRTC echo canceller support.
 * WebRTC AECM, WebRTC echo canceller for mobile support.
 * G729, G.729 audio encoding/decoding support.
 * G729B CNG, G.729 annex B confort noise generation.
 * GSM, GSM audio encoding/decoding support.
 * iLBC, iLBC audio encoding/decoding support.
 * ISAC, ISAC audio encoding/decoding support.
 * OPUS, OPUS audio encoding/decoding support.
 * Speex, Speex audio encoding/decoding support.
 * Video, Ability to capture and display video.
 * jpeg, JPEG support with libjpeg-turbo.
 * qrcode, QRCode support with zxing.
 * MKV, MKV playing and recording support.
 * VPX, VPX (VP8) video encoding/decoding support.
 * LibYUV, Enable LibYUV support
 * Camera2, Android capture filter using Camera2 API for Android 8+
 * Java wrapper, Build the Java wrapper from Liblinphone.
 * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
 * VCARD, Enable vCard 4 support in Linphone and Liblinphone.
 * Assets, Enable packaging of assets (ringtones) when building the SDK.
 * Advanced IM, Enable advanced instant messaging such as group chat.
 * DB Storage, Enable the database storage.

-- Disabled features:
 * Embedded OpenH264, Embed the openh264 library instead of downloading it from Cisco.
 * Unit tests, Enable unit tests support with BCUnit library.
 * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
 * Doc, Enable documentation generation with Doxygen
 * Tools, Enable tools binary compilation.
 * unmaintained, Allow inclusion of unmaintained code in the build.
 * Soci mysql, Enable mysql support of SOCI
 * Sanitizer, Enable Clang sanitizer
 * HW Sanitizer, Enable Android HW sanitizer
 * Polarssl, Crypto stack implementation based on polarssl.
 * Tunnel, Secure tunnel for SIP/RTP (require license).
 * RTP Map always in SDP, Always include rtpmap in SDP.
 * mDNS, Multicast DNS support
 * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
 * Non free codecs, Allow inclusion of non-free codecs in the build.
 * WASAPI, Windows Audio Session API (WASAPI) sound card support.
 * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB, AMR wide-band audio encoding/decoding support (require license).
 * Codec2, Codec2 audio encoding/decoding support.
 * G726, G.726 audio encoding/decoding support.
 * Silk, Silk audio encoding/decoding support.
 * WebRTC VAD, WebRTC voice activation detector support.
 * BV16, BroadVoice 16 audio encoding/decoding support.
 * V4L, Ability to capture and display video using libv4l2 .
 * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * H263, H263 video encoding/decoding support (require license).
 * H263p, H263+ video encoding/decoding support (require license).
 * MPEG4, MPEG4 video encoding/decoding support (require license).
 * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
 * X264, H.264 video encoding support with the x264 library (require license).
 * AAudio, AAudio Android sound card for Android 8+.
 * PCAP, PCAP support.
 * GTK UI, Enable the GTK user interface of Linphone.
 * CXX wrapper, Build the C++ wrapper for Liblinphone.
 * CSharp wrapper, Build the C# wrapper from Liblinphone.
 * Swift wrapper, Build the Swift wrapper sources from Liblinphone.
 * Swift wrapper compilation, Compile and package the swift wrapper framework. Require at least cmake 3.16.3.
 * Jazzy doc, Build the Swift doc from Liblinphone.
 * LIME, Enable Linphone IM Encryption support in  Liblinphone.
 * NLS, Enable internationalization of Linphone and Liblinphone.
 * Update Check, Enable update check.
 * Relative prefix, liblinphone and mediastreamer will look for their respective ressources relatively to their location.

-- Setting build type to 'RelWithDebInfo' as none was specified

  ***************************************************************************
  ***************************************************************************
  ***** Linphone SDK without third party GPL software                   *****
  ***** If you acquired a proprietary license from Belledonne           *****
  ***** Communications, this SDK can be used to create                  *****
  ***** a proprietary Linphone-based application.                       *****
  ***************************************************************************
  ***************************************************************************
  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/nancy/Downloads/nancysdk/linphone-sdk/build
bacss-MacBook-Pro:build nancy$ cmake --build .
Scanning dependencies of target gradle-clean

> Configure project :
Old java wrapper detected, adding it to sources and removing some incompatible classes

> Task :clean UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 561ms
1 actionable task: 1 up-to-date
[  0%] Built target gradle-clean
Scanning dependencies of target android-arm64
[  2%] Creating directories for 'android-arm64'
[  5%] No download step for 'android-arm64'
[  7%] No update step for 'android-arm64'
[ 10%] No patch step for 'android-arm64'
[ 13%] Performing configure step for 'android-arm64'
loading initial cache file /Users/nancy/Downloads/nancysdk/linphone-sdk/build/android-arm64-prefix/tmp/android-arm64-cache-RelWithDebInfo.cmake
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error in CMakeLists.txt:
  The CMAKE_C_COMPILER:

    /Users/nancy/Tools/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error in CMakeLists.txt:
  The CMAKE_CXX_COMPILER:

    /Users/nancy/Tools/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/Users/nancy/Downloads/nancysdk/linphone-sdk/build/android-arm64/CMakeFiles/CMakeOutput.log".
make[2]: *** [android-arm64-prefix/src/android-arm64-stamp/android-arm64-configure] Error 1
make[1]: *** [CMakeFiles/android-arm64.dir/all] Error 2
make: *** [all] Error 2
bacss-MacBook-Pro:build nancy$ 


Inside CMakeOutput.log there is only the target and host versions:
The target system is: Android - 1 - aarch64
The host system is: Darwin - 19.5.0 - x86_64

**Comment by Viish** [comment]
Can you show me how you configured your env variables?
Also, what is the result of the following command? `which ndk-build`

**Comment by Viish** [comment]
Also, delete your build folder and start again from scratch.

**Comment by nzkar** [comment]
I delete my build folder and start from scratch each time.

ENV VARIABLES:
export ANDROID_HOME=/Users/nancy/Library/Android/sdk
export ANDROID_SDK_ROOT=/Users/nancy/Library/Android/sdk
export ANDROID_NDK_HOME=/Users/nancy/Tools/android-ndk-r21d
export PATH="/Users/nancy/Tools/android-ndk-r21d:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:${PATH}"

NDK-BUILD:
Bacs-MacBook-Pro:build nancy$ which ndk-build
/Users/nancy/Tools/android-ndk-r21d/ndk-build

**Comment by Viish** [comment]
Maybe there is an issue in your NDK. Delete it, download it again and retry.
Also ANDROID_SDK_ROOT isn't required and you need to add the $ANDROID_SDK_ROOT/tools/bin to your path (but I doubt this is the reason why it fails at this point).

**Comment by nzkar** [comment]
Hi, I managed to pass the clang errors with the new download of ndk-r21d. But after a long build time, following error occured.

> Task :compileReleaseJavaWithJavac
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/nancy/Downloads/nancysdk/linphone-sdk/liblinphone/wrappers/java/classes/org/linphone/core/tools/PushNotificationUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings

> Task :extractReleaseAnnotations
> Task :mergeReleaseGeneratedProguardFiles
> Task :mergeReleaseConsumerProguardFiles
> Task :syncReleaseLibJars
> Task :bundleReleaseAar
> Task :compileReleaseSources
> Task :verifyReleaseResources
> Task :assembleRelease

> Task :releaseJavadoc FAILED
/Users/nancy/Downloads/nancysdk/linphone-sdk/build/linphone-sdk/android-arm64/share/linphonej/java/org/linphone/core/Factory.java:34: error: package org.linphone.core.tools.h264 does not exist
import org.linphone.core.tools.h264.OpenH264DownloadHelper;
                                   ^
/Users/nancy/Downloads/nancysdk/linphone-sdk/build/linphone-sdk/android-arm64/share/linphonej/java/org/linphone/core/Factory.java:55: error: cannot find symbol
    abstract public OpenH264DownloadHelper createOpenH264DownloadHelper(Context context);
                    ^
  symbol:   class OpenH264DownloadHelper
  location: class Factory
/Users/nancy/Downloads/nancysdk/linphone-sdk/build/linphone-sdk/android-arm64/share/linphonej/java/org/linphone/core/Factory.java:541: error: cannot find symbol
    public OpenH264DownloadHelper createOpenH264DownloadHelper(Context context) {
           ^
  symbol:   class OpenH264DownloadHelper
  location: class FactoryImpl
3 errors

> Task :javaPreCompileDebug
> Task :generateDebugRFile
> Task :mergeDebugNativeLibs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':releaseJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/nancy/Downloads/nancysdk/linphone-sdk/build/linphone-sdk/bin/tmp/releaseJavadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 18s
42 actionable tasks: 42 executed
CMake Error at /Users/nancy/Downloads/nancysdk/linphone-sdk/cmake/Android/GenerateSDK.cmake:49 (message):
  Gradle assemble failed


make[2]: *** [CMakeFiles/sdk] Error 1
make[1]: *** [CMakeFiles/sdk.dir/all] Error 2
make: *** [all] Error 2

**Comment by Viish** [comment]
Hi,
Simply update the sdk to the latest version on master branch, it will fix this issue.
Cheers,

**Comment by nzkar** [comment]
Successfully built it thank you!
