### ISSUE TITLE
sal media description

### ISSUE THREAD

**Issue by gregperezz** [BelledonneCommunications/linphone-sdk#69]
Hi there, android application cannot answer some calls. Sal_media_description_has_srtp method returns false if there are two media description lines in sdp resulting in a 488 return message. Am I missing something? Thanks in advance.

**Comment by gregperezz** [comment]
Weirdly it now connects the end points however there is one way voice only.

https://www.linphone.org:444//tmp/5f80558e71668_f0c9a10d2866fdca9be0.gz

**Comment by gregperezz** [comment]
Hi, do you have any ideas on this issue?

**Comment by Viish** [comment]
From your logs you don't receive audio, but I can't say more without looking at the logs of the remote party.
Either it doesn't send audio, or there is a stream configuration issue so it doesn't send it to the right place.
Anyway please open a new issue with the logs of both devices during a call.

**Comment by Viish** [comment]
From your logs in https://github.com/BelledonneCommunications/linphone-android/issues/1196,

I think it comes from this:
```
2020-10-13 10:16:30:955 [org.linphone/mediastreamer] ERROR Unsupported crypto suite 'F8_128_HMAC_SHA1_80' with parameters ''
2020-10-13 10:16:30:955 [org.linphone/liblinphone] WARNING Failed to parse crypto-algo: 'F8_128_HMAC_SHA1_80'
```
causing the SDP to disable audio stream:
```
v=0
o=testaccountnum3 2296 1042 IN IP4 192.168.1.18
s=Talk
c=IN IP4 192.168.1.18
t=0 0
a=Ik:wp0G57/B3d883hQAuYNeOjUakFR45qHm9sPRoKibVV8=
m=audio 7078 RTP/SAVP 0 8 101
a=rtpmap:101 telephone-event/8000
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:zekuisncECyDIVTKPvcgHdLWtCEv8kFGmSboj+ce
m=audio 0 RTP/AVP 0
a=inactive
```

**Comment by gregperezz** [comment]
But in the 200 OK SDP Linphone replies with the crypto line below.

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:YCT4LOZR1Q7yilI4Dpfmtgan3uzwVercnGry/7bk

**Comment by gregperezz** [comment]
Hi @Viish could you check the problem further?
