### ISSUE TITLE
Unable to load VCard grammar.

### ISSUE THREAD

**Issue by TheInfiniter** [BelledonneCommunications/linphone-sdk#77]
I am starting to learn linphone-sdk, and encountered this grammar problem. I cloned this repo to my PC with Debian-type system on it, built the sdk according to Readme.md, then created a console project in QT Creator, copied the "Basic Registration" example from [here](https://linphone.org/snapshots/docs/liblinphone/4.5.0/multilang//samples/samples.html), and then added all libraries (app couldn't even be built without all lib*.so from lib folder attached). When I run this console app, it tells me this:

> belr-error-Could not load grammar vcard_grammar, because the file could not be located
> bctbx-fatal-Unable to load VCARD grammar.

Perhaps I bult it somehow wrong, or something? I saw that file in source files of linphone-sdk. What should I do with this grammar file?

**Comment by Viish** [comment]
Our SDK builds a share folder you need to keep. If you moved it somewhere else, make sure linphone_factory_get_top_resources_dir() returns the path to it.
Otherwise you can also disable vCard support when you build the SDK.

**Comment by TheInfiniter** [comment]
linphone_factory_get_top_resources_dir() return correct path to Share folder in build directory. But this error is still remains.
