### ISSUE TITLE
No audio (inbound & outbound) when using Android Telecom Framework 

### ISSUE THREAD

**Issue by jeremynorman89** [BelledonneCommunications/linphone-sdk#83]
Hey,

The SDK is working great but as soon as I try and hook-up the [Android Telecom Framework](https://developer.android.com/guide/topics/connectivity/telecom#integrateCalling) (as a self-managed calling app) I no longer receive any audio in either direction.

I have implemented the framework with a different VoIP library before and not run into this issue so I'm reasonably sure the issue is not with the implementation.

My logs for a call with the framework enabled are here: https://gist.github.com/jeremynorman89/bbcf0db9a3559a9e082b758662ce27af

Thanks!

**Comment by Viish** [comment]
Hi,

Just so you know, we made a while back a prototype for Android Telecom Framework that was working fine, see https://github.com/BelledonneCommunications/linphone-android branch `feature/use_android_native_dialer`.

Also you are using a SDK from master branch that can be instable. Please try with latest 4.4 release (4.4.9 at this time).

Finally, please attach logs from the start of the app to help diagnose the issue.

Cheers,

**Comment by jeremynorman89** [comment]
> Hi,
> 
> Just so you know, we made a while back a prototype for Android Telecom Framework that was working fine, see https://github.com/BelledonneCommunications/linphone-android branch `feature/use_android_native_dialer`.
> 
> Also you are using a SDK from master branch that can be instable. Please try with latest 4.4 release (4.4.9 at this time).
> 
> Finally, please attach logs from the start of the app to help diagnose the issue.
> 
> Cheers,

I did not know about that, that was really helpful and I found the issue. It was a problem with the implementation of the Telecom Framework (the other library didn't require this for some odd reason), setting the following on the connection fixed it:

`audioModeIsVoip = true` 

Thank you so much!

**Comment by Viish** [comment]
You're very welcome :) and good luck with your project !
