### ISSUE TITLE
linphone-sdk build bctoolbox failed

### ISSUE THREAD

**Issue by zxpgo** [BelledonneCommunications/linphone-sdk#91]
-- Using mbedTLS
-- Using Decaf
-- DTLS SRTP available
-- Configuring incomplete, errors occurred!
See also "/Users/a406/work/linphone-sdk/build-4.4.2/WORK/ios-x86_64/Build/bctoolbox/CMakeFiles/CMakeOutput.log".
See also "/Users/a406/work/linphone-sdk/build-4.4.2/WORK/ios-x86_64/Build/bctoolbox/CMakeFiles/CMakeError.log".
make[1]: *** [/Users/a406/work/linphone-sdk/build-4.4.2/WORK/ios-x86_64/Stamp/EP_bctoolbox/Debug-iphonesimulator/EP_bctoolbox-configure] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution CMake\ Rules /Users/a406/work/linphone-sdk/build-4.4.2/ios-x86_64/Project.build/Debug-iphonesimulator/EP_bctoolbox.build/Script-22EFF921860B4679BF481F48.sh
(1 failure)
make: *** [/Users/a406/work/linphone-sdk/build-4.4.2/ios-x86_64-prefix/src/ios-x86_64-stamp/Debug/ios-x86_64-build] Error 65
Command /bin/sh failed with exit code 2

** BUILD FAILED **

Users/a406/work/linphone-sdk/build-4.4.2/WORK/ios-x86_64/Build/bctoolbox/CMakeFiles/**CMakeError.log** is as follow:

ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld Debug/cmTC_66964.app/cmTC_66964 normal x86_64
(1 failure)

**Comment by KyronNextLevel** [comment]
Issue closed, as we do not support anymore 4.4 SDK. Please reopen another issue referencing this one if you notice the same problem with new releases
