### ISSUE TITLE
Crash when call has been rejected from phone which has voice email

### ISSUE THREAD

**Issue by djkskqyr3** [BelledonneCommunications/linphone-sdk#98]
Hello, linphone
I hope you are doing well.

I have crash issue when the call has been rejected from real phone number.
Here is test environment and case.

Bob : **linphone ios app**
Cat : **real phone number**

and here is app setting. (TLS and disable outbound proxy)

![image](https://user-images.githubusercontent.com/1333215/103290727-2c280e00-4a25-11eb-8a3d-307548de16e7.png)

When I call from Bob to Cat, Cat have rejected incoming call.
As soon as rejected the call, Bob got crash and killed linphone app.

I have attached crash log file and please search "Here is crash and I reopen app"
[linphone_log.zip](https://github.com/BelledonneCommunications/linphone-sdk/files/5750960/linphone_log.zip)

also here is some file for help 
![image](https://user-images.githubusercontent.com/1333215/103289633-9f7c5080-4a22-11eb-93c9-888db28a0a05.png)
[crashlog.zip](https://github.com/BelledonneCommunications/linphone-sdk/files/5750971/crashlog.zip)

This crash occur very often, maybe 70~80%
Please help me, Thank you

**Comment by djkskqyr3** [comment]
if Outbound proxy is enabled then there is no crash

**Comment by djkskqyr3** [comment]
in `**try_early_media_forking**` function, I was expected this message "Early media response received from another branch, checking if media can be forked to this new destination."
But I can not see this message since linphone app has crash and closed.

**Comment by djkskqyr3** [comment]
linphone sdk 4.3.0 has no crash with same server and same app.
from 4.4.0, there is crash

**Comment by djkskqyr3** [comment]
@Viish do you have chance to check my issue?
Thanks

**Comment by Viish** [comment]
If the outbound proxy fixes it, you should use it.
Problem is with your server: After the early media (183) is received, the no early-media ringing (180) is received and then another early media (183) is received, which isn't correct.

**Comment by djkskqyr3** [comment]
@Viish Thanks for your reply.

We are using Flexisip proxy server as a push gateway.

AUC ----------->Flexisip--------->Switch------------>Phone (outbound proxy)
AUC ------------------------------>Switch------------>Phone (no outbound proxy)

While we are using Flexisip with outbound proxy, we have the Bye-Packet issue.
When the call has been terminated by the callee side, there is a bye-packet issue.
(When a call has been terminated by the caller, there is no problem.)
By this issue, the caller side is keeping a call session with no media.
After 25~30sec (or over), the caller side will be terminated with no media forcely.
In the BYE message, it seems that there is a wrong RRUL.
As I know, BYE RRUL should be the original inviter's Contact.

Ex: Original inviter's Contact was 123456@switch_server
But BYE RRUL is 123456@flexisip_server

In case, we can not fix Switch server since that is not our server.
What should I do in next step? please advice any suggestion.
Thanks

**Comment by djkskqyr3** [comment]
linphone sdk 4.3.0 has no crash with same server and same app.
from 4.4.0, there is crash

**Comment by Viish** [comment]
You can always try with latest 4.4.x or test with 4.5.0-beta just in case.
Otherwise open an issue on our flexisip repository and/or send an email to our mailing list.

**Comment by djkskqyr3** [comment]
Ok, I am using 4.4.21 (pod linphone-sdk)

In case, where is the problem? linphone-sdk ? flexisip ?

**Comment by djkskqyr3** [comment]
https://github.com/BelledonneCommunications/linphone-android/issues/498#issuecomment-470813721

>Comment out "op->mRoot->mCallbacks.call_ringing(op);":
This fixed the crash issue for me

**Comment by Viish** [comment]
Just so you know, your crash has been fixed in 4.5.0-beta version starting this commit: bd59c3bec88b97cc21679049de88d147a34359b8

**Comment by djkskqyr3** [comment]
Thanks so much, should I build sdk from source code?
or can I install 4.5 beta from Pod?

**Comment by djkskqyr3** [comment]
and sorry, there is another crash issue on app startup.
This will occur 50% of every open app. (open 10 times, 5 crash)

Here is the crash log

[testflight_feedback (2).zip](https://github.com/BelledonneCommunications/linphone-sdk/files/5795475/testflight_feedback.2.zip)

Please help me, Thanks again

**Comment by Viish** [comment]
> can I install 4.5 beta from Pod?

Yes.

> there is another crash issue on app startup.

First, check the issue still exists with latest version. If not, please open a new issue with logs.

**Comment by djkskqyr3** [comment]
Ok, I will check 4.5 sdk, Thanks ,

**Comment by djkskqyr3** [comment]
I tried to tested with **linphone-sdk-ios-4.5.0-beta.32+b97d0be** and installed by Pod.
But it won't compile , there is a lot of compile error on msgNotificationService/Utils.swift
So I have compiled sdk by myself, it's **linphone-sdk-ios-4.5.0-alpha.296+4a3c4b2**
There is no compile error, and still there is crash issue on second 183.

Both has been installed by following command:
PODFILE_PATH=build pod install

**Comment by Viish** [comment]
Check branch release/4.4 from linphone-iphone project (https://github.com/BelledonneCommunications/linphone-iphone/tree/release/4.4) to see how to integrate SDK 4.5.

**Comment by djkskqyr3** [comment]
Thanks so much.
Finally I got success build regarding to release/4.4 guide.
I will test more tomorrow

Anyway When app go to background mode (by clicking device Home button), there is crash after 1~3sec.

https://github.com/BelledonneCommunications/linphone-iphone/blob/4bf9105c308cc506e5bf6b752cb28962d017f2ef/Classes/CoreManager.swift#L60

and here is my fix.

    @objc func stopLinphoneCore() {
        if (lc?.callsNb == 0) {
            //stop iterate when core is off
            //lc?.stopAsync()

            stopIterateTimer()
            lc?.stop()
        }
    }

Thanks

**Comment by djkskqyr3** [comment]
Hi @Viish I have tested beta 4.5.

Great job, 
**when incoming call rejected, there is crash** => this crash has been fixed, Thanks

anyway, there is crash issue with this : 
> and sorry, there is another crash issue on app startup.
> This will occur 50% of every open app. (open 10 times, 5 crash)

I will create new issue, Thanks
